declare let lstrip: any
declare let rstrip: any
declare let strip: any
declare let has_words: any
declare let hljs: any
declare let replace_all: any
declare const validate_email: any
declare const validate_phone: any
declare const validate_name: any
declare const validate_url: any
declare const strip_html: any
declare const get_number_format: any
declare const qz: any
declare const sha256: any
declare const READ: any
declare const WRITE: any
declare const CREATE: any
declare const DELETE: any
declare const SUBMIT: any
declare const CANCEL: any
declare const AMEND: any
