from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class PricingRuleGenerated(FrappeModel):
    doctype = 'Pricing Rule'
    title = models.CharField(max_length=140, blank=True, null=True, default='')
    disable = models.SmallIntegerField(default=0)
    apply_on = models.CharField(max_length=140, blank=True, null=True, default='Item Code')
    price_or_product_discount = models.CharField(max_length=140, blank=True, null=True, default='')
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    mixed_conditions = models.SmallIntegerField(default=0)
    is_cumulative = models.SmallIntegerField(default=0)
    coupon_code_based = models.SmallIntegerField(default=0)
    apply_rule_on_other = models.CharField(max_length=140, blank=True, null=True, default='')
    other_item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    other_item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    other_brand = models.CharField(max_length=140, blank=True, null=True, default='')
    selling = models.SmallIntegerField(default=0)
    buying = models.SmallIntegerField(default=0)
    applicable_for = models.CharField(max_length=140, blank=True, null=True, default='')
    customer = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_group = models.CharField(max_length=140, blank=True, null=True, default='')
    territory = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_partner = models.CharField(max_length=140, blank=True, null=True, default='')
    campaign = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_group = models.CharField(max_length=140, blank=True, null=True, default='')
    min_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    max_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    min_amt = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    max_amt = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    valid_from = models.DateField(null=True, blank=True)
    valid_upto = models.DateField(null=True, blank=True)
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_type = models.CharField(max_length=140, blank=True, null=True, default='Percentage')
    margin_rate_or_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate_or_discount = models.CharField(max_length=140, blank=True, null=True, default='Discount Percentage')
    apply_discount_on = models.CharField(max_length=140, blank=True, null=True, default='Grand Total')
    rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    for_price_list = models.CharField(max_length=140, blank=True, null=True, default='')
    same_item = models.SmallIntegerField(default=0)
    free_item = models.CharField(max_length=140, blank=True, null=True, default='')
    free_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    free_item_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    free_item_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    threshold_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    priority = models.CharField(max_length=140, blank=True, null=True, default='')
    apply_multiple_pricing_rules = models.SmallIntegerField(default=0)
    apply_discount_on_rate = models.SmallIntegerField(default=0)
    validate_applied_rule = models.SmallIntegerField(default=0)
    rule_description = models.TextField(blank=True, null=True, default='')
    promotional_scheme_id = models.CharField(max_length=140, blank=True, null=True, default='')
    promotional_scheme = models.CharField(max_length=140, blank=True, null=True, default='')
    condition = models.TextField(blank=True, null=True, default='')
    is_recursive = models.SmallIntegerField(default=0)
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='PRLE-.####')
    round_free_qty = models.SmallIntegerField(default=0)
    recurse_for = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    apply_recursion_over = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    has_priority = models.SmallIntegerField(default=0)
    dont_enforce_free_item_qty = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
