from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class SalesOrderItemGenerated(FrappeChildModel):
    doctype = 'Sales Order Item'
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    is_product_bundle = models.SmallIntegerField(default=0)
    product_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    delivery_date = models.DateField(null=True, blank=True)
    image = models.TextField(blank=True, null=True, default='')
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    uom = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_factor = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    margin_type = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_rate_or_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    pricing_rules = models.TextField(blank=True, null=True, default='')
    is_free_item = models.SmallIntegerField(default=0)
    net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    delivered_by_supplier = models.SmallIntegerField(default=0)
    skip_delivery = models.SmallIntegerField(default=0)
    supplier = models.CharField(max_length=140, blank=True, null=True, default='')
    weight_per_unit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    target_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    prevdoc_docname = models.CharField(max_length=140, blank=True, null=True, default='')
    brand = models.CharField(max_length=140, blank=True, null=True, default='')
    item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    billed_amt = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    closed = models.SmallIntegerField(default=0)
    valuation_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    gross_profit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    blanket_order = models.CharField(max_length=140, blank=True, null=True, default='')
    blanket_order_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    projected_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    actual_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ordered_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    delivered_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    work_order_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    returned_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    item_tax_template = models.CharField(max_length=140, blank=True, null=True, default='')
    page_break = models.SmallIntegerField(default=0)
    planned_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    produced_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    item_tax_rate = models.TextField(blank=True, null=True, default='')
    transaction_date = models.DateField(null=True, blank=True)
    additional_notes = models.TextField(blank=True, null=True, default='')
    against_blanket_order = models.SmallIntegerField(default=0)
    bom_no = models.CharField(max_length=140, blank=True, null=True, default='')
    stock_uom_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    grant_commission = models.SmallIntegerField(default=0)
    picked_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    purchase_order = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    quotation_item = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request_item = models.CharField(max_length=140, blank=True, null=True, default='')
    reserve_stock = models.SmallIntegerField(default=1)
    stock_reserved_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    production_plan_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    is_stock_item = models.SmallIntegerField(default=0)
    distributed_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    company_total_stock = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    cost_center = models.CharField(max_length=140, blank=True, null=True, default=':Company')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    subcontracted_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    fg_item = models.CharField(max_length=140, blank=True, null=True, default='')
    fg_item_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    requested_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)

    class Meta:
        abstract = True
