from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class DeliveryNoteGenerated(FrappeModel):
    doctype = 'Delivery Note'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    customer = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_name = models.CharField(max_length=140, blank=True, null=True, default='')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    posting_date = models.DateField(null=True, blank=True)
    posting_time = models.TimeField(null=True, blank=True)
    set_posting_time = models.SmallIntegerField(default=0)
    is_return = models.SmallIntegerField(default=0)
    issue_credit_note = models.SmallIntegerField(default=0)
    return_against = models.CharField(max_length=140, blank=True, null=True, default='')
    po_no = models.TextField(blank=True, null=True, default='')
    po_date = models.DateField(null=True, blank=True)
    shipping_address_name = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_address = models.TextField(blank=True, null=True, default='')
    shipping_contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_contact_display = models.TextField(blank=True, null=True, default='')
    shipping_contact_mobile = models.TextField(blank=True, null=True, default='')
    shipping_contact_email = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_display = models.TextField(blank=True, null=True, default='')
    contact_mobile = models.TextField(blank=True, null=True, default='')
    contact_email = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_address = models.CharField(max_length=140, blank=True, null=True, default='')
    tax_id = models.CharField(max_length=140, blank=True, null=True, default='')
    address_display = models.TextField(blank=True, null=True, default='')
    company_address = models.CharField(max_length=140, blank=True, null=True, default='')
    company_address_display = models.TextField(blank=True, null=True, default='')
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    selling_price_list = models.CharField(max_length=140, blank=True, null=True, default='')
    price_list_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    plc_conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ignore_pricing_rule = models.SmallIntegerField(default=0)
    set_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    scan_barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    total_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_net_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    tax_category = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_rule = models.CharField(max_length=140, blank=True, null=True, default='')
    taxes_and_charges = models.CharField(max_length=140, blank=True, null=True, default='')
    other_charges_calculation = models.TextField(blank=True, null=True, default='')
    base_total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    apply_discount_on = models.CharField(max_length=140, blank=True, null=True, default='Grand Total')
    base_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    tc_name = models.CharField(max_length=140, blank=True, null=True, default='')
    terms = models.TextField(blank=True, null=True, default='')
    transporter = models.CharField(max_length=140, blank=True, null=True, default='')
    driver = models.CharField(max_length=140, blank=True, null=True, default='')
    lr_no = models.CharField(max_length=140, blank=True, null=True, default='')
    vehicle_no = models.CharField(max_length=140, blank=True, null=True, default='')
    transporter_name = models.CharField(max_length=140, blank=True, null=True, default='')
    driver_name = models.CharField(max_length=140, blank=True, null=True, default='')
    lr_date = models.DateField(null=True, blank=True)
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    per_billed = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    customer_group = models.CharField(max_length=140, blank=True, null=True, default='')
    territory = models.CharField(max_length=140, blank=True, null=True, default='')
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    select_print_heading = models.CharField(max_length=140, blank=True, null=True, default='')
    language = models.CharField(max_length=140, blank=True, null=True, default='')
    print_without_amount = models.SmallIntegerField(default=0)
    group_same_items = models.SmallIntegerField(default=0)
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    per_installed = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    installation_status = models.CharField(max_length=140, blank=True, null=True, default='')
    excise_page = models.CharField(max_length=140, blank=True, null=True, default='')
    instructions = models.TextField(blank=True, null=True, default='')
    auto_repeat = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_partner = models.CharField(max_length=140, blank=True, null=True, default='')
    commission_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_commission = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    is_internal_customer = models.SmallIntegerField(default=0)
    inter_company_reference = models.CharField(max_length=140, blank=True, null=True, default='')
    per_returned = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    set_target_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    represents_company = models.CharField(max_length=140, blank=True, null=True, default='')
    disable_rounded_total = models.SmallIntegerField(default=0)
    dispatch_address_name = models.CharField(max_length=140, blank=True, null=True, default='')
    dispatch_address = models.TextField(blank=True, null=True, default='')
    amount_eligible_for_commission = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    incoterm = models.CharField(max_length=140, blank=True, null=True, default='')
    named_place = models.CharField(max_length=140, blank=True, null=True, default='')
    delivery_trip = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_medium = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_content = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_source = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_campaign = models.CharField(max_length=140, blank=True, null=True, default='')
    company_contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    last_scanned_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    title = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
