from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class BomGenerated(FrappeModel):
    doctype = 'BOM'
    item = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    uom = models.CharField(max_length=140, blank=True, null=True, default='')
    set_qty_based_on_percentage = models.SmallIntegerField(default=0)
    quantity = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    is_active = models.SmallIntegerField(default=1)
    is_default = models.SmallIntegerField(default=1)
    with_operations = models.SmallIntegerField(default=0)
    inspection_required = models.SmallIntegerField(default=0)
    allow_alternative_item = models.SmallIntegerField(default=0)
    quality_inspection_template = models.CharField(max_length=140, blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    transfer_material_against = models.CharField(max_length=140, blank=True, null=True, default='Work Order')
    conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    rm_cost_as_per = models.CharField(max_length=140, blank=True, null=True, default='Valuation Rate')
    buying_price_list = models.CharField(max_length=140, blank=True, null=True, default='')
    routing = models.CharField(max_length=140, blank=True, null=True, default='')
    operating_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    raw_material_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_operating_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_raw_material_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    show_in_website = models.SmallIntegerField(default=0)
    route = models.TextField(blank=True, null=True, default='')
    website_image = models.TextField(blank=True, null=True, default='')
    thumbnail = models.CharField(max_length=140, blank=True, null=True, default='')
    web_long_description = models.TextField(blank=True, null=True, default='')
    show_items = models.SmallIntegerField(default=0)
    show_operations = models.SmallIntegerField(default=0)
    plc_conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    price_list_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    has_variants = models.SmallIntegerField(default=0)
    process_loss_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    process_loss_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    fg_based_operating_cost = models.SmallIntegerField(default=0)
    operating_cost_per_bom_quantity = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    bom_creator = models.CharField(max_length=140, blank=True, null=True, default='')
    bom_creator_item = models.CharField(max_length=140, blank=True, null=True, default='')
    track_semi_finished_goods = models.SmallIntegerField(default=0)
    default_source_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    default_target_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    is_phantom_bom = models.SmallIntegerField(default=0)
    secondary_items_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_secondary_items_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    cost_allocation = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    cost_allocation_per = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    backflush_based_on = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
