from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class NavariKraEtimsSettingsGenerated(FrappeModel):
    doctype = 'Navari KRA eTims Settings'
    env = models.CharField(max_length=140, blank=True, null=True, default='Sandbox')
    sandbox = models.SmallIntegerField(default=1)
    is_active = models.SmallIntegerField(default=0)
    server_url = models.CharField(max_length=140, blank=True, null=True, default='https://api-dev.slade360edi.com/erp')
    auth_server_url = models.CharField(max_length=140, blank=True, null=True, default='https://accounts.multitenant.slade360.co.ke')
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    workstation = models.CharField(max_length=140, blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    tin = models.CharField(max_length=140, blank=True, null=True, default='')
    bhfid = models.CharField(max_length=140, blank=True, null=True, default='')
    department = models.CharField(max_length=140, blank=True, null=True, default='')
    notices_refresh_frequency = models.CharField(max_length=140, blank=True, null=True, default='Hourly')
    notices_refresh_freq_cron_format = models.CharField(max_length=140, blank=True, null=True, default='')
    codes_refresh_frequency = models.CharField(max_length=140, blank=True, null=True, default='Hourly')
    codes_refresh_freq_cron_format = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_auto_submission_enabled = models.SmallIntegerField(default=0)
    sales_information_submission = models.CharField(max_length=140, blank=True, null=True, default='Both')
    max_allowed_revisions = models.IntegerField(null=True, blank=True)
    enable_verification_redirect = models.SmallIntegerField(default=1)
    purchase_auto_submission_enabled = models.SmallIntegerField(default=0)
    purchase_information_submission = models.CharField(max_length=140, blank=True, null=True, default='Both')
    stock_auto_submission_enabled = models.SmallIntegerField(default=0)
    stock_information_submission = models.CharField(max_length=140, blank=True, null=True, default='Both')
    sales_information_submission_timeframe = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    maximum_sales_information_submission_attempts = models.IntegerField(null=True, blank=True)
    purchase_information_submission_timeframe = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    maximum_purchase_information_submission_attempts = models.IntegerField(null=True, blank=True)
    stock_information_submission_timeframe = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    maximum_stock_information_submission_attempts = models.IntegerField(null=True, blank=True)
    etims_country_of_origin = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_taxation_type = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_item_classification = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_country_of_origin_code = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_taxation_type_name = models.CharField(max_length=140, blank=True, null=True, default='')
    item_classification_name = models.TextField(blank=True, null=True, default='')
    etims_packaging_unit = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_packaging_unit_code = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_unit_of_quantity = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_unit_of_quantity_code = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_product_type = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_item_type = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_product_type_name = models.CharField(max_length=140, blank=True, null=True, default='')
    etims_item_type_name = models.CharField(max_length=140, blank=True, null=True, default='')
    client_id = models.CharField(max_length=140, blank=True, null=True, default='')
    client_secret = models.TextField(blank=True, null=True, default='')
    auth_username = models.CharField(max_length=140, blank=True, null=True, default='')
    auth_password = models.TextField(blank=True, null=True, default='')
    access_token = models.CharField(max_length=140, blank=True, null=True, default='')
    refresh_token = models.CharField(max_length=140, blank=True, null=True, default='')
    token_expiry = FrappeDateTimeField(null=True, blank=True)
    expires_in = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
