# Generated by Django 5.0.14 on 2026-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0005_customfield_defaultvalue_propertysetter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDimension',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', max_length=140)),
                ('fieldname', models.CharField(blank=True, default='', max_length=140)),
                ('document_type', models.CharField(blank=True, default='', max_length=140)),
                ('disabled', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Accounting Dimension',
                'db_table': 'tabAccounting Dimension',
                'ordering': ['creation'],
            },
        ),
        migrations.CreateModel(
            name='AccountingDimensionDetail',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('company', models.CharField(blank=True, default='', max_length=140)),
                ('reference_document', models.CharField(blank=True, default='', max_length=140)),
                ('default_dimension', models.CharField(blank=True, default='', max_length=140)),
                ('mandatory_for_bs', models.SmallIntegerField(default=0)),
                ('mandatory_for_pl', models.SmallIntegerField(default=0)),
                ('automatically_post_balancing_accounting_entry', models.SmallIntegerField(default=0)),
                ('offsetting_account', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Accounting Dimension Detail',
                'db_table': 'tabAccounting Dimension Detail',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='RepostAllowedTypes',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('document_type', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Repost Allowed Types',
                'db_table': 'tabRepost Allowed Types',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJobType',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('method', models.CharField(blank=True, default='', max_length=140)),
                ('stopped', models.SmallIntegerField(default=0)),
                ('create_log', models.SmallIntegerField(default=0)),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
                ('cron_format', models.CharField(blank=True, default='', max_length=140)),
                ('queue', models.CharField(blank=True, default='', max_length=140)),
                ('frequency', models.CharField(blank=True, default='', max_length=140)),
                ('server_script', models.CharField(blank=True, default='', max_length=140)),
                ('next_execution', models.DateTimeField(blank=True, null=True)),
                ('scheduler_event', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Scheduled Job Type',
                'db_table': 'tabScheduled Job Type',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerEvent',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('scheduled_against', models.CharField(blank=True, default='', max_length=140)),
                ('method', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Scheduler Event',
                'db_table': 'tabScheduler Event',
                'ordering': ['-creation'],
            },
        ),
    ]
