# Generated by Django 5.0.14 on 2026-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0009_inventorydimension_purchasereceiptitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('enabled', models.SmallIntegerField(default=1)),
                ('price_list_name', models.CharField(blank=True, default='', max_length=140)),
                ('currency', models.CharField(blank=True, default='', max_length=140)),
                ('buying', models.SmallIntegerField(default=0)),
                ('selling', models.SmallIntegerField(default=0)),
                ('price_not_uom_dependent', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Price List',
                'db_table': 'tabPrice List',
                'ordering': ['creation'],
            },
        ),
    ]
