# Generated by Django 5.0.14 on 2026-10-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0011_activitytype_addresstemplate_emailtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttributeValue',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('attribute_value', models.CharField(blank=True, default='', max_length=140)),
                ('abbr', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Item Attribute Value',
                'db_table': 'tabItem Attribute Value',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='PriceListCountry',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('country', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Price List Country',
                'db_table': 'tabPrice List Country',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='SerialAndBatchEntry',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('serial_no', models.CharField(blank=True, default='', max_length=140)),
                ('batch_no', models.CharField(blank=True, default='', max_length=140)),
                ('qty', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('warehouse', models.CharField(blank=True, default='', max_length=140)),
                ('incoming_rate', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('outgoing_rate', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('stock_value_difference', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('is_outward', models.SmallIntegerField(default=0)),
                ('stock_queue', models.TextField(blank=True, default='')),
                ('delivered_qty', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('reference_for_reservation', models.CharField(blank=True, default='', max_length=140)),
                ('posting_datetime', models.DateTimeField(blank=True, null=True)),
                ('voucher_type', models.CharField(blank=True, default='', max_length=140)),
                ('voucher_no', models.CharField(blank=True, default='', max_length=140)),
                ('voucher_detail_no', models.CharField(blank=True, default='', max_length=140)),
                ('type_of_transaction', models.CharField(blank=True, default='', max_length=140)),
                ('is_cancelled', models.SmallIntegerField(default=0)),
                ('item_code', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Serial and Batch Entry',
                'db_table': 'tabSerial and Batch Entry',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='WorkstationOperatingComponentAccount',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('company', models.CharField(blank=True, default='', max_length=140)),
                ('expense_account', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Workstation Operating Component Account',
                'db_table': 'tabWorkstation Operating Component Account',
                'ordering': ['-creation'],
            },
        ),
    ]
