# Generated by Django 5.0.14 on 2026-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0017_emailaccount_emaildomain_imapfolder_replytoaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('subject', models.TextField(blank=True, default='')),
                ('communication_medium', models.CharField(blank=True, default='', max_length=140)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('recipients', models.TextField(blank=True, default='')),
                ('cc', models.TextField(blank=True, default='')),
                ('bcc', models.TextField(blank=True, default='')),
                ('phone_no', models.CharField(blank=True, default='', max_length=140)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=140)),
                ('content', models.TextField(blank=True, default='')),
                ('text_content', models.TextField(blank=True, default='')),
                ('communication_type', models.CharField(blank=True, default='Communication', max_length=140)),
                ('status', models.CharField(blank=True, default='', max_length=140)),
                ('sent_or_received', models.CharField(blank=True, default='', max_length=140)),
                ('communication_date', models.DateTimeField(blank=True, null=True)),
                ('read_receipt', models.SmallIntegerField(default=0)),
                ('sender_full_name', models.CharField(blank=True, default='', max_length=140)),
                ('read_by_recipient', models.SmallIntegerField(default=0)),
                ('read_by_recipient_on', models.DateTimeField(blank=True, null=True)),
                ('reference_doctype', models.CharField(blank=True, default='', max_length=140)),
                ('reference_name', models.CharField(blank=True, default='', max_length=140)),
                ('reference_owner', models.CharField(blank=True, default='', max_length=140)),
                ('email_account', models.CharField(blank=True, default='', max_length=140)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=140)),
                ('user', models.CharField(blank=True, default='', max_length=140)),
                ('unread_notification_sent', models.SmallIntegerField(default=0)),
                ('seen', models.SmallIntegerField(default=0)),
                ('_user_tags', models.CharField(blank=True, default='', max_length=140)),
                ('message_id', models.TextField(blank=True, default='')),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('email_status', models.CharField(blank=True, default='', max_length=140)),
                ('has_attachment', models.SmallIntegerField(default=0)),
                ('email_template', models.CharField(blank=True, default='', max_length=140)),
                ('imap_folder', models.CharField(blank=True, default='', max_length=140)),
                ('send_after', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Communication',
                'db_table': 'tabCommunication',
                'ordering': ['-creation'],
            },
        ),
    ]
