# Generated by Django 5.0.14 on 2026-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0022_dependenttask_tasktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDocperm',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('role', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('if_owner', models.SmallIntegerField(default=0)),
                ('permlevel', models.IntegerField(blank=True, null=True)),
                ('read', models.SmallIntegerField(default=1)),
                ('write', models.SmallIntegerField(default=0)),
                ('create', models.SmallIntegerField(default=0)),
                ('delete', models.SmallIntegerField(default=0)),
                ('submit', models.SmallIntegerField(default=0)),
                ('cancel', models.SmallIntegerField(default=0)),
                ('amend', models.SmallIntegerField(default=0)),
                ('mask', models.SmallIntegerField(default=0)),
                ('report', models.SmallIntegerField(default=0)),
                ('export', models.SmallIntegerField(default=1)),
                ('import_field', models.SmallIntegerField(default=0)),
                ('share', models.SmallIntegerField(default=0)),
                ('print_field', models.SmallIntegerField(default=0)),
                ('email', models.SmallIntegerField(default=0)),
                ('parent', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('select', models.SmallIntegerField(default=0)),
                ('is_app_disabled', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Custom DocPerm',
                'db_table': 'tabCustom DocPerm',
                'ordering': ['creation'],
            },
        ),
    ]
