# Generated by Django 5.0.14 on 2026-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0024_contact_is_billing_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('data_import', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('docname', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('exception', models.TextField(blank=True, default='', null=True)),
                ('row_indexes', models.TextField(blank=True, default='', null=True)),
                ('success', models.SmallIntegerField(default=0)),
                ('import_action', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('log_index', models.IntegerField(blank=True, null=True)),
                ('messages', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Data Import Log',
                'db_table': 'tabData Import Log',
                'ordering': ['-creation'],
            },
        ),
    ]
