# Generated by Django 5.0.14 on 2026-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0025_data_import_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPesaTransaction',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=140, null=True)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('bill_ref_number', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('middle_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('checkout_request_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('result_code', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('result_desc', models.TextField(blank=True, default='', null=True)),
                ('company', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('payment_request', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('payment_entry', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('sales_invoice', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('raw_payload', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'db_table': 'tabM-Pesa Transaction',
                'ordering': ['-creation'],
            },
        ),
    ]
