# Generated by Django 5.0.14 on 2026-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0027_standard_hidden_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtimsSettings',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('branch_id', models.CharField(blank=True, default='00', max_length=2, null=True)),
                ('provider', models.CharField(blank=True, default='OSCU KRA', max_length=140, null=True)),
                ('environment', models.CharField(blank=True, default='Sandbox', max_length=140, null=True)),
                ('is_active', models.SmallIntegerField(default=0)),
                ('server_url', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('tin', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('device_serial_number', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('communication_key', models.TextField(blank=True, default='', null=True)),
                ('scu_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('mrc_no', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('initialized_on', models.DateTimeField(blank=True, null=True)),
                ('payment_type_code', models.CharField(blank=True, default='01', max_length=140, null=True)),
                ('sales_status_code', models.CharField(blank=True, default='02', max_length=140, null=True)),
                ('purchase_type_code', models.CharField(blank=True, default='N', max_length=140, null=True)),
                ('purchase_receipt_type_code', models.CharField(blank=True, default='P', max_length=140, null=True)),
                ('purchase_status_code', models.CharField(blank=True, default='02', max_length=140, null=True)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'eTIMS Settings',
                'db_table': 'tabeTIMS Settings',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='EtimsSubmission',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('reference_doctype', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('reference_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('document_type', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('settings', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=140, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('result_message', models.TextField(blank=True, default='', null=True)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('total_receipt_number', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('internal_data', models.TextField(blank=True, default='', null=True)),
                ('receipt_signature', models.TextField(blank=True, default='', null=True)),
                ('scu_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('scu_datetime', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('qr_url', models.TextField(blank=True, default='', null=True)),
                ('request_body', models.TextField(blank=True, default='', null=True)),
                ('response_body', models.TextField(blank=True, default='', null=True)),
                ('last_attempt_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'eTIMS Submission',
                'db_table': 'tabeTIMS Submission',
                'ordering': ['-creation'],
            },
        ),
    ]
