# Generated by Django 5.0.14 on 2026-10-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0028_etims'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('sent_on', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('no_of_requested_sms', models.IntegerField(blank=True, null=True)),
                ('requested_numbers', models.TextField(blank=True, default='', null=True)),
                ('no_of_sent_sms', models.IntegerField(blank=True, null=True)),
                ('sent_to', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'db_table': 'tabSMS Log',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='SmsParameter',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('parameter', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('header', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SMS Parameter',
                'db_table': 'tabSMS Parameter',
                'ordering': ['-creation'],
            },
        ),
    ]
