# Generated by Django 5.0.14 on 2026-10-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0029_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityLostReason',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Opportunity Lost Reason',
                'db_table': 'tabOpportunity Lost Reason',
                'ordering': ['-creation'],
            },
        ),
    ]
