# Generated by Django 5.0.14 on 2026-10-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0030_unify_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('show_as_cc', models.TextField(blank=True, default='', null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, default='Not Sent', max_length=140, null=True)),
                ('error', models.TextField(blank=True, default='', null=True)),
                ('message_id', models.TextField(blank=True, default='', null=True)),
                ('reference_doctype', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('reference_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('communication', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('send_after', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('add_unsubscribe_link', models.SmallIntegerField(default=1)),
                ('unsubscribe_method', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('expose_recipients', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('attachments', models.TextField(blank=True, default='', null=True)),
                ('retry', models.IntegerField(blank=True, null=True)),
                ('email_account', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('unsubscribe_params', models.TextField(blank=True, default='', null=True)),
                ('raw_html', models.SmallIntegerField(default=0)),
                ('redact_message_after_send', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Email Queue',
                'db_table': 'tabEmail Queue',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueueRecipient',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('recipient', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('status', models.CharField(blank=True, default='Not Sent', max_length=140, null=True)),
                ('error', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Email Queue Recipient',
                'db_table': 'tabEmail Queue Recipient',
                'ordering': ['-creation'],
            },
        ),
    ]
