# Generated by Django 5.0.14 on 2026-10-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0032_integrations_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Gender',
                'db_table': 'tabGender',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('salutation', models.CharField(blank=True, default='', max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Salutation',
                'db_table': 'tabSalutation',
                'ordering': ['-creation'],
            },
        ),
    ]
