# Generated by Django 5.0.14 on 2026-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0033_gender_salutation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenanceTeam',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('maintenance_team_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('maintenance_manager', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('maintenance_manager_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Asset Maintenance Team',
                'db_table': 'tabAsset Maintenance Team',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDistribution',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('distribution_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('fiscal_year', models.CharField(blank=True, default='', max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Monthly Distribution',
                'db_table': 'tabMonthly Distribution',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDistributionPercentage',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, default='', max_length=140)),
                ('parentfield', models.CharField(blank=True, default='', max_length=140)),
                ('parenttype', models.CharField(blank=True, default='', max_length=140)),
                ('month', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('percentage_allocation', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
            ],
            options={
                'verbose_name': 'Monthly Distribution Percentage',
                'db_table': 'tabMonthly Distribution Percentage',
                'ordering': ['-creation'],
            },
        ),
    ]
