# Generated by Django 5.0.14 on 2026-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0041_custom_sidebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('enable', models.SmallIntegerField(default=1)),
                ('user', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('calendar_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('refresh_token', models.TextField(blank=True, default='', null=True)),
                ('authorization_code', models.TextField(blank=True, default='', null=True)),
                ('next_sync_token', models.TextField(blank=True, default='', null=True)),
                ('google_calendar_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('pull_from_google_calendar', models.SmallIntegerField(default=1)),
                ('sync_as_public', models.SmallIntegerField(default=0)),
                ('push_to_google_calendar', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Google Calendar',
                'db_table': 'tabGoogle Calendar',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='GoogleContacts',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('enable', models.SmallIntegerField(default=0)),
                ('authorization_code', models.TextField(blank=True, default='', null=True)),
                ('refresh_token', models.TextField(blank=True, default='', null=True)),
                ('last_sync_on', models.DateTimeField(blank=True, null=True)),
                ('email_id', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('next_sync_token', models.TextField(blank=True, default='', null=True)),
                ('pull_from_google_contacts', models.SmallIntegerField(default=0)),
                ('push_to_google_contacts', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Google Contacts',
                'db_table': 'tabGoogle Contacts',
                'ordering': ['-creation'],
            },
        ),
        migrations.CreateModel(
            name='WebhookRequestLog',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, default='', null=True)),
                ('headers', models.TextField(blank=True, default='', null=True)),
                ('response', models.TextField(blank=True, default='', null=True)),
                ('data', models.TextField(blank=True, default='', null=True)),
                ('user', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('reference_document', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('error', models.TextField(blank=True, default='', null=True)),
                ('webhook', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('reference_doctype', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('attempt', models.IntegerField(blank=True, null=True)),
                ('next_retry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Request Log',
                'db_table': 'tabWebhook Request Log',
                'ordering': ['-creation'],
            },
        ),
    ]
