# Generated by Django 5.0.14 on 2026-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0043_remaining_frappe_doctypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docshare',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('_user_tags', models.TextField(blank=True, null=True)),
                ('_comments', models.TextField(blank=True, null=True)),
                ('_assign', models.TextField(blank=True, null=True)),
                ('_liked_by', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('share_doctype', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('share_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('read', models.SmallIntegerField(default=0)),
                ('write', models.SmallIntegerField(default=0)),
                ('share', models.SmallIntegerField(default=0)),
                ('everyone', models.SmallIntegerField(default=0)),
                ('notify_by_email', models.SmallIntegerField(default=1)),
                ('submit', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'DocShare',
                'db_table': 'tabDocShare',
                'ordering': ['-creation'],
            },
        ),
    ]
