# Generated by Django 5.0.14 on 2026-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0045_automation_doctypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcapitalization',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmaintenancelog',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrepair',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financebook',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_seen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
