# Generated by Django 5.0.14 on 2026-10-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0048_reference_kenya_doctypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingstepmap',
            name='is_optional',
            field=models.SmallIntegerField(default=0),
        ),
    ]
