import { get, post, type ModuleEndpoints } from '@/core/api/endpointRegistry'

const method = (name: string) => `/api/erpnext/method/${name}/`

export const hrmsEndpoints: ModuleEndpoints = {
  doctypes: {
    Employee: 'erpnext/resource/Employee',
    'PWA Notification': 'erpnext/resource/PWA Notification',
    'Attendance Request': 'erpnext/resource/Attendance Request',
    'Employee Checkin': 'erpnext/resource/Employee Checkin',
    'Shift Assignment': 'erpnext/resource/Shift Assignment',
    'Shift Request': 'erpnext/resource/Shift Request',
    'Leave Application': 'erpnext/resource/Leave Application',
    'Expense Claim': 'erpnext/resource/Expense Claim',
    'Employee Advance': 'erpnext/resource/Employee Advance',
    File: 'erpnext/resource/File',
    'Payroll Period': 'erpnext/resource/Payroll Period',
    'Salary Slip': 'erpnext/resource/Salary Slip',
  },
  methods: {
    'hrms.api.get_current_user_info': get(method('hrms.api.get_current_user_info')),
    'hrms.api.get_current_employee_info': get(method('hrms.api.get_current_employee_info')),
    'hrms.api.get_all_employees': get(method('hrms.api.get_all_employees')),
    'hrms.api.get_hr_settings': get(method('hrms.api.get_hr_settings')),
    'hrms.api.get_unread_notifications_count': get(method('hrms.api.get_unread_notifications_count')),
    'hrms.api.mark_all_notifications_as_read': post(method('hrms.api.mark_all_notifications_as_read')),
    'hrms.api.are_push_notifications_enabled': get(method('hrms.api.are_push_notifications_enabled')),
    'hrms.api.get_attendance_calendar_events': get(method('hrms.api.get_attendance_calendar_events')),
    'hrms.api.get_attendance_for_calendar': get(method('hrms.api.get_attendance_for_calendar')),
    'hrms.api.get_holidays_for_calendar': get(method('hrms.api.get_holidays_for_calendar')),
    'hrms.api.get_attendance_requests': get(method('hrms.api.get_attendance_requests')),
    'hrms.api.get_shift_requests': get(method('hrms.api.get_shift_requests')),
    'hrms.api.get_shift_request_approvers': get(method('hrms.api.get_shift_request_approvers')),
    'hrms.api.get_shifts': get(method('hrms.api.get_shifts')),
    'hrms.api.get_leave_applications': get(method('hrms.api.get_leave_applications')),
    'hrms.api.get_leave_balance_map': get(method('hrms.api.get_leave_balance_map')),
    'hrms.api.get_holidays_for_employee': get(method('hrms.api.get_holidays_for_employee')),
    'hrms.api.get_leave_approval_details': get(method('hrms.api.get_leave_approval_details')),
    'hrms.api.get_leave_types': get(method('hrms.api.get_leave_types')),
    'hrms.api.get_expense_claims': get(method('hrms.api.get_expense_claims')),
    'hrms.api.get_expense_claim_summary': get(method('hrms.api.get_expense_claim_summary')),
    'hrms.api.get_expense_type_description': get(method('hrms.api.get_expense_type_description')),
    'hrms.api.get_expense_claim_types': get(method('hrms.api.get_expense_claim_types')),
    'hrms.api.get_expense_approval_details': get(method('hrms.api.get_expense_approval_details')),
    'hrms.api.get_employee_advance_balance': get(method('hrms.api.get_employee_advance_balance')),
    'hrms.api.get_company_currencies': get(method('hrms.api.get_company_currencies')),
    'hrms.api.get_currency_symbols': get(method('hrms.api.get_currency_symbols')),
    'hrms.api.get_company_cost_center_and_expense_account': get(
      method('hrms.api.get_company_cost_center_and_expense_account'),
    ),
    'hrms.api.get_doctype_fields': get(method('hrms.api.get_doctype_fields')),
    'hrms.api._download_pdf': post(method('hrms.api._download_pdf')),
    'hrms.api.get_doctype_states': get(method('hrms.api.get_doctype_states')),
    'hrms.api.get_attachments': get(method('hrms.api.get_attachments')),
    'hrms.api.upload_base64_file': post(method('hrms.api.upload_base64_file')),
    'hrms.api.delete_attachment': post(method('hrms.api.delete_attachment')),
    'hrms.api.get_workflow': get(method('hrms.api.get_workflow')),
    'hrms.api.get_current_employee': get(method('hrms.api.get_current_employee')),
    'hrms.api.roster.get_default_company': get(method('hrms.api.roster.get_default_company')),
    'hrms.api.roster.get_events': get(method('hrms.api.roster.get_events')),
    'hrms.api.roster.get_schedule_from_assignment': get(method('hrms.api.roster.get_schedule_from_assignment')),
    'hrms.api.roster.create_shift_schedule_assignment': post(
      method('hrms.api.roster.create_shift_schedule_assignment'),
    ),
    'hrms.api.roster.delete_shift_schedule_assignment': post(
      method('hrms.api.roster.delete_shift_schedule_assignment'),
    ),
    'hrms.api.roster.swap_shift': post(method('hrms.api.roster.swap_shift')),
    'hrms.api.roster.break_shift': post(method('hrms.api.roster.break_shift')),
    'hrms.api.roster.insert_shift': post(method('hrms.api.roster.insert_shift')),
  },
}
