from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class PurchaseInvoiceItemGenerated(FrappeChildModel):
    doctype = 'Purchase Invoice Item'
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    received_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rejected_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    uom = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_factor = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    pricing_rules = models.TextField(blank=True, null=True, default='')
    is_free_item = models.SmallIntegerField(default=0)
    net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_per_unit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    quality_inspection = models.CharField(max_length=140, blank=True, null=True, default='')
    batch_no = models.CharField(max_length=140, blank=True, null=True, default='')
    serial_no = models.TextField(blank=True, null=True, default='')
    rejected_serial_no = models.TextField(blank=True, null=True, default='')
    expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    item_tax_template = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default=':Company')
    deferred_expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    service_stop_date = models.DateField(null=True, blank=True)
    enable_deferred_expense = models.SmallIntegerField(default=0)
    service_start_date = models.DateField(null=True, blank=True)
    service_end_date = models.DateField(null=True, blank=True)
    allow_zero_valuation_rate = models.SmallIntegerField(default=0)
    brand = models.CharField(max_length=140, blank=True, null=True, default='')
    item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    item_tax_rate = models.TextField(blank=True, null=True, default='')
    item_tax_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    purchase_order = models.CharField(max_length=140, blank=True, null=True, default='')
    include_exploded_items = models.SmallIntegerField(default=0)
    is_fixed_asset = models.SmallIntegerField(default=0)
    asset_location = models.CharField(max_length=140, blank=True, null=True, default='')
    po_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_receipt = models.CharField(max_length=140, blank=True, null=True, default='')
    page_break = models.SmallIntegerField(default=0)
    pr_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    valuation_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rm_supp_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    landed_cost_voucher_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    manufacturer = models.CharField(max_length=140, blank=True, null=True, default='')
    manufacturer_part_no = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_category = models.CharField(max_length=140, blank=True, null=True, default='')
    from_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_invoice_item = models.CharField(max_length=140, blank=True, null=True, default='')
    stock_uom_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    sales_invoice_item = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_type = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_rate_or_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    product_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    apply_tds = models.SmallIntegerField(default=1)
    serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    wip_composite_asset = models.CharField(max_length=140, blank=True, null=True, default='')
    use_serial_batch_fields = models.SmallIntegerField(default=0)
    material_request = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request_item = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_incoming_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    distributed_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    tax_withholding_category = models.CharField(max_length=140, blank=True, null=True, default='')
    delivered_by_supplier = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
