from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class WorkOrderGenerated(FrappeModel):
    doctype = 'Work Order'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    production_item = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    bom_no = models.CharField(max_length=140, blank=True, null=True, default='')
    allow_alternative_item = models.SmallIntegerField(default=0)
    use_multi_level_bom = models.SmallIntegerField(default=1)
    skip_transfer = models.SmallIntegerField(default=0)
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    material_transferred_for_manufacturing = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    produced_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    sales_order = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    from_wip_warehouse = models.SmallIntegerField(default=0)
    wip_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    fg_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    scrap_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    planned_start_date = FrappeDateTimeField(null=True, blank=True)
    actual_start_date = FrappeDateTimeField(null=True, blank=True)
    planned_end_date = FrappeDateTimeField(null=True, blank=True)
    actual_end_date = FrappeDateTimeField(null=True, blank=True)
    expected_delivery_date = models.DateField(null=True, blank=True)
    transfer_material_against = models.CharField(max_length=140, blank=True, null=True, default='')
    planned_operating_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    actual_operating_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_operating_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_operating_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    description = models.TextField(blank=True, null=True, default='')
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request_item = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    production_plan = models.CharField(max_length=140, blank=True, null=True, default='')
    production_plan_item = models.CharField(max_length=140, blank=True, null=True, default='')
    product_bundle_item = models.CharField(max_length=140, blank=True, null=True, default='')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    update_consumed_material_cost_in_project = models.SmallIntegerField(default=1)
    source_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    lead_time = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    has_serial_no = models.SmallIntegerField(default=0)
    has_batch_no = models.SmallIntegerField(default=0)
    batch_size = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    corrective_operation_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    production_plan_sub_assembly_item = models.CharField(max_length=140, blank=True, null=True, default='')
    process_loss_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    track_semi_finished_goods = models.SmallIntegerField(default=0)
    reserve_stock = models.SmallIntegerField(default=0)
    disassembled_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    mps = models.CharField(max_length=140, blank=True, null=True, default='')
    additional_transferred_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    subcontracting_inward_order = models.CharField(max_length=140, blank=True, null=True, default='')
    subcontracting_inward_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    max_producible_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    _seen = models.TextField(null=True, blank=True)

    class Meta:
        abstract = True
