from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class PaymentEntryGenerated(FrappeModel):
    doctype = 'Payment Entry'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    payment_type = models.CharField(max_length=140, blank=True, null=True, default='')
    posting_date = models.DateField(null=True, blank=True)
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    mode_of_payment = models.CharField(max_length=140, blank=True, null=True, default='')
    party_type = models.CharField(max_length=140, blank=True, null=True, default='')
    party = models.CharField(max_length=140, blank=True, null=True, default='')
    party_name = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_email = models.CharField(max_length=140, blank=True, null=True, default='')
    paid_from = models.CharField(max_length=140, blank=True, null=True, default='')
    paid_from_account_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    paid_to = models.CharField(max_length=140, blank=True, null=True, default='')
    paid_to_account_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    paid_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    source_exchange_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_paid_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    received_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    target_exchange_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_received_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_allocated_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total_allocated_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    unallocated_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    difference_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    reference_no = models.CharField(max_length=140, blank=True, null=True, default='')
    reference_date = models.DateField(null=True, blank=True)
    clearance_date = models.DateField(null=True, blank=True)
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    remarks = models.TextField(blank=True, null=True, default='')
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    print_heading = models.CharField(max_length=140, blank=True, null=True, default='')
    bank = models.CharField(max_length=140, blank=True, null=True, default='')
    bank_account_no = models.CharField(max_length=140, blank=True, null=True, default='')
    payment_order = models.CharField(max_length=140, blank=True, null=True, default='')
    auto_repeat = models.CharField(max_length=140, blank=True, null=True, default='')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    title = models.CharField(max_length=140, blank=True, null=True, default='')
    bank_account = models.CharField(max_length=140, blank=True, null=True, default='')
    party_bank_account = models.CharField(max_length=140, blank=True, null=True, default='')
    payment_order_status = models.CharField(max_length=140, blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    custom_remarks = models.SmallIntegerField(default=0)
    tax_withholding_category = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_taxes_and_charges_template = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_taxes_and_charges_template = models.CharField(max_length=140, blank=True, null=True, default='')
    base_total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    paid_amount_after_tax = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_paid_amount_after_tax = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    received_amount_after_tax = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_received_amount_after_tax = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    paid_from_account_type = models.CharField(max_length=140, blank=True, null=True, default='')
    paid_to_account_type = models.CharField(max_length=140, blank=True, null=True, default='')
    book_advance_payments_in_separate_party_account = models.SmallIntegerField(default=0)
    base_in_words = models.TextField(blank=True, null=True, default='')
    in_words = models.TextField(blank=True, null=True, default='')
    reconcile_on_advance_payment_date = models.SmallIntegerField(default=0)
    is_opening = models.CharField(max_length=140, blank=True, null=True, default='No')
    apply_tds = models.SmallIntegerField(default=0)
    tax_withholding_group = models.CharField(max_length=140, blank=True, null=True, default='')
    ignore_tax_withholding_threshold = models.SmallIntegerField(default=0)
    override_tax_withholding_entries = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
