from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class JobCardGenerated(FrappeModel):
    doctype = 'Job Card'
    work_order = models.CharField(max_length=140, blank=True, null=True, default='')
    bom_no = models.CharField(max_length=140, blank=True, null=True, default='')
    workstation = models.CharField(max_length=140, blank=True, null=True, default='')
    operation = models.CharField(max_length=140, blank=True, null=True, default='')
    posting_date = models.DateField(null=True, blank=True)
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    for_quantity = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    wip_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    total_completed_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_time_in_mins = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    operation_id = models.CharField(max_length=140, blank=True, null=True, default='')
    transferred_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    requested_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    remarks = models.TextField(blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='Open')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='PO-JOB.#####')
    production_item = models.CharField(max_length=140, blank=True, null=True, default='')
    barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    sequence_id = models.IntegerField(null=True, blank=True)
    quality_inspection = models.CharField(max_length=140, blank=True, null=True, default='')
    hour_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    is_corrective_job_card = models.SmallIntegerField(default=0)
    for_job_card = models.CharField(max_length=140, blank=True, null=True, default='')
    for_operation = models.CharField(max_length=140, blank=True, null=True, default='')
    serial_no = models.TextField(blank=True, null=True, default='')
    batch_no = models.CharField(max_length=140, blank=True, null=True, default='')
    quality_inspection_template = models.CharField(max_length=140, blank=True, null=True, default='')
    workstation_type = models.CharField(max_length=140, blank=True, null=True, default='')
    expected_start_date = models.DateTimeField(null=True, blank=True)
    expected_end_date = models.DateTimeField(null=True, blank=True)
    serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    process_loss_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    time_required = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    actual_start_date = models.DateTimeField(null=True, blank=True)
    actual_end_date = models.DateTimeField(null=True, blank=True)
    finished_good = models.CharField(max_length=140, blank=True, null=True, default='')
    target_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    operation_row_id = models.IntegerField(null=True, blank=True)
    source_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    semi_fg_bom = models.CharField(max_length=140, blank=True, null=True, default='')
    batch_split = models.SmallIntegerField(default=0)
    weight_per_piece = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    is_subcontracted = models.SmallIntegerField(default=0)
    manufactured_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    skip_material_transfer = models.SmallIntegerField(default=0)
    backflush_from_wip_warehouse = models.SmallIntegerField(default=0)
    is_paused = models.SmallIntegerField(default=0)
    track_semi_finished_goods = models.SmallIntegerField(default=0)
    pending_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)

    class Meta:
        abstract = True
