from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class CompanyGenerated(FrappeTreeModel):
    doctype = 'Company'
    company_name = models.CharField(max_length=140, blank=True, null=True, default='')
    abbr = models.CharField(max_length=140, blank=True, null=True, default='')
    is_group = models.SmallIntegerField(default=0)
    default_finance_book = models.CharField(max_length=140, blank=True, null=True, default='')
    domain = models.CharField(max_length=140, blank=True, null=True, default='')
    parent_company = models.CharField(max_length=140, blank=True, null=True, default='')
    company_logo = models.TextField(blank=True, null=True, default='')
    company_description = models.TextField(blank=True, null=True, default='')
    sales_monthly_history = models.TextField(blank=True, null=True, default='')
    transactions_annual_history = models.TextField(blank=True, null=True, default='')
    monthly_sales_target = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_monthly_sales = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    default_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    default_letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    default_holiday_list = models.CharField(max_length=140, blank=True, null=True, default='')
    default_warehouse_for_sales_return = models.CharField(max_length=140, blank=True, null=True, default='')
    country = models.CharField(max_length=140, blank=True, null=True, default='')
    create_chart_of_accounts_based_on = models.CharField(max_length=140, blank=True, null=True, default='')
    chart_of_accounts = models.CharField(max_length=140, blank=True, null=True, default='')
    existing_company = models.CharField(max_length=140, blank=True, null=True, default='')
    tax_id = models.CharField(max_length=140, blank=True, null=True, default='')
    date_of_establishment = models.DateField(null=True, blank=True)
    default_bank_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_cash_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_receivable_account = models.CharField(max_length=140, blank=True, null=True, default='')
    round_off_account = models.CharField(max_length=140, blank=True, null=True, default='')
    round_off_cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    write_off_account = models.CharField(max_length=140, blank=True, null=True, default='')
    bank_charges_account = models.CharField(max_length=140, blank=True, null=True, default='')
    exchange_gain_loss_account = models.CharField(max_length=140, blank=True, null=True, default='')
    exchange_gain_account = models.CharField(max_length=140, blank=True, null=True, default='')
    exchange_loss_account = models.CharField(max_length=140, blank=True, null=True, default='')
    unrealized_exchange_gain_loss_account = models.CharField(max_length=140, blank=True, null=True, default='')
    allow_account_creation_against_child_company = models.SmallIntegerField(default=0)
    default_payable_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_income_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_deferred_revenue_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_deferred_expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    credit_limit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    payment_terms = models.CharField(max_length=140, blank=True, null=True, default='')
    enable_perpetual_inventory = models.SmallIntegerField(default=1)
    default_inventory_account = models.CharField(max_length=140, blank=True, null=True, default='')
    stock_adjustment_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_purchase_price_variance_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_manufacturing_variance_account = models.CharField(max_length=140, blank=True, null=True, default='')
    stock_received_but_not_billed = models.CharField(max_length=140, blank=True, null=True, default='')
    accumulated_depreciation_account = models.CharField(max_length=140, blank=True, null=True, default='')
    depreciation_expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    series_for_depreciation_entry = models.CharField(max_length=140, blank=True, null=True, default='')
    disposal_account = models.CharField(max_length=140, blank=True, null=True, default='')
    depreciation_cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    capital_work_in_progress_account = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_received_but_not_billed = models.CharField(max_length=140, blank=True, null=True, default='')
    exception_budget_approver_role = models.CharField(max_length=140, blank=True, null=True, default='')
    date_of_incorporation = models.DateField(null=True, blank=True)
    date_of_commencement = models.DateField(null=True, blank=True)
    phone_no = models.CharField(max_length=140, blank=True, null=True, default='')
    fax = models.CharField(max_length=140, blank=True, null=True, default='')
    email = models.CharField(max_length=140, blank=True, null=True, default='')
    website = models.CharField(max_length=140, blank=True, null=True, default='')
    registration_details = models.TextField(blank=True, null=True, default='')
    lft = models.IntegerField(null=True, blank=True)
    rgt = models.IntegerField(null=True, blank=True)
    old_parent = models.CharField(max_length=140, blank=True, null=True, default='')
    default_selling_terms = models.CharField(max_length=140, blank=True, null=True, default='')
    default_buying_terms = models.CharField(max_length=140, blank=True, null=True, default='')
    default_in_transit_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    default_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    sample_retention_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    unrealized_profit_loss_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_discount_account = models.CharField(max_length=140, blank=True, null=True, default='')
    enable_provisional_accounting_for_non_stock_items = models.SmallIntegerField(default=0)
    default_provisional_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_advance_received_account = models.CharField(max_length=140, blank=True, null=True, default='')
    default_advance_paid_account = models.CharField(max_length=140, blank=True, null=True, default='')
    book_advance_payments_in_separate_party_account = models.SmallIntegerField(default=0)
    auto_exchange_rate_revaluation = models.SmallIntegerField(default=0)
    auto_err_frequency = models.CharField(max_length=140, blank=True, null=True, default='')
    submit_err_jv = models.SmallIntegerField(default=0)
    reconcile_on_advance_payment_date = models.SmallIntegerField(default=0)
    default_operating_cost_account = models.CharField(max_length=140, blank=True, null=True, default='')
    round_off_for_opening = models.CharField(max_length=140, blank=True, null=True, default='')
    reconciliation_takes_effect_on = models.CharField(max_length=140, blank=True, null=True, default='Oldest Of Invoice Or Advance')
    reporting_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_expense_contra_account = models.CharField(max_length=140, blank=True, null=True, default='')
    service_expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    expenses_added_to_stock_account = models.CharField(max_length=140, blank=True, null=True, default='')
    expenses_added_to_stock_contra_account = models.CharField(max_length=140, blank=True, null=True, default='')
    enable_item_wise_inventory_account = models.SmallIntegerField(default=0)
    valuation_method = models.CharField(max_length=140, blank=True, null=True, default='FIFO')
    default_wip_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    default_fg_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    default_scrap_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    default_sales_contact = models.CharField(max_length=140, blank=True, null=True, default='')
    accounts_frozen_till_date = models.DateField(null=True, blank=True)
    role_allowed_for_frozen_entries = models.CharField(max_length=140, blank=True, null=True, default='')
    default_letter_head_report = models.CharField(max_length=140, blank=True, null=True, default='')
    disable_sdbnb_in_sr = models.SmallIntegerField(default=0)
    stock_delivered_but_not_billed = models.CharField(max_length=140, blank=True, null=True, default='')
    enable_stock_delivered_but_not_billed = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
