# Generated by Django 5.0.14 on 2026-09-27 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leasing', '0001_initial'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTGateway',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('vendor', models.CharField(choices=[('SKIDATA', 'SKIDATA'), ('Hikvision', 'Hikvision'), ('Dahua', 'Dahua'), ('Axis', 'Axis'), ('Custom', 'Custom')], max_length=100)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=50)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IoT Gateway',
                'db_table': 'tabIoTGateway',
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('ANPR Camera', 'ANPR Camera'), ('Boom Barrier', 'Boom Barrier'), ('CCTV Camera', 'CCTV Camera'), ('Access Reader', 'Access Reader'), ('Footfall Sensor', 'Footfall Sensor'), ('Environment Sensor', 'Environment Sensor')], max_length=100)),
                ('location_description', models.CharField(help_text='e.g. Basement 1 Entry Gate A', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='property.building')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='iot.iotgateway')),
            ],
            options={
                'verbose_name': 'IoT Device',
                'db_table': 'tabIoTDevice',
            },
        ),
        migrations.CreateModel(
            name='RegisteredVehicle',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('Tenant', 'Tenant'), ('VIP', 'VIP'), ('Staff', 'Staff'), ('Contractor', 'Contractor'), ('Blacklisted', 'Blacklisted')], default='Tenant', max_length=50)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='leasing.tenant')),
            ],
            options={
                'verbose_name': 'Registered Vehicle',
                'db_table': 'tabRegisteredVehicle',
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(db_index=True, max_length=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('calculated_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active (In Mall)'), ('Paid', 'Paid (Waiting to Exit)'), ('Completed', 'Completed (Exited)'), ('Violation', 'Violation (Overstay/Blacklisted)')], default='Active', max_length=50)),
                ('entry_device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='iot.iotdevice')),
                ('exit_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exits', to='iot.iotdevice')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, help_text='Auto-linked if plate is registered', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.registeredvehicle')),
            ],
            options={
                'verbose_name': 'Parking Session',
                'db_table': 'tabParkingSession',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Blacklisted Vehicle', 'Blacklisted Vehicle'), ('Perimeter Intrusion', 'Perimeter Intrusion'), ('Crowd Gathering', 'Crowd Gathering'), ('Fire/Smoke Detected', 'Fire/Smoke Detected'), ('Hardware Tamper', 'Hardware Tamper')], max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=50)),
                ('event_time', models.DateTimeField()),
                ('snapshot_url', models.CharField(blank=True, help_text='URL to NVR snapshot of the event', max_length=255)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='iot.iotdevice')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'db_table': 'tabSecurityEvent',
            },
        ),
    ]
