import {
  ArrowBigUp,
  ArrowDown,
  ArrowDownAZ,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpZA,
  Braces,
  Calendar,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleQuestionMark,
  CircleX,
  Clock,
  Command,
  Copy,
  CornerDownLeft,
  Delete,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileAudio2,
  FileImage,
  FileSpreadsheet,
  FileText,
  FileType,
  FileVideo2,
  Folder,
  IdCard,
  Info,
  LandPlot,
  LayoutGrid,
  Link,
  ListFilterPlus,
  Lock,
  MapPin,
  Maximize,
  Minus,
  Monitor,
  Network,
  Option,
  OctagonX,
  PanelRightClose,
  Paperclip,
  Pencil,
  Play,
  Plus,
  Redo2,
  RefreshCcw,
  RefreshCw,
  Search,
  Settings,
  Settings2,
  Shield,
  SquareArrowOutUpRight,
  SquareAsterisk,
  SquarePen,
  Star,
  Target,
  Trash2,
  TriangleAlert,
  Undo2,
  Unlock,
  User,
  Users,
  X,
  Zap,
  type LucideIcon as LucideComponent,
} from 'lucide-react'
import { DynamicIcon, type IconName } from 'lucide-react/dynamic'
import { cn } from '../utils/cn'

const staticIcons: Readonly<Record<string, LucideComponent>> = {
  'arrow-big-up': ArrowBigUp,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  command: Command,
  'corner-down-left': CornerDownLeft,
  delete: Delete,
  option: Option,
  'arrow-down-a-z': ArrowDownAZ,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-z-a': ArrowUpZA,
  braces: Braces,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dollar-sign': CircleDollarSign,
  'circle-question-mark': CircleQuestionMark,
  'circle-x': CircleX,
  clock: Clock,
  copy: Copy,
  ellipsis: Ellipsis,
  'more-horizontal': Ellipsis,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-audio-2': FileAudio2,
  'file-image': FileImage,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'file-type': FileType,
  'file-video-2': FileVideo2,
  folder: Folder,
  'id-card': IdCard,
  info: Info,
  'land-plot': LandPlot,
  'layout-grid': LayoutGrid,
  link: Link,
  'list-filter-plus': ListFilterPlus,
  lock: Lock,
  'map-pin': MapPin,
  maximize: Maximize,
  minus: Minus,
  monitor: Monitor,
  network: Network,
  'octagon-x': OctagonX,
  'x-octagon': OctagonX,
  'panel-right-close': PanelRightClose,
  paperclip: Paperclip,
  pencil: Pencil,
  edit: SquarePen,
  play: Play,
  plus: Plus,
  'redo-2': Redo2,
  'refresh-ccw': RefreshCcw,
  'refresh-cw': RefreshCw,
  search: Search,
  settings: Settings,
  'settings-2': Settings2,
  shield: Shield,
  'square-arrow-out-up-right': SquareArrowOutUpRight,
  'square-asterisk': SquareAsterisk,
  'square-pen': SquarePen,
  star: Star,
  target: Target,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  'undo-2': Undo2,
  unlock: Unlock,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
}

export interface LucideIconProps {
  name: string
  className?: string
  strokeWidth?: number
}

export function LucideIcon({ name, className, strokeWidth }: LucideIconProps) {
  const normalized = name.replace(/^lucide-/, '')
  const Icon = staticIcons[normalized]
  if (Icon) return <Icon aria-hidden="true" className={cn('shrink-0', className)} strokeWidth={strokeWidth} />
  return (
    <DynamicIcon
      name={normalized as IconName}
      aria-hidden="true"
      className={cn('shrink-0', className)}
      strokeWidth={strokeWidth}
    />
  )
}
