# Generated by Django 5.0.14 on 2026-09-27 08:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=140)),
                ('middle_name', models.CharField(blank=True, max_length=140)),
                ('last_name', models.CharField(blank=True, max_length=140)),
                ('full_name', models.CharField(blank=True, editable=False, max_length=270)),
                ('email_id', models.EmailField(blank=True, editable=False, max_length=254)),
                ('status', models.CharField(choices=[('Passive', 'Passive'), ('Open', 'Open'), ('Replied', 'Replied')], default='Passive', max_length=10)),
                ('salutation', models.CharField(blank=True, max_length=140)),
                ('gender', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, editable=False, max_length=30)),
                ('mobile_no', models.CharField(blank=True, editable=False, max_length=30)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=140)),
                ('designation', models.CharField(blank=True, max_length=140)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=140)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('email_id', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_ids', to='core.contact')),
            ],
            options={
                'verbose_name': 'Contact Email',
                'db_table': 'contact_email',
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=30)),
                ('is_primary_phone', models.BooleanField(default=False)),
                ('is_primary_mobile_no', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_nos', to='core.contact')),
            ],
            options={
                'verbose_name': 'Contact Phone',
                'db_table': 'contact_phone',
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='DocShare',
            fields=[
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('share_doctype', models.CharField(max_length=140)),
                ('share_name', models.CharField(max_length=140)),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=False)),
                ('submit', models.BooleanField(default=False)),
                ('everyone', models.BooleanField(default=False)),
                ('notify_by_email', models.BooleanField(default=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Share',
                'db_table': 'docshare',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=140)),
                ('reference_name', models.CharField(blank=True, max_length=140)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDos',
                'db_table': 'todo',
            },
        ),
    ]
