# Generated by Django 5.0.14 on 2026-09-27 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_doctype', models.CharField(max_length=140)),
                ('reference_name', models.CharField(max_length=140)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liked Document',
                'db_table': 'liked_document',
                'unique_together': {('user', 'reference_doctype', 'reference_name')},
            },
        ),
        migrations.CreateModel(
            name='SeenDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_doctype', models.CharField(max_length=140)),
                ('reference_name', models.CharField(max_length=140)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seen Document',
                'db_table': 'seen_document',
                'unique_together': {('user', 'reference_doctype', 'reference_name')},
            },
        ),
    ]
