# Generated by Django 5.0.14 on 2026-09-27 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_likeddocument_seendocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('is_private', models.BooleanField(default=True)),
                ('folder', models.CharField(blank=True, default='Home', max_length=255)),
                ('attached_to_doctype', models.CharField(blank=True, max_length=140)),
                ('attached_to_name', models.CharField(blank=True, max_length=140)),
                ('attached_to_field', models.CharField(blank=True, max_length=140)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'db_table': 'core_file_attachment',
            },
        ),
    ]
