# Generated by Django 5.0.14 on 2026-09-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # The RunSQL UPDATE and the later AddField/AlterField both touch
    # `contact` -- Postgres refuses an ALTER TABLE on a table with pending
    # (not-yet-committed) trigger events from an earlier UPDATE in the same
    # transaction, so each operation here needs its own transaction.
    atomic = False

    dependencies = [
        ('core', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('address_title', models.CharField(blank=True, max_length=140)),
                ('address_type', models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Office', 'Office'), ('Personal', 'Personal'), ('Plant', 'Plant'), ('Postal', 'Postal'), ('Shop', 'Shop'), ('Subsidiary', 'Subsidiary'), ('Warehouse', 'Warehouse'), ('Current', 'Current'), ('Permanent', 'Permanent'), ('Other', 'Other')], default='Billing', max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=240)),
                ('address_line2', models.CharField(blank=True, max_length=240)),
                ('city', models.CharField(blank=True, max_length=140)),
                ('state', models.CharField(blank=True, max_length=140)),
                ('country', models.CharField(blank=True, max_length=140)),
                ('pincode', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Gender',
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Salutation',
                'db_table': 'salutation',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        # contact.gender/salutation were plain CharFields (blank='', not
        # null) before this -- '' isn't a valid FK value once they become
        # Links, so clear it to NULL first.
        migrations.RunSQL(
            "ALTER TABLE contact ALTER COLUMN gender DROP NOT NULL; "
            "ALTER TABLE contact ALTER COLUMN salutation DROP NOT NULL; "
            "UPDATE contact SET gender = NULL WHERE gender = ''; "
            "UPDATE contact SET salutation = NULL WHERE salutation = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.gender'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salutation'),
        ),
    ]
