# Generated by Django 5.0.14 on 2026-09-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_language_user_time_zone_user_user_image'),
        ('crm', '0021_seed_address_quick_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('currency_precision', models.CharField(blank=True, choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2)),
                ('float_precision', models.CharField(blank=True, choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2)),
                ('number_format', models.CharField(choices=[('#,###.##', '#,###.##'), ('#.###,##', '#.###,##'), ('# ###.##', '# ###.##'), ('#,##,###.##', '#,##,###.##'), ('#.##,###', '#.##,###'), ('#,###.###', '#,###.###'), ('#.###', '#.###'), ('#,###', '#,###')], default='#,###.##', max_length=20)),
                ('date_format', models.CharField(choices=[('yyyy-mm-dd', 'yyyy-mm-dd'), ('dd-mm-yyyy', 'dd-mm-yyyy'), ('dd/mm/yyyy', 'dd/mm/yyyy'), ('dd.mm.yyyy', 'dd.mm.yyyy'), ('mm/dd/yyyy', 'mm/dd/yyyy'), ('mm-dd-yyyy', 'mm-dd-yyyy'), ('month d, yyyy', 'month d, yyyy'), ('day, month d, yyyy', 'day, month d, yyyy')], default='yyyy-mm-dd', max_length=20)),
                ('time_format', models.CharField(choices=[('HH:mm:ss', 'HH:mm:ss'), ('HH:mm', 'HH:mm'), ('hh:mm:ss a', 'hh:mm:ss a'), ('hh:mm a', 'hh:mm a')], default='HH:mm:ss', max_length=20)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.currency')),
            ],
            options={
                'verbose_name': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
