# Generated by Django 5.0.14 on 2026-09-27 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=140)),
                ('due_date_based_on', models.CharField(blank=True, max_length=140)),
                ('priority', models.IntegerField(default=0)),
                ('disabled', models.BooleanField(default=False)),
                ('description', models.TextField(default='Automatic Assignment')),
                ('rule', models.CharField(choices=[('Round Robin', 'Round Robin'), ('Load Balancing', 'Load Balancing'), ('Based on Field', 'Based on Field'), ('Weighted Distribution', 'Weighted Distribution')], max_length=25)),
                ('assign_condition', models.TextField(blank=True)),
                ('unassign_condition', models.TextField(blank=True)),
                ('close_condition', models.TextField(blank=True)),
                ('assign_condition_json', models.TextField(blank=True)),
                ('unassign_condition_json', models.TextField(blank=True)),
                ('field', models.CharField(blank=True, max_length=140)),
                ('current_index', models.IntegerField(default=0)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment Rule',
                'db_table': 'assignment_rule',
                'ordering': ['-priority', '-creation'],
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='assignment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.assignmentrule'),
        ),
        migrations.CreateModel(
            name='AssignmentRuleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('parent_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rows', to='core.assignmentrule')),
            ],
            options={
                'verbose_name': 'Assignment Rule Day',
                'db_table': 'assignment_rule_day',
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRuleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_field', models.CharField(choices=[('users', 'users'), ('weighted_users', 'weighted_users')], default='users', max_length=20)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('weight', models.IntegerField(default=1)),
                ('parent_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rows', to='core.assignmentrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment Rule User',
                'db_table': 'assignment_rule_user',
                'ordering': ['idx'],
            },
        ),
    ]
