# Generated by Django 5.0.14 on 2026-09-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_automation_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLinkAccess',
            fields=[
                ('doctype_label', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guest Link Access',
                'db_table': 'guest_link_access',
            },
        ),
        migrations.CreateModel(
            name='WebForm',
            fields=[
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255, unique=True)),
                ('doc_type', models.CharField(choices=[('CRM Lead', 'CRM Lead'), ('CRM Deal', 'CRM Deal')], max_length=140)),
                ('crm_published', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('button_label', models.CharField(blank=True, default='Submit', max_length=140)),
                ('introduction_text', models.TextField(blank=True)),
                ('success_message', models.CharField(blank=True, max_length=255)),
                ('success_url', models.CharField(blank=True, max_length=255)),
                ('allowed_embedding_domains', models.TextField(blank=True)),
                ('login_required', models.BooleanField(default=False)),
                ('allow_multiple', models.BooleanField(default=True)),
                ('is_standard', models.BooleanField(default=False)),
                ('module', models.CharField(default='FCRM', max_length=140)),
                ('crm_hidden_defaults', models.TextField(blank=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web Form',
                'db_table': 'web_form',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='WebFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('fieldname', models.CharField(max_length=140)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('fieldtype', models.CharField(choices=[('Data', 'Data'), ('Small Text', 'Small Text'), ('Text', 'Text'), ('Long Text', 'Long Text'), ('Text Editor', 'Text Editor'), ('HTML Editor', 'HTML Editor'), ('Markdown Editor', 'Markdown Editor'), ('Select', 'Select'), ('Link', 'Link'), ('Int', 'Int'), ('Float', 'Float'), ('Currency', 'Currency'), ('Percent', 'Percent'), ('Check', 'Check'), ('Date', 'Date'), ('Datetime', 'Datetime'), ('Time', 'Time'), ('Phone', 'Phone'), ('Color', 'Color'), ('Section Break', 'Section Break'), ('Column Break', 'Column Break')], max_length=20)),
                ('options', models.TextField(blank=True)),
                ('reqd', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('depends_on', models.CharField(blank=True, max_length=255)),
                ('mandatory_depends_on', models.CharField(blank=True, max_length=255)),
                ('read_only_depends_on', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rows', to='core.webform')),
            ],
            options={
                'verbose_name': 'Web Form Field',
                'db_table': 'web_form_field',
                'ordering': ['idx'],
            },
        ),
    ]
