# Generated by Django 5.0.14 on 2026-10-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_email_account_template_user_email'),
        ('crm', '0030_unify_currency'),
        ('erpnext', '0022_dependenttask_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.currency'),
        ),
    ]
