# Generated by Django 5.0.14 on 2026-10-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_unify_assignment_rule'),
        ('crm', '0036_gender_salutation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Salutation',
        ),
    ]
