# Generated by Django 5.0.14 on 2026-10-05 20:36

from django.db import migrations, models


def backfill_frappe_user(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        user.name = user.email
        user.enabled = 1 if user.is_active else 0
        user.full_name = " ".join(part for part in (user.first_name, user.middle_name, user.last_name) if part).strip()
        user.creation = user.creation or user.date_joined.replace(tzinfo=None)
        user.modified = user.modified or user.creation
        user.owner = user.owner or "Administrator"
        user.modified_by = user.modified_by or "Administrator"
        user.save(update_fields=["name", "enabled", "full_name", "creation", "modified", "owner", "modified_by"])


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0007_user_view'),
        ('core', '0025_frappe_docshare'),
    ]

    operations = [
        migrations.RunSQL('DROP VIEW IF EXISTS "tabUser"', migrations.RunSQL.noop),
        migrations.AddField(
            model_name='user',
            name='_assign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='_liked_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='_user_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_in_mentions',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bulk_actions',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='bypass_restrict_ip_check_if_2fa_enabled',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='code_editor_type',
            field=models.CharField(blank=True, default='vscode', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dashboard',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='default_app',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_workspace',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='desk_theme',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dock_mode',
            field=models.CharField(blank=True, default='Pinned', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='docstatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='document_follow_frequency',
            field=models.CharField(blank=True, default='Daily', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_follow_notify',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_assigned_documents',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_commented_documents',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_created_documents',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_liked_documents',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_shared_documents',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='form_navigation_buttons',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='form_sidebar',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_settings',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_known_versions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_reset_password_key_generated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='list_sidebar',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logout_all_sessions',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='module_profile',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mute_sounds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_status',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='redirect_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='report_split_view',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_key',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restrict_ip',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_profile_name',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='search_bar',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='send_me_a_copy',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='send_read_receipt',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='send_welcome_email',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='show_absolute_datetime_in_timeline',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='show_my_space',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='simultaneous_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thread_notify',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='timeline',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='unsubscribed',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, default='System User', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='view_switcher',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='user',
            table='tabUser',
        ),
            migrations.RunPython(backfill_frappe_user, migrations.RunPython.noop),
    ]
