# Generated by Django 5.0.14 on 2026-10-05 20:50

from apps.core.migration_utils import tolerant_extra_columns
from django.db import migrations


@tolerant_extra_columns
def copy_automation(apps, schema_editor):
    OldFlow = apps.get_model("core", "AutomationFlow")
    OldAction = apps.get_model("core", "AutomationAction")
    OldSettings = apps.get_model("core", "AutomationSettings")
    NewFlow = apps.get_model("erpnext", "AutomationFlow")
    NewAction = apps.get_model("erpnext", "AutomationAction")
    User = apps.get_model("core", "User")
    Singles = apps.get_model("frappe", "Singles")
    emails = {user.pk: user.email for user in User.objects.all()}
    flow_fields = [
        "title", "document_type", "enabled", "disabled_reason", "trigger_type", "trigger_field", "from_value",
        "to_value", "custom_event", "date_field", "date_offset", "date_direction", "cron_expression", "next_run",
        "filters", "condition", "relationships", "revalidate_on_run", "run_as", "stop_on_error",
    ]
    for flow in OldFlow.objects.all():
        values = {field: getattr(flow, field) for field in flow_fields}
        values["enabled"] = int(bool(values["enabled"]))
        values["revalidate_on_run"] = int(bool(values["revalidate_on_run"]))
        values["stop_on_error"] = int(bool(values["stop_on_error"]))
        values["automation_user"] = emails.get(flow.automation_user_id, "")
        values["owner"] = emails.get(flow.owner_id, "Administrator")
        values["modified_by"] = values["owner"]
        values["creation"] = flow.creation.replace(tzinfo=None) if flow.creation else None
        values["modified"] = flow.modified.replace(tzinfo=None) if flow.modified else None
        NewFlow.objects.get_or_create(name=flow.name, defaults=values)
        for row in OldAction.objects.filter(flow_id=flow.pk).order_by("idx"):
            NewAction.objects.get_or_create(
                name=f"{flow.name}-{row.idx}",
                defaults={
                    "parent": flow.name,
                    "parentfield": "actions",
                    "parenttype": "Automation Flow",
                    "idx": row.idx + 1,
                    "step_key": row.step_key,
                    "step_type": row.step_type,
                    "action_type": row.action_type,
                    "target": row.target,
                    "output_alias": row.output_alias,
                    "params": row.params,
                    "step_condition": row.step_condition,
                    "related_condition": row.related_condition,
                    "parent_step": row.parent_step,
                    "branch": row.branch,
                    "owner": "Administrator",
                    "modified_by": "Administrator",
                },
            )
    settings = OldSettings.objects.first()
    if settings:
        for field in (
            "disable_automations", "max_depth", "failure_threshold", "stale_running_minutes", "max_attempts",
            "drain_seconds", "commit_every", "queue_retention_days", "step_output_limit", "event_payload_limit",
            "allow_unregistered_events",
        ):
            value = getattr(settings, field)
            value = "1" if value is True else "0" if value is False else str(value)
            Singles.objects.update_or_create(doctype="Automation Settings", field=field, defaults={"value": value})


class Migration(migrations.Migration):

    dependencies = [
        ('erpnext', '0045_automation_doctypes'),
        ('frappe', '0009_auth_table'),
        ('core', '0027_drop_user_email'),
    ]

    operations = [
        migrations.RunPython(copy_automation, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='automationaction',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='automationeventsubscription',
            name='resume_queue',
        ),
        migrations.RemoveField(
            model_name='automationeventsubscription',
            name='run',
        ),
        migrations.RemoveField(
            model_name='automationflow',
            name='automation_user',
        ),
        migrations.RemoveField(
            model_name='automationflow',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='automationtriggerqueue',
            name='automation',
        ),
        migrations.DeleteModel(
            name='AutomationSettings',
        ),
        migrations.RemoveField(
            model_name='automationtriggerqueue',
            name='triggered_by',
        ),
        migrations.RemoveField(
            model_name='backgroundtask',
            name='user',
        ),
        migrations.DeleteModel(
            name='AutomationAction',
        ),
        migrations.DeleteModel(
            name='AutomationEventSubscription',
        ),
        migrations.DeleteModel(
            name='AutomationFlow',
        ),
        migrations.DeleteModel(
            name='AutomationTriggerQueue',
        ),
        migrations.DeleteModel(
            name='BackgroundTask',
        ),
    ]
