from django.db import models

from apps.frappe.model.base import FrappeDateTimeField, FrappeTimeField


class UserFrappeFields(models.Model):
    name = models.CharField(max_length=140, unique=True, null=True, blank=True)
    owner = models.CharField(max_length=140, blank=True, default='')
    creation = FrappeDateTimeField(null=True, blank=True)
    modified = FrappeDateTimeField(null=True, blank=True)
    modified_by = models.CharField(max_length=140, blank=True, default='')
    docstatus = models.SmallIntegerField(default=0)
    idx = models.IntegerField(default=0)
    _user_tags = models.TextField(null=True, blank=True)
    _comments = models.TextField(null=True, blank=True)
    _assign = models.TextField(null=True, blank=True)
    _liked_by = models.TextField(null=True, blank=True)
    enabled = models.SmallIntegerField(default=1)
    middle_name = models.CharField(max_length=140, blank=True, null=True, default='')
    full_name = models.CharField(max_length=140, blank=True, null=True, default='')
    send_welcome_email = models.SmallIntegerField(default=1)
    unsubscribed = models.SmallIntegerField(default=0)
    role_profile_name = models.CharField(max_length=140, blank=True, null=True, default='')
    gender = models.CharField(max_length=140, blank=True, null=True, default='')
    phone = models.CharField(max_length=140, blank=True, null=True, default='')
    mobile_no = models.CharField(max_length=140, blank=True, null=True, default='')
    birth_date = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=140, blank=True, null=True, default='')
    interest = models.TextField(blank=True, null=True, default='')
    bio = models.TextField(blank=True, null=True, default='')
    mute_sounds = models.SmallIntegerField(default=0)
    logout_all_sessions = models.SmallIntegerField(default=1)
    reset_password_key = models.CharField(max_length=140, blank=True, null=True, default='')
    last_password_reset_date = models.DateField(null=True, blank=True)
    redirect_url = models.TextField(blank=True, null=True, default='')
    document_follow_notify = models.SmallIntegerField(default=0)
    document_follow_frequency = models.CharField(max_length=140, blank=True, null=True, default='Daily')
    thread_notify = models.SmallIntegerField(default=1)
    send_me_a_copy = models.SmallIntegerField(default=0)
    send_read_receipt = models.SmallIntegerField(default=0)
    allowed_in_mentions = models.SmallIntegerField(default=1)
    home_settings = models.TextField(blank=True, null=True, default='')
    simultaneous_sessions = models.IntegerField(null=True, blank=True)
    user_type = models.CharField(max_length=140, blank=True, null=True, default='System User')
    login_after = models.IntegerField(null=True, blank=True)
    login_before = models.IntegerField(null=True, blank=True)
    restrict_ip = models.TextField(blank=True, null=True, default='')
    bypass_restrict_ip_check_if_2fa_enabled = models.SmallIntegerField(default=0)
    last_ip = models.CharField(max_length=140, blank=True, null=True, default='')
    last_active = FrappeDateTimeField(null=True, blank=True)
    last_known_versions = models.TextField(blank=True, null=True, default='')
    api_key = models.CharField(max_length=140, blank=True, null=True, default='')
    desk_theme = models.CharField(max_length=140, blank=True, null=True, default='')
    module_profile = models.CharField(max_length=140, blank=True, null=True, default='')
    last_reset_password_key_generated_on = FrappeDateTimeField(null=True, blank=True)
    follow_created_documents = models.SmallIntegerField(default=0)
    follow_commented_documents = models.SmallIntegerField(default=0)
    follow_liked_documents = models.SmallIntegerField(default=0)
    follow_shared_documents = models.SmallIntegerField(default=0)
    follow_assigned_documents = models.SmallIntegerField(default=0)
    onboarding_status = models.TextField(blank=True, null=True, default='{}')
    default_workspace = models.CharField(max_length=140, blank=True, null=True, default='')
    code_editor_type = models.CharField(max_length=140, blank=True, null=True, default='vscode')
    default_app = models.CharField(max_length=140, blank=True, null=True, default='')
    search_bar = models.SmallIntegerField(default=1)
    notifications = models.SmallIntegerField(default=1)
    show_my_space = models.SmallIntegerField(default=0)
    dock_mode = models.CharField(max_length=140, blank=True, null=True, default='Pinned')
    list_sidebar = models.SmallIntegerField(default=1)
    bulk_actions = models.SmallIntegerField(default=1)
    view_switcher = models.SmallIntegerField(default=1)
    form_sidebar = models.SmallIntegerField(default=1)
    timeline = models.SmallIntegerField(default=1)
    dashboard = models.SmallIntegerField(default=1)
    show_absolute_datetime_in_timeline = models.SmallIntegerField(default=0)
    report_split_view = models.SmallIntegerField(default=1)
    form_navigation_buttons = models.SmallIntegerField(default=1)

    class Meta:
        abstract = True
