from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class CustomFieldGenerated(FrappeModel):
    doctype = 'Custom Field'
    dt = models.CharField(max_length=140, blank=True, null=True, default='')
    label = models.CharField(max_length=255, blank=True, null=True, default='')
    fieldname = models.CharField(max_length=140, blank=True, null=True, default='')
    insert_after = models.CharField(max_length=140, blank=True, null=True, default='')
    fieldtype = models.CharField(max_length=140, blank=True, null=True, default='Data')
    precision = models.CharField(max_length=140, blank=True, null=True, default='')
    options = models.TextField(blank=True, null=True, default='')
    fetch_from = models.TextField(blank=True, null=True, default='')
    fetch_if_empty = models.SmallIntegerField(default=0)
    collapsible = models.SmallIntegerField(default=0)
    collapsible_depends_on = models.TextField(blank=True, null=True, default='')
    default = models.TextField(blank=True, null=True, default='')
    depends_on = models.TextField(blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    permlevel = models.IntegerField(null=True, blank=True)
    width = models.CharField(max_length=140, blank=True, null=True, default='')
    columns = models.IntegerField(null=True, blank=True)
    reqd = models.SmallIntegerField(default=0)
    unique = models.SmallIntegerField(default=0)
    is_virtual = models.SmallIntegerField(default=0)
    read_only = models.SmallIntegerField(default=0)
    ignore_user_permissions = models.SmallIntegerField(default=0)
    hidden = models.SmallIntegerField(default=0)
    print_hide = models.SmallIntegerField(default=0)
    print_hide_if_no_value = models.SmallIntegerField(default=0)
    print_width = models.CharField(max_length=140, blank=True, null=True, default='')
    alignment = models.CharField(max_length=140, blank=True, null=True, default='')
    no_copy = models.SmallIntegerField(default=0)
    ignore_versioning = models.SmallIntegerField(default=0)
    allow_on_submit = models.SmallIntegerField(default=0)
    in_list_view = models.SmallIntegerField(default=0)
    in_standard_filter = models.SmallIntegerField(default=0)
    in_global_search = models.SmallIntegerField(default=0)
    bold = models.SmallIntegerField(default=0)
    report_hide = models.SmallIntegerField(default=0)
    search_index = models.SmallIntegerField(default=0)
    ignore_xss_filter = models.SmallIntegerField(default=0)
    translatable = models.SmallIntegerField(default=0)
    length = models.IntegerField(null=True, blank=True)
    mandatory_depends_on = models.TextField(blank=True, null=True, default='')
    read_only_depends_on = models.TextField(blank=True, null=True, default='')
    allow_in_quick_entry = models.SmallIntegerField(default=0)
    allow_bulk_edit = models.SmallIntegerField(default=0)
    in_preview = models.SmallIntegerField(default=0)
    hide_seconds = models.SmallIntegerField(default=0)
    hide_days = models.SmallIntegerField(default=0)
    hide_border = models.SmallIntegerField(default=0)
    non_negative = models.SmallIntegerField(default=0)
    min_value = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    max_value = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    module = models.CharField(max_length=140, blank=True, null=True, default='')
    is_system_generated = models.SmallIntegerField(default=0)
    is_app_disabled = models.SmallIntegerField(default=0)
    sort_options = models.SmallIntegerField(default=0)
    link_filters = models.TextField(blank=True, null=True, default='')
    show_dashboard = models.SmallIntegerField(default=0)
    placeholder = models.CharField(max_length=140, blank=True, null=True, default='')
    button_color = models.CharField(max_length=140, blank=True, null=True, default='')
    set_only_once = models.SmallIntegerField(default=0)
    mask = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
