from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class EmailAccountGenerated(FrappeModel):
    doctype = 'Email Account'
    email_id = models.CharField(max_length=140, blank=True, null=True, default='')
    login_id_is_different = models.SmallIntegerField(default=0)
    login_id = models.CharField(max_length=140, blank=True, null=True, default='')
    password = models.TextField(blank=True, null=True, default='')
    awaiting_password = models.SmallIntegerField(default=0)
    ascii_encode_password = models.SmallIntegerField(default=0)
    email_account_name = models.CharField(max_length=140, blank=True, null=True, default='')
    domain = models.CharField(max_length=140, blank=True, null=True, default='')
    service = models.CharField(max_length=140, blank=True, null=True, default='')
    enable_incoming = models.SmallIntegerField(default=0)
    use_imap = models.SmallIntegerField(default=0)
    email_server = models.CharField(max_length=140, blank=True, null=True, default='')
    use_ssl = models.SmallIntegerField(default=0)
    attachment_limit = models.IntegerField(null=True, blank=True)
    append_to = models.CharField(max_length=140, blank=True, null=True, default='')
    default_incoming = models.SmallIntegerField(default=0)
    email_sync_option = models.CharField(max_length=140, blank=True, null=True, default='UNSEEN')
    initial_sync_count = models.CharField(max_length=140, blank=True, null=True, default='250')
    notify_if_unreplied = models.SmallIntegerField(default=0)
    unreplied_for_mins = models.IntegerField(null=True, blank=True)
    send_notification_to = models.TextField(blank=True, null=True, default='')
    enable_outgoing = models.SmallIntegerField(default=0)
    smtp_server = models.CharField(max_length=140, blank=True, null=True, default='')
    use_tls = models.SmallIntegerField(default=0)
    smtp_port = models.CharField(max_length=140, blank=True, null=True, default='')
    default_outgoing = models.SmallIntegerField(default=0)
    always_use_account_email_id_as_sender = models.SmallIntegerField(default=0)
    always_use_account_name_as_sender_name = models.SmallIntegerField(default=0)
    send_unsubscribe_message = models.SmallIntegerField(default=1)
    track_email_status = models.SmallIntegerField(default=1)
    no_smtp_authentication = models.SmallIntegerField(default=0)
    add_signature = models.SmallIntegerField(default=0)
    signature = models.TextField(blank=True, null=True, default='')
    enable_auto_reply = models.SmallIntegerField(default=0)
    auto_reply_message = models.TextField(blank=True, null=True, default='')
    footer = models.TextField(blank=True, null=True, default='')
    uidvalidity = models.CharField(max_length=140, blank=True, null=True, default='')
    uidnext = models.IntegerField(null=True, blank=True)
    no_failed = models.IntegerField(null=True, blank=True)
    enable_automatic_linking = models.SmallIntegerField(default=0)
    incoming_port = models.CharField(max_length=140, blank=True, null=True, default='')
    append_emails_to_sent_folder = models.SmallIntegerField(default=0)
    use_ssl_for_outgoing = models.SmallIntegerField(default=0)
    create_contact = models.SmallIntegerField(default=1)
    brand_logo = models.TextField(blank=True, null=True, default='')
    auth_method = models.CharField(max_length=140, blank=True, null=True, default='Basic')
    use_starttls = models.SmallIntegerField(default=0)
    connected_app = models.CharField(max_length=140, blank=True, null=True, default='')
    connected_user = models.CharField(max_length=140, blank=True, null=True, default='')
    validate_ssl_certificate = models.SmallIntegerField(default=1)
    frappe_mail_site = models.CharField(max_length=140, blank=True, null=True, default='https://frappemail.com')
    api_key = models.CharField(max_length=140, blank=True, null=True, default='')
    api_secret = models.TextField(blank=True, null=True, default='')
    backend_app_flow = models.SmallIntegerField(default=0)
    sent_folder_name = models.CharField(max_length=140, blank=True, null=True, default='')
    always_bcc = models.CharField(max_length=140, blank=True, null=True, default='')
    last_received_at = FrappeDateTimeField(null=True, blank=True)
    add_x_original_from = models.SmallIntegerField(default=1)
    add_reply_to_header = models.SmallIntegerField(default=1)
    dsn_notify_type = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
