from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class SalesInvoiceItemGenerated(FrappeChildModel):
    doctype = 'Sales Invoice Item'
    barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    is_product_bundle = models.SmallIntegerField(default=0)
    product_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    uom = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_factor = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    margin_type = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_rate_or_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    pricing_rules = models.TextField(blank=True, null=True, default='')
    is_free_item = models.SmallIntegerField(default=0)
    net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    delivered_by_supplier = models.SmallIntegerField(default=0)
    income_account = models.CharField(max_length=140, blank=True, null=True, default='')
    expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    item_tax_template = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default=':Company')
    deferred_revenue_account = models.CharField(max_length=140, blank=True, null=True, default='')
    service_stop_date = models.DateField(null=True, blank=True)
    enable_deferred_revenue = models.SmallIntegerField(default=0)
    service_start_date = models.DateField(null=True, blank=True)
    service_end_date = models.DateField(null=True, blank=True)
    weight_per_unit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    target_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    quality_inspection = models.CharField(max_length=140, blank=True, null=True, default='')
    batch_no = models.CharField(max_length=140, blank=True, null=True, default='')
    allow_zero_valuation_rate = models.SmallIntegerField(default=0)
    serial_no = models.TextField(blank=True, null=True, default='')
    item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    brand = models.CharField(max_length=140, blank=True, null=True, default='')
    item_tax_rate = models.TextField(blank=True, null=True, default='')
    actual_batch_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    actual_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    sales_order = models.CharField(max_length=140, blank=True, null=True, default='')
    so_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    delivery_note = models.CharField(max_length=140, blank=True, null=True, default='')
    dn_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    delivered_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    is_fixed_asset = models.SmallIntegerField(default=0)
    asset = models.CharField(max_length=140, blank=True, null=True, default='')
    page_break = models.SmallIntegerField(default=0)
    finance_book = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_invoice_item = models.CharField(max_length=140, blank=True, null=True, default='')
    incoming_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_account = models.CharField(max_length=140, blank=True, null=True, default='')
    grant_commission = models.SmallIntegerField(default=0)
    purchase_order = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    has_item_scanned = models.SmallIntegerField(default=0)
    serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    use_serial_batch_fields = models.SmallIntegerField(default=0)
    distributed_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    company_total_stock = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    pos_invoice_item = models.CharField(max_length=140, blank=True, null=True, default='')
    pos_invoice = models.CharField(max_length=140, blank=True, null=True, default='')
    scio_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    tax_withholding_category = models.CharField(max_length=140, blank=True, null=True, default='')
    apply_tds = models.SmallIntegerField(default=1)
    against_pick_list = models.CharField(max_length=140, blank=True, null=True, default='')
    pick_list_item = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
