from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class PurchaseOrderGenerated(FrappeModel):
    doctype = 'Purchase Order'
    title = models.CharField(max_length=140, blank=True, null=True, default='')
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_name = models.CharField(max_length=140, blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    transaction_date = models.DateField(null=True, blank=True)
    schedule_date = models.DateField(null=True, blank=True)
    order_confirmation_no = models.CharField(max_length=140, blank=True, null=True, default='')
    order_confirmation_date = models.DateField(null=True, blank=True)
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    customer = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_name = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_contact_display = models.TextField(blank=True, null=True, default='')
    customer_contact_mobile = models.TextField(blank=True, null=True, default='')
    customer_contact_email = models.TextField(blank=True, null=True, default='')
    supplier_address = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    address_display = models.TextField(blank=True, null=True, default='')
    contact_display = models.TextField(blank=True, null=True, default='')
    contact_mobile = models.TextField(blank=True, null=True, default='')
    contact_email = models.TextField(blank=True, null=True, default='')
    shipping_address = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_address_display = models.TextField(blank=True, null=True, default='')
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    buying_price_list = models.CharField(max_length=140, blank=True, null=True, default='')
    price_list_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    plc_conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ignore_pricing_rule = models.SmallIntegerField(default=0)
    set_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    is_subcontracted = models.SmallIntegerField(default=0)
    supplier_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    scan_barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    total_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_net_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    taxes_and_charges = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_rule = models.CharField(max_length=140, blank=True, null=True, default='')
    other_charges_calculation = models.TextField(blank=True, null=True, default='')
    base_taxes_and_charges_added = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_taxes_and_charges_deducted = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    taxes_and_charges_added = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    taxes_and_charges_deducted = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    apply_discount_on = models.CharField(max_length=140, blank=True, null=True, default='Grand Total')
    base_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    base_rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    disable_rounded_total = models.SmallIntegerField(default=0)
    in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    advance_paid = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    payment_terms_template = models.CharField(max_length=140, blank=True, null=True, default='')
    tc_name = models.CharField(max_length=140, blank=True, null=True, default='')
    terms = models.TextField(blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    ref_sq = models.CharField(max_length=140, blank=True, null=True, default='')
    party_account_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    inter_company_order_reference = models.CharField(max_length=140, blank=True, null=True, default='')
    remarks = models.TextField(blank=True, null=True, default='')
    per_received = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    per_billed = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    select_print_heading = models.CharField(max_length=140, blank=True, null=True, default='')
    group_same_items = models.SmallIntegerField(default=0)
    language = models.CharField(max_length=140, blank=True, null=True, default='')
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    auto_repeat = models.CharField(max_length=140, blank=True, null=True, default='')
    tax_category = models.CharField(max_length=140, blank=True, null=True, default='')
    set_reserve_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    billing_address = models.CharField(max_length=140, blank=True, null=True, default='')
    billing_address_display = models.TextField(blank=True, null=True, default='')
    is_internal_supplier = models.SmallIntegerField(default=0)
    represents_company = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    set_from_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    incoterm = models.CharField(max_length=140, blank=True, null=True, default='')
    named_place = models.CharField(max_length=140, blank=True, null=True, default='')
    advance_payment_status = models.CharField(max_length=140, blank=True, null=True, default='')
    has_unit_price_items = models.SmallIntegerField(default=0)
    dispatch_address = models.CharField(max_length=140, blank=True, null=True, default='')
    dispatch_address_display = models.TextField(blank=True, null=True, default='')
    supplier_group = models.CharField(max_length=140, blank=True, null=True, default='')
    last_scanned_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    mps = models.CharField(max_length=140, blank=True, null=True, default='')
    transaction_time = FrappeTimeField(null=True, blank=True)

    class Meta:
        abstract = True
