from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class PurchaseInvoiceGenerated(FrappeModel):
    doctype = 'Purchase Invoice'
    title = models.CharField(max_length=140, blank=True, null=True, default='')
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_name = models.CharField(max_length=140, blank=True, null=True, default='')
    tax_id = models.CharField(max_length=140, blank=True, null=True, default='')
    due_date = models.DateField(null=True, blank=True)
    is_paid = models.SmallIntegerField(default=0)
    is_return = models.SmallIntegerField(default=0)
    apply_tds = models.SmallIntegerField(default=0)
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    posting_date = models.DateField(null=True, blank=True)
    posting_time = FrappeTimeField(null=True, blank=True)
    set_posting_time = models.SmallIntegerField(default=0)
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    on_hold = models.SmallIntegerField(default=0)
    release_date = models.DateField(null=True, blank=True)
    hold_comment = models.TextField(blank=True, null=True, default='')
    bill_no = models.CharField(max_length=140, blank=True, null=True, default='')
    bill_date = models.DateField(null=True, blank=True)
    return_against = models.CharField(max_length=140, blank=True, null=True, default='')
    update_billed_amount_in_purchase_order = models.SmallIntegerField(default=0)
    update_billed_amount_in_purchase_receipt = models.SmallIntegerField(default=1)
    supplier_address = models.CharField(max_length=140, blank=True, null=True, default='')
    address_display = models.TextField(blank=True, null=True, default='')
    contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_display = models.TextField(blank=True, null=True, default='')
    contact_mobile = models.TextField(blank=True, null=True, default='')
    contact_email = models.TextField(blank=True, null=True, default='')
    shipping_address = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_address_display = models.TextField(blank=True, null=True, default='')
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    buying_price_list = models.CharField(max_length=140, blank=True, null=True, default='')
    price_list_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    plc_conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ignore_pricing_rule = models.SmallIntegerField(default=0)
    set_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    is_subcontracted = models.SmallIntegerField(default=0)
    update_stock = models.SmallIntegerField(default=0)
    scan_barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    total_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_net_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    tax_category = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_rule = models.CharField(max_length=140, blank=True, null=True, default='')
    taxes_and_charges = models.CharField(max_length=140, blank=True, null=True, default='')
    other_charges_calculation = models.TextField(blank=True, null=True, default='')
    base_taxes_and_charges_added = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_taxes_and_charges_deducted = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    taxes_and_charges_added = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    taxes_and_charges_deducted = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    apply_discount_on = models.CharField(max_length=140, blank=True, null=True, default='Grand Total')
    base_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    total_advance = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    outstanding_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    disable_rounded_total = models.SmallIntegerField(default=0)
    mode_of_payment = models.CharField(max_length=140, blank=True, null=True, default='')
    cash_bank_account = models.CharField(max_length=140, blank=True, null=True, default='')
    clearance_date = models.DateField(null=True, blank=True)
    paid_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_paid_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    write_off_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_write_off_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    write_off_account = models.CharField(max_length=140, blank=True, null=True, default='')
    write_off_cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    allocate_advances_automatically = models.SmallIntegerField(default=0)
    payment_terms_template = models.CharField(max_length=140, blank=True, null=True, default='')
    tc_name = models.CharField(max_length=140, blank=True, null=True, default='')
    terms = models.TextField(blank=True, null=True, default='')
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    group_same_items = models.SmallIntegerField(default=0)
    select_print_heading = models.CharField(max_length=140, blank=True, null=True, default='')
    language = models.CharField(max_length=140, blank=True, null=True, default='')
    is_internal_supplier = models.SmallIntegerField(default=0)
    credit_to = models.CharField(max_length=140, blank=True, null=True, default='')
    party_account_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    is_opening = models.CharField(max_length=140, blank=True, null=True, default='No')
    against_expense_account = models.TextField(blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    inter_company_invoice_reference = models.CharField(max_length=140, blank=True, null=True, default='')
    remarks = models.TextField(blank=True, null=True, default='')
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    auto_repeat = models.CharField(max_length=140, blank=True, null=True, default='')
    billing_address = models.CharField(max_length=140, blank=True, null=True, default='')
    billing_address_display = models.TextField(blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    unrealized_profit_loss_account = models.CharField(max_length=140, blank=True, null=True, default='')
    represents_company = models.CharField(max_length=140, blank=True, null=True, default='')
    set_from_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    per_received = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ignore_default_payment_terms_template = models.SmallIntegerField(default=0)
    subscription = models.CharField(max_length=140, blank=True, null=True, default='')
    incoterm = models.CharField(max_length=140, blank=True, null=True, default='')
    named_place = models.CharField(max_length=140, blank=True, null=True, default='')
    only_include_allocated_payments = models.SmallIntegerField(default=0)
    use_company_roundoff_cost_center = models.SmallIntegerField(default=0)
    use_transaction_date_exchange_rate = models.SmallIntegerField(default=0)
    supplier_group = models.CharField(max_length=140, blank=True, null=True, default='')
    update_outstanding_for_self = models.SmallIntegerField(default=1)
    sender = models.CharField(max_length=140, blank=True, null=True, default='')
    dispatch_address_display = models.TextField(blank=True, null=True, default='')
    dispatch_address = models.CharField(max_length=140, blank=True, null=True, default='')
    last_scanned_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    claimed_landed_cost_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    tax_withholding_group = models.CharField(max_length=140, blank=True, null=True, default='')
    ignore_tax_withholding_threshold = models.SmallIntegerField(default=0)
    override_tax_withholding_entries = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
