from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class DeliveryNoteItemGenerated(FrappeChildModel):
    doctype = 'Delivery Note Item'
    barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    is_product_bundle = models.SmallIntegerField(default=0)
    product_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    uom = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_factor = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    margin_type = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_rate_or_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    pricing_rules = models.TextField(blank=True, null=True, default='')
    is_free_item = models.SmallIntegerField(default=0)
    net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_per_unit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    target_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    quality_inspection = models.CharField(max_length=140, blank=True, null=True, default='')
    actual_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    actual_batch_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    brand = models.CharField(max_length=140, blank=True, null=True, default='')
    item_tax_rate = models.TextField(blank=True, null=True, default='')
    expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    item_tax_template = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default=':Company')
    allow_zero_valuation_rate = models.SmallIntegerField(default=0)
    against_sales_order = models.CharField(max_length=140, blank=True, null=True, default='')
    against_sales_invoice = models.CharField(max_length=140, blank=True, null=True, default='')
    so_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    si_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    installed_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    billed_amt = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    closed = models.SmallIntegerField(default=0)
    page_break = models.SmallIntegerField(default=0)
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    dn_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    returned_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    incoming_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    grant_commission = models.SmallIntegerField(default=0)
    pick_list_item = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_order = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    has_item_scanned = models.SmallIntegerField(default=0)
    material_request = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request_item = models.CharField(max_length=140, blank=True, null=True, default='')
    received_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    packed_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    serial_no = models.TextField(blank=True, null=True, default='')
    batch_no = models.CharField(max_length=140, blank=True, null=True, default='')
    use_serial_batch_fields = models.SmallIntegerField(default=0)
    distributed_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    company_total_stock = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    against_pick_list = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
