# Generated by Django 5.0.14 on 2026-09-27 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Short code for the building', max_length=50, unique=True)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building',
                'db_table': 'tabBuilding',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(help_text='Floor level number, e.g. 0 for Ground, 1 for First Floor, -1 for Basement')),
                ('floor_plan_image', models.CharField(blank=True, max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='property.building')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Floor',
                'db_table': 'tabFloor',
                'unique_together': {('building', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('gross_leasable_area', models.DecimalField(blank=True, decimal_places=2, help_text='In square meters', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Under Construction', 'Under Construction'), ('Closed', 'Closed')], default='Operational', max_length=50)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mall',
                'db_table': 'tabMall',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='property.mall'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.CharField(max_length=100, unique=True)),
                ('unit_type', models.CharField(choices=[('Retail Shop', 'Retail Shop'), ('Food Court', 'Food Court'), ('Kiosk', 'Kiosk'), ('Anchor Tenant', 'Anchor Tenant'), ('Office', 'Office'), ('Storage', 'Storage')], max_length=50)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=10)),
                ('base_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Standard monthly base rent', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Under Maintenance', 'Under Maintenance'), ('Reserved', 'Reserved')], default='Vacant', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='property.floor')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit',
                'db_table': 'tabUnit',
            },
        ),
    ]
