# Generated by Django 5.0.14 on 2026-10-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_attendance_employeecheckin_leavepolicyassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=140)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=140)),
                ('docstatus', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
                ('naming_series', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('employee', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('employee_name', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('leave_type', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('new_leaves_allocated', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('carry_forward', models.SmallIntegerField(default=0)),
                ('unused_leaves', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('total_leaves_allocated', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('total_leaves_encashed', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('compensatory_request', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('leave_period', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('leave_policy', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('expired', models.SmallIntegerField(default=0)),
                ('amended_from', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('carry_forwarded_leaves_count', models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True)),
                ('leave_policy_assignment', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Leave Allocation',
                'db_table': 'tabLeave Allocation',
                'ordering': ['-creation'],
            },
        ),
    ]
