from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class ItemGenerated(FrappeModel):
    doctype = 'Item'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    variant_of = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    disabled = models.SmallIntegerField(default=0)
    allow_alternative_item = models.SmallIntegerField(default=0)
    is_stock_item = models.SmallIntegerField(default=1)
    include_item_in_manufacturing = models.SmallIntegerField(default=1)
    opening_stock = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    valuation_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    standard_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    is_fixed_asset = models.SmallIntegerField(default=0)
    asset_category = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    brand = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    shelf_life_in_days = models.IntegerField(null=True, blank=True)
    end_of_life = models.DateField(null=True, blank=True)
    default_material_request_type = models.CharField(max_length=140, blank=True, null=True, default='Purchase')
    valuation_method = models.CharField(max_length=140, blank=True, null=True, default='')
    warranty_period = models.CharField(max_length=140, blank=True, null=True, default='')
    weight_per_unit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    has_batch_no = models.SmallIntegerField(default=0)
    create_new_batch = models.SmallIntegerField(default=0)
    batch_number_series = models.CharField(max_length=140, blank=True, null=True, default='')
    has_expiry_date = models.SmallIntegerField(default=0)
    retain_sample = models.SmallIntegerField(default=0)
    sample_quantity = models.IntegerField(null=True, blank=True)
    has_serial_no = models.SmallIntegerField(default=0)
    serial_no_series = models.CharField(max_length=140, blank=True, null=True, default='')
    use_serial_no_wise_valuation = models.SmallIntegerField(default=1)
    has_variants = models.SmallIntegerField(default=0)
    variant_based_on = models.CharField(max_length=140, blank=True, null=True, default='Item Attribute')
    is_purchase_item = models.SmallIntegerField(default=1)
    purchase_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    min_order_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    safety_stock = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    lead_time_days = models.IntegerField(null=True, blank=True)
    last_purchase_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    is_customer_provided_item = models.SmallIntegerField(default=0)
    delivered_by_supplier = models.SmallIntegerField(default=0)
    country_of_origin = models.CharField(max_length=140, blank=True, null=True, default='')
    customs_tariff_number = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    is_sales_item = models.SmallIntegerField(default=1)
    max_discount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    enable_deferred_revenue = models.SmallIntegerField(default=0)
    no_of_months = models.IntegerField(null=True, blank=True)
    enable_deferred_expense = models.SmallIntegerField(default=0)
    no_of_months_exp = models.IntegerField(null=True, blank=True)
    inspection_required_before_purchase = models.SmallIntegerField(default=0)
    inspection_required_before_delivery = models.SmallIntegerField(default=0)
    quality_inspection_template = models.CharField(max_length=140, blank=True, null=True, default='')
    default_bom = models.CharField(max_length=140, blank=True, null=True, default='')
    is_sub_contracted_item = models.SmallIntegerField(default=0)
    customer_code = models.TextField(blank=True, null=True, default='')
    total_projected_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    over_delivery_receipt_allowance = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    over_billing_allowance = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    auto_create_assets = models.SmallIntegerField(default=0)
    default_item_manufacturer = models.CharField(max_length=140, blank=True, null=True, default='')
    default_manufacturer_part_no = models.CharField(max_length=140, blank=True, null=True, default='')
    grant_commission = models.SmallIntegerField(default=1)
    is_grouped_asset = models.SmallIntegerField(default=0)
    allow_negative_stock = models.SmallIntegerField(default=0)
    production_capacity = models.IntegerField(null=True, blank=True)
    purchase_tax_withholding_category = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_tax_withholding_category = models.CharField(max_length=140, blank=True, null=True, default='')
    restrict_to_companies = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
