from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class SalarySlipGenerated(FrappeModel):
    doctype = 'Salary Slip'
    posting_date = models.DateField(null=True, blank=True)
    employee = models.CharField(max_length=140, blank=True, null=True, default='')
    employee_name = models.CharField(max_length=140, blank=True, null=True, default='')
    department = models.CharField(max_length=140, blank=True, null=True, default='')
    designation = models.CharField(max_length=140, blank=True, null=True, default='')
    branch = models.CharField(max_length=140, blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='')
    journal_entry = models.CharField(max_length=140, blank=True, null=True, default='')
    payroll_entry = models.CharField(max_length=140, blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    salary_slip_based_on_timesheet = models.SmallIntegerField(default=0)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    salary_structure = models.CharField(max_length=140, blank=True, null=True, default='')
    payroll_frequency = models.CharField(max_length=140, blank=True, null=True, default='')
    total_working_days = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    leave_without_pay = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    payment_days = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_working_hours = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    hour_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    bank_name = models.CharField(max_length=140, blank=True, null=True, default='')
    bank_account_no = models.CharField(max_length=140, blank=True, null=True, default='')
    deduct_tax_for_unsubmitted_tax_exemption_proof = models.SmallIntegerField(default=0)
    gross_pay = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_pay = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    mode_of_payment = models.CharField(max_length=140, blank=True, null=True, default='')
    absent_days = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    unmarked_days = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    total_deduction = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    base_hour_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_gross_pay = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    exchange_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total_deduction = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_pay = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total_in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    year_to_date = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    month_to_date = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_year_to_date = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_month_to_date = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    gross_year_to_date = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_gross_year_to_date = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ctc = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    income_from_other_sources = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_earnings = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    non_taxable_earnings = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    deductions_before_tax_calculation = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    tax_exemption_declaration = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    standard_tax_exemption_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    annual_taxable_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    income_tax_deducted_till_date = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    future_income_tax_deductions = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    current_month_income_tax = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_income_tax = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    salary_withholding = models.CharField(max_length=140, blank=True, null=True, default='')
    salary_withholding_cycle = models.CharField(max_length=140, blank=True, null=True, default='')
    current_payroll_period = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
