from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class SalesInvoiceGenerated(FrappeModel):
    doctype = 'Sales Invoice'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    customer = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_name = models.TextField(blank=True, null=True, default='')
    tax_id = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    is_pos = models.SmallIntegerField(default=0)
    pos_profile = models.CharField(max_length=140, blank=True, null=True, default='')
    is_return = models.SmallIntegerField(default=0)
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    posting_date = models.DateField(null=True, blank=True)
    posting_time = FrappeTimeField(null=True, blank=True)
    set_posting_time = models.SmallIntegerField(default=0)
    due_date = models.DateField(null=True, blank=True)
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    return_against = models.CharField(max_length=140, blank=True, null=True, default='')
    update_billed_amount_in_sales_order = models.SmallIntegerField(default=0)
    po_no = models.CharField(max_length=140, blank=True, null=True, default='')
    po_date = models.DateField(null=True, blank=True)
    customer_address = models.CharField(max_length=140, blank=True, null=True, default='')
    address_display = models.TextField(blank=True, null=True, default='')
    contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_display = models.TextField(blank=True, null=True, default='')
    contact_mobile = models.TextField(blank=True, null=True, default='')
    contact_email = models.CharField(max_length=140, blank=True, null=True, default='')
    territory = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_address_name = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_address = models.TextField(blank=True, null=True, default='')
    shipping_contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_contact_display = models.TextField(blank=True, null=True, default='')
    shipping_contact_mobile = models.TextField(blank=True, null=True, default='')
    shipping_contact_email = models.CharField(max_length=140, blank=True, null=True, default='')
    company_address = models.CharField(max_length=140, blank=True, null=True, default='')
    company_address_display = models.TextField(blank=True, null=True, default='')
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    selling_price_list = models.CharField(max_length=140, blank=True, null=True, default='')
    price_list_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    plc_conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ignore_pricing_rule = models.SmallIntegerField(default=0)
    set_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    update_stock = models.SmallIntegerField(default=0)
    scan_barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    total_billing_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_net_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    taxes_and_charges = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_rule = models.CharField(max_length=140, blank=True, null=True, default='')
    tax_category = models.CharField(max_length=140, blank=True, null=True, default='')
    other_charges_calculation = models.TextField(blank=True, null=True, default='')
    base_total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    loyalty_points = models.IntegerField(null=True, blank=True)
    loyalty_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    redeem_loyalty_points = models.SmallIntegerField(default=0)
    loyalty_program = models.CharField(max_length=140, blank=True, null=True, default='')
    loyalty_redemption_account = models.CharField(max_length=140, blank=True, null=True, default='')
    loyalty_redemption_cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    apply_discount_on = models.CharField(max_length=15, blank=True, null=True, default='Grand Total')
    base_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_in_words = models.TextField(blank=True, null=True, default='')
    grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    in_words = models.TextField(blank=True, null=True, default='')
    total_advance = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    outstanding_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    allocate_advances_automatically = models.SmallIntegerField(default=0)
    payment_terms_template = models.CharField(max_length=140, blank=True, null=True, default='')
    cash_bank_account = models.CharField(max_length=140, blank=True, null=True, default='')
    base_paid_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    paid_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_change_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    change_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    account_for_change_amount = models.CharField(max_length=140, blank=True, null=True, default='')
    write_off_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_write_off_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    write_off_outstanding_amount_automatically = models.SmallIntegerField(default=0)
    write_off_account = models.CharField(max_length=140, blank=True, null=True, default='')
    write_off_cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    tc_name = models.CharField(max_length=140, blank=True, null=True, default='')
    terms = models.TextField(blank=True, null=True, default='')
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    group_same_items = models.SmallIntegerField(default=0)
    language = models.CharField(max_length=140, blank=True, null=True, default='')
    select_print_heading = models.CharField(max_length=140, blank=True, null=True, default='')
    inter_company_invoice_reference = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_group = models.CharField(max_length=140, blank=True, null=True, default='')
    is_discounted = models.SmallIntegerField(default=0)
    status = models.CharField(max_length=30, blank=True, null=True, default='Draft')
    debit_to = models.CharField(max_length=140, blank=True, null=True, default='')
    party_account_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    is_opening = models.CharField(max_length=4, blank=True, null=True, default='No')
    remarks = models.TextField(blank=True, null=True, default='')
    sales_partner = models.CharField(max_length=140, blank=True, null=True, default='')
    commission_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_commission = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    auto_repeat = models.CharField(max_length=140, blank=True, null=True, default='')
    against_income_account = models.TextField(blank=True, null=True, default='')
    is_consolidated = models.SmallIntegerField(default=0)
    is_internal_customer = models.SmallIntegerField(default=0)
    company_tax_id = models.CharField(max_length=140, blank=True, null=True, default='')
    unrealized_profit_loss_account = models.CharField(max_length=140, blank=True, null=True, default='')
    represents_company = models.CharField(max_length=140, blank=True, null=True, default='')
    set_target_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    is_debit_note = models.SmallIntegerField(default=0)
    disable_rounded_total = models.SmallIntegerField(default=0)
    additional_discount_account = models.CharField(max_length=140, blank=True, null=True, default='')
    dispatch_address_name = models.CharField(max_length=140, blank=True, null=True, default='')
    dispatch_address = models.TextField(blank=True, null=True, default='')
    ignore_default_payment_terms_template = models.SmallIntegerField(default=0)
    total_billing_hours = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount_eligible_for_commission = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    subscription = models.CharField(max_length=140, blank=True, null=True, default='')
    is_cash_or_non_trade_discount = models.SmallIntegerField(default=0)
    incoterm = models.CharField(max_length=140, blank=True, null=True, default='')
    named_place = models.CharField(max_length=140, blank=True, null=True, default='')
    only_include_allocated_payments = models.SmallIntegerField(default=0)
    use_company_roundoff_cost_center = models.SmallIntegerField(default=0)
    update_billed_amount_in_delivery_note = models.SmallIntegerField(default=1)
    dont_create_loyalty_points = models.SmallIntegerField(default=0)
    coupon_code = models.CharField(max_length=140, blank=True, null=True, default='')
    update_outstanding_for_self = models.SmallIntegerField(default=1)
    utm_medium = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_content = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_campaign = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_source = models.CharField(max_length=140, blank=True, null=True, default='')
    company_contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    is_created_using_pos = models.SmallIntegerField(default=0)
    pos_closing_entry = models.CharField(max_length=140, blank=True, null=True, default='')
    last_scanned_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    has_subcontracted = models.SmallIntegerField(default=0)
    apply_tds = models.SmallIntegerField(default=0)
    tax_withholding_group = models.CharField(max_length=140, blank=True, null=True, default='')
    ignore_tax_withholding_threshold = models.SmallIntegerField(default=0)
    override_tax_withholding_entries = models.SmallIntegerField(default=0)
    title = models.CharField(max_length=140, blank=True, null=True, default='')
    _seen = models.TextField(null=True, blank=True)

    class Meta:
        abstract = True
