# Generated by Django 5.0.14 on 2026-10-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=140, unique=True)),
                ('desk_access', models.SmallIntegerField(default=1)),
                ('disabled', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Role',
                'db_table': 'tabRole',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('current', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Series',
                'db_table': 'tabSeries',
            },
        ),
        migrations.CreateModel(
            name='Singles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=140)),
                ('field', models.CharField(max_length=140)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'tabSingles',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=140)),
                ('allow', models.CharField(max_length=140)),
                ('for_value', models.CharField(max_length=140)),
                ('applicable_for', models.CharField(blank=True, default='', max_length=140)),
                ('apply_to_all_doctypes', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'tabUser Permission',
            },
        ),
        migrations.CreateModel(
            name='DocPerm',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('parent', models.CharField(max_length=140)),
                ('parentfield', models.CharField(default='permissions', max_length=140)),
                ('parenttype', models.CharField(default='DocType', max_length=140)),
                ('role', models.CharField(max_length=140)),
                ('permlevel', models.IntegerField(default=0)),
                ('read', models.SmallIntegerField(default=0)),
                ('write', models.SmallIntegerField(default=0)),
                ('create', models.SmallIntegerField(default=0)),
                ('delete', models.SmallIntegerField(default=0)),
                ('submit', models.SmallIntegerField(default=0)),
                ('cancel', models.SmallIntegerField(default=0)),
                ('amend', models.SmallIntegerField(default=0)),
                ('report', models.SmallIntegerField(default=0)),
                ('export', models.SmallIntegerField(default=0)),
                ('import_data', models.SmallIntegerField(db_column='import', default=0)),
                ('share', models.SmallIntegerField(default=0)),
                ('print', models.SmallIntegerField(default=0)),
                ('email', models.SmallIntegerField(default=0)),
                ('select', models.SmallIntegerField(default=0)),
                ('if_owner', models.SmallIntegerField(default=0)),
                ('idx', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tabDocPerm',
                'indexes': [models.Index(fields=['parent'], name='tabDocPerm_parent_7228c0_idx'), models.Index(fields=['role'], name='tabDocPerm_role_f8f814_idx')],
            },
        ),
        migrations.CreateModel(
            name='HasRole',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('parent', models.CharField(max_length=140)),
                ('parentfield', models.CharField(default='roles', max_length=140)),
                ('parenttype', models.CharField(default='User', max_length=140)),
                ('role', models.CharField(max_length=140)),
                ('idx', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tabHas Role',
                'indexes': [models.Index(fields=['parent'], name='tabHas Role_parent_ca05db_idx'), models.Index(fields=['role'], name='tabHas Role_role_139fd6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='singles',
            constraint=models.UniqueConstraint(fields=('doctype', 'field'), name='uniq_tab_singles_doctype_field'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user'], name='tabUser Per_user_2a047d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['allow', 'for_value'], name='tabUser Per_allow_03be37_idx'),
        ),
    ]
