# Generated by Django 5.0.14 on 2026-10-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='hide_descendants',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='is_default',
            field=models.SmallIntegerField(default=0),
        ),
    ]
