# Generated by Django 5.0.14 on 2026-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0002_userpermission_hide_descendants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='docstatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='home_page',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='role',
            name='idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='is_custom',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='role',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='role',
            name='restrict_to_domain',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='role',
            name='two_factor_auth',
            field=models.SmallIntegerField(default=0),
        ),
    ]
