# Generated by Django 5.0.14 on 2026-10-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0004_docfieldtable_doctypetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=180)),
                ('doctype', models.CharField(max_length=180)),
                ('data', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': '__UserSettings',
            },
        ),
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.UniqueConstraint(fields=('user', 'doctype'), name='uniq_user_settings_user_doctype'),
        ),
    ]
