# Generated by Django 5.0.14 on 2026-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0005_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='_assign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='_liked_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='_user_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
