# Generated by Django 5.0.14 on 2026-10-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0008_global_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=255)),
                ('fieldname', models.CharField(max_length=140)),
                ('password', models.TextField()),
                ('encrypted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': '__Auth',
            },
        ),
        migrations.AddConstraint(
            model_name='auth',
            constraint=models.UniqueConstraint(fields=('doctype', 'name', 'fieldname'), name='uniq_auth_doctype_name_field'),
        ),
    ]
