# Generated by Django 5.0.14 on 2026-10-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0009_auth_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='docperm',
            name='_assign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docperm',
            name='_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docperm',
            name='_liked_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docperm',
            name='_user_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docperm',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docperm',
            name='docstatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docperm',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docperm',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='docperm',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='_assign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='_liked_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='_user_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='docstatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='hasrole',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='_assign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='_liked_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='_user_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='docstatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='docperm',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='hasrole',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
