# Generated by Django 5.0.14 on 2026-10-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0010_standard_columns_for_permission_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfieldtable',
            name='alignment',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='allow_bulk_edit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='allow_in_quick_entry',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='button_color',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='documentation_url',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='hide_border',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='hide_days',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='hide_seconds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='ignore_versioning',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='ignore_xss_filter',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='in_filter',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='in_import_template',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='make_attachment_public',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='mask',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='max_height',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='not_nullable',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='oldfieldname',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='oldfieldtype',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='print_hide_if_no_value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='remember_last_selected_value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='show_dashboard',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='show_description_on_click',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='show_on_timeline',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='sort_options',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docfieldtable',
            name='sticky',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='allow_auto_repeat',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='allow_bulk_edit',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='allow_copy',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='allow_events_in_timeline',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='allow_guest_to_view',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='beta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='color',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='default_email_template',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='default_print_format',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='default_view',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='deprecated',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='documentation',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='email_append_to',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='force_re_route_to_default_view',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='grid_page_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='has_web_view',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='hide_toolbar',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='image_field',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='in_create',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='is_calendar_and_gantt',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='is_published_field',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='make_attachments_public',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='max_attachments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='migration_hash',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='protect_attached_files',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='queue_in_background',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='read_only',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='recipient_account_field',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='restrict_to_domain',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='route',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='row_format',
            field=models.CharField(blank=True, default='Dynamic', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='rows_threshold_for_grid_search',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='search_fields',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='sender_field',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='sender_name_field',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='show_name_in_global_search',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='show_preview_popup',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='show_title_field_in_link',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='subject_field',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='timeline_field',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='track_seen',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='track_views',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctypetable',
            name='translated_doctype',
            field=models.SmallIntegerField(default=0),
        ),
    ]
