# Generated by Django 5.0.14 on 2026-10-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frappe', '0011_doctype_docfield_standard_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('sid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sessiondata', models.TextField(blank=True, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=16, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Sessions',
                'db_table': 'tabSessions',
            },
        ),
    ]
