from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class CustomizeFormFieldGenerated(FrappeChildModel):
    doctype = 'Customize Form Field'
    label = models.CharField(max_length=255, blank=True, null=True, default='')
    fieldtype = models.CharField(max_length=140, blank=True, null=True, default='Data')
    fieldname = models.CharField(max_length=140, blank=True, null=True, default='')
    reqd = models.SmallIntegerField(default=0)
    unique = models.SmallIntegerField(default=0)
    is_virtual = models.SmallIntegerField(default=0)
    in_list_view = models.SmallIntegerField(default=0)
    in_standard_filter = models.SmallIntegerField(default=0)
    in_global_search = models.SmallIntegerField(default=0)
    bold = models.SmallIntegerField(default=0)
    translatable = models.SmallIntegerField(default=1)
    precision = models.CharField(max_length=140, blank=True, null=True, default='')
    length = models.IntegerField(null=True, blank=True)
    options = models.TextField(blank=True, null=True, default='')
    fetch_from = models.TextField(blank=True, null=True, default='')
    fetch_if_empty = models.SmallIntegerField(default=0)
    depends_on = models.TextField(blank=True, null=True, default='')
    permlevel = models.IntegerField(null=True, blank=True)
    hidden = models.SmallIntegerField(default=0)
    read_only = models.SmallIntegerField(default=0)
    collapsible = models.SmallIntegerField(default=0)
    allow_bulk_edit = models.SmallIntegerField(default=0)
    collapsible_depends_on = models.TextField(blank=True, null=True, default='')
    ignore_user_permissions = models.SmallIntegerField(default=0)
    allow_on_submit = models.SmallIntegerField(default=0)
    report_hide = models.SmallIntegerField(default=0)
    in_import_template = models.SmallIntegerField(default=0)
    remember_last_selected_value = models.SmallIntegerField(default=0)
    default = models.TextField(blank=True, null=True, default='')
    in_filter = models.SmallIntegerField(default=0)
    description = models.TextField(blank=True, null=True, default='')
    print_hide = models.SmallIntegerField(default=0)
    print_hide_if_no_value = models.SmallIntegerField(default=0)
    print_width = models.CharField(max_length=140, blank=True, null=True, default='')
    alignment = models.CharField(max_length=140, blank=True, null=True, default='')
    columns = models.IntegerField(null=True, blank=True)
    width = models.CharField(max_length=140, blank=True, null=True, default='')
    is_custom_field = models.SmallIntegerField(default=0)
    allow_in_quick_entry = models.SmallIntegerField(default=0)
    mandatory_depends_on = models.TextField(blank=True, null=True, default='')
    read_only_depends_on = models.TextField(blank=True, null=True, default='')
    in_preview = models.SmallIntegerField(default=0)
    hide_seconds = models.SmallIntegerField(default=0)
    hide_days = models.SmallIntegerField(default=0)
    hide_border = models.SmallIntegerField(default=0)
    non_negative = models.SmallIntegerField(default=0)
    min_value = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    max_value = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    show_dashboard = models.SmallIntegerField(default=0)
    no_copy = models.SmallIntegerField(default=0)
    ignore_versioning = models.SmallIntegerField(default=0)
    is_system_generated = models.SmallIntegerField(default=0)
    ignore_xss_filter = models.SmallIntegerField(default=0)
    sort_options = models.SmallIntegerField(default=0)
    link_filters = models.TextField(blank=True, null=True, default='')
    placeholder = models.CharField(max_length=140, blank=True, null=True, default='')
    button_color = models.CharField(max_length=140, blank=True, null=True, default='')
    mask = models.SmallIntegerField(default=0)
    set_only_once = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
