from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class PurchaseReceiptGenerated(FrappeModel):
    doctype = 'Purchase Receipt'
    title = models.CharField(max_length=140, blank=True, null=True, default='')
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_name = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_delivery_note = models.CharField(max_length=140, blank=True, null=True, default='')
    posting_date = models.DateField(null=True, blank=True)
    posting_time = FrappeTimeField(null=True, blank=True)
    set_posting_time = models.SmallIntegerField(default=0)
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    is_return = models.SmallIntegerField(default=0)
    return_against = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_address = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    address_display = models.TextField(blank=True, null=True, default='')
    contact_display = models.TextField(blank=True, null=True, default='')
    contact_mobile = models.TextField(blank=True, null=True, default='')
    contact_email = models.TextField(blank=True, null=True, default='')
    shipping_address = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_address_display = models.TextField(blank=True, null=True, default='')
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    buying_price_list = models.CharField(max_length=140, blank=True, null=True, default='')
    price_list_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    plc_conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ignore_pricing_rule = models.SmallIntegerField(default=0)
    set_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    is_subcontracted = models.SmallIntegerField(default=0)
    supplier_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    total_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_net_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    tax_category = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_rule = models.CharField(max_length=140, blank=True, null=True, default='')
    taxes_and_charges = models.CharField(max_length=140, blank=True, null=True, default='')
    other_charges_calculation = models.TextField(blank=True, null=True, default='')
    base_taxes_and_charges_added = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_taxes_and_charges_deducted = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    taxes_and_charges_added = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    taxes_and_charges_deducted = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    apply_discount_on = models.CharField(max_length=140, blank=True, null=True, default='Grand Total')
    base_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    base_rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    disable_rounded_total = models.SmallIntegerField(default=0)
    tc_name = models.CharField(max_length=140, blank=True, null=True, default='')
    terms = models.TextField(blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    range = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    per_billed = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    auto_repeat = models.CharField(max_length=140, blank=True, null=True, default='')
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    select_print_heading = models.CharField(max_length=140, blank=True, null=True, default='')
    language = models.CharField(max_length=140, blank=True, null=True, default='')
    group_same_items = models.SmallIntegerField(default=0)
    instructions = models.TextField(blank=True, null=True, default='')
    remarks = models.TextField(blank=True, null=True, default='')
    transporter_name = models.CharField(max_length=140, blank=True, null=True, default='')
    lr_no = models.CharField(max_length=140, blank=True, null=True, default='')
    lr_date = models.DateField(null=True, blank=True)
    is_internal_supplier = models.SmallIntegerField(default=0)
    inter_company_reference = models.CharField(max_length=140, blank=True, null=True, default='')
    scan_barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    billing_address = models.CharField(max_length=140, blank=True, null=True, default='')
    billing_address_display = models.TextField(blank=True, null=True, default='')
    apply_putaway_rule = models.SmallIntegerField(default=0)
    per_returned = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    set_from_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    represents_company = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    incoterm = models.CharField(max_length=140, blank=True, null=True, default='')
    named_place = models.CharField(max_length=140, blank=True, null=True, default='')
    subcontracting_receipt = models.CharField(max_length=140, blank=True, null=True, default='')
    dispatch_address = models.CharField(max_length=140, blank=True, null=True, default='')
    dispatch_address_display = models.TextField(blank=True, null=True, default='')
    last_scanned_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
