from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class SubcontractingReceiptItemGenerated(FrappeChildModel):
    doctype = 'Subcontracting Receipt Item'
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    received_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rejected_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_factor = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rm_cost_per_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    service_cost_per_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_cost_per_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    quality_inspection = models.CharField(max_length=140, blank=True, null=True, default='')
    subcontracting_order = models.CharField(max_length=140, blank=True, null=True, default='')
    schedule_date = models.DateField(null=True, blank=True)
    serial_no = models.TextField(blank=True, null=True, default='')
    batch_no = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_serial_no = models.TextField(blank=True, null=True, default='')
    subcontracting_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    bom = models.CharField(max_length=140, blank=True, null=True, default='')
    brand = models.CharField(max_length=140, blank=True, null=True, default='')
    rm_supp_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    manufacturer = models.CharField(max_length=140, blank=True, null=True, default='')
    manufacturer_part_no = models.CharField(max_length=140, blank=True, null=True, default='')
    subcontracting_receipt_item = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default=':Company')
    page_break = models.SmallIntegerField(default=0)
    returned_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    reference_name = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_order = models.CharField(max_length=140, blank=True, null=True, default='')
    include_exploded_items = models.SmallIntegerField(default=0)
    use_serial_batch_fields = models.SmallIntegerField(default=0)
    job_card = models.CharField(max_length=140, blank=True, null=True, default='')
    landed_cost_voucher_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    service_expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    secondary_item_type = models.CharField(max_length=140, blank=True, null=True, default='')
    secondary_items_cost_per_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    valuation_type = models.CharField(max_length=140, blank=True, null=True, default='')
    bom_secondary_item = models.CharField(max_length=140, blank=True, null=True, default='')
    process_loss_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)

    class Meta:
        abstract = True
