# Generated by Django 5.0.14 on 2026-09-27 08:19

import apps.core.assignable
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0002_seed_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMDashboard',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('layout', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CRM Dashboard',
                'db_table': 'crm_dashboard',
            },
        ),
        migrations.CreateModel(
            name='CRMExotelSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('record_call', models.BooleanField(default=False)),
                ('account_sid', models.CharField(blank=True, max_length=140)),
                ('subdomain', models.CharField(blank=True, max_length=140)),
                ('api_key', models.CharField(blank=True, max_length=140)),
                ('api_token', models.CharField(blank=True, max_length=140)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'verbose_name': 'CRM Exotel Settings',
                'db_table': 'crm_exotel_settings',
            },
        ),
        migrations.CreateModel(
            name='CRMTelephonyAgent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='telephony_agent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_no', models.CharField(blank=True, editable=False, max_length=30)),
                ('twilio_number', models.CharField(blank=True, max_length=30)),
                ('exotel_number', models.CharField(blank=True, max_length=30)),
                ('default_medium', models.CharField(blank=True, choices=[('', ''), ('Twilio', 'Twilio'), ('Exotel', 'Exotel')], max_length=10)),
                ('call_receiving_device', models.CharField(choices=[('Computer', 'Computer'), ('Phone', 'Phone')], default='Computer', max_length=10)),
            ],
            options={
                'verbose_name': 'CRM Telephony Agent',
                'db_table': 'crm_telephony_agent',
            },
        ),
        migrations.CreateModel(
            name='CRMTwilioSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('record_calls', models.BooleanField(default=False)),
                ('account_sid', models.CharField(blank=True, max_length=140)),
                ('auth_token', models.CharField(blank=True, max_length=140)),
                ('api_key', models.CharField(blank=True, max_length=140)),
                ('api_secret', models.CharField(blank=True, max_length=140)),
                ('twiml_sid', models.CharField(blank=True, max_length=140)),
                ('app_name', models.CharField(blank=True, max_length=140)),
                ('twilio_apps', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'verbose_name': 'CRM Twilio Settings',
                'db_table': 'crm_twilio_settings',
            },
        ),
        migrations.AddField(
            model_name='crmterritory',
            name='old_parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmterritory'),
        ),
        migrations.CreateModel(
            name='CRMCallLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('telephony_medium', models.CharField(blank=True, choices=[('', ''), ('Manual', 'Manual'), ('Twilio', 'Twilio'), ('Exotel', 'Exotel')], max_length=10)),
                ('from_number', models.CharField(db_column='from_number', max_length=30)),
                ('to_number', models.CharField(db_column='to_number', max_length=30)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Ringing', 'Ringing'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Busy', 'Busy'), ('No Answer', 'No Answer'), ('Queued', 'Queued'), ('Canceled', 'Canceled')], max_length=15)),
                ('type', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=10)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('medium', models.CharField(blank=True, max_length=140)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.TextField(blank=True)),
                ('reference_doctype', models.CharField(blank=True, default='CRM Lead', max_length=140)),
                ('reference_docname', models.CharField(blank=True, max_length=140)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Call Log',
                'db_table': 'crm_call_log',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='CallLogLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('link_doctype', models.CharField(max_length=140)),
                ('link_name', models.CharField(max_length=140)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crm.crmcalllog')),
            ],
            options={
                'verbose_name': 'Call Log Link',
                'db_table': 'crm_call_log_link',
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='CRMTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Backlog', 'Backlog'), ('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Canceled', 'Canceled')], max_length=15)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('reference_doctype', models.CharField(blank=True, max_length=140)),
                ('reference_docname', models.CharField(blank=True, max_length=140)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Task',
                'db_table': 'crm_task',
                'ordering': ['-modified'],
            },
            bases=(apps.core.assignable.AssignableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FCRMNote',
            fields=[
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField(blank=True)),
                ('reference_doctype', models.CharField(blank=True, default='CRM Lead', max_length=140)),
                ('reference_docname', models.CharField(blank=True, max_length=140)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCRM Note',
                'db_table': 'fcrm_note',
                'ordering': ['-modified'],
            },
        ),
        migrations.AddField(
            model_name='crmcalllog',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.fcrmnote'),
        ),
    ]
