# Generated by Django 5.0.14 on 2026-09-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_crmdashboard_crmexotelsettings_crmtelephonyagent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMEnrichmentFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('source_key', models.CharField(choices=[('company_name', 'company_name'), ('description', 'description'), ('logo', 'logo'), ('industry', 'industry'), ('primary_email', 'primary_email'), ('primary_phone', 'primary_phone'), ('secondary_phone', 'secondary_phone'), ('linkedin', 'linkedin'), ('twitter', 'twitter'), ('github', 'github'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube')], max_length=20)),
                ('target_doctype', models.CharField(max_length=140)),
                ('target_fieldname', models.CharField(max_length=140)),
                ('write_policy', models.CharField(choices=[('Fill if empty', 'Fill if empty'), ('Always refresh', 'Always refresh'), ('Override defaults', 'Override defaults')], default='Fill if empty', max_length=20)),
                ('create_missing_link', models.BooleanField(default=False)),
                ('default_values', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CRM Enrichment Field Mapping',
                'db_table': 'crm_enrichment_field_mapping',
            },
        ),
        migrations.CreateModel(
            name='CRMEnrichmentRun',
            fields=[
                ('name', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('reference_doctype', models.CharField(blank=True, max_length=140)),
                ('reference_name', models.CharField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=10)),
                ('source_website', models.CharField(blank=True, max_length=255)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=140)),
                ('industry_confidence', models.FloatField(default=0)),
                ('emails_found', models.IntegerField(default=0)),
                ('phones_found', models.IntegerField(default=0)),
                ('social_profiles', models.TextField(blank=True)),
                ('raw_json', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRM Enrichment Run',
                'db_table': 'crm_enrichment_run',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='CRMEnrichmentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_enrich', models.BooleanField(default=False)),
                ('max_pages', models.IntegerField(default=10)),
                ('max_depth', models.IntegerField(default=2)),
                ('use_sitemap', models.BooleanField(default=True)),
                ('request_timeout', models.IntegerField(default=10)),
                ('max_download_bytes', models.IntegerField(default=3000000)),
                ('retry_count', models.IntegerField(default=2)),
                ('user_agent', models.CharField(default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36', max_length=255)),
            ],
            options={
                'verbose_name': 'CRM Enrichment Settings',
                'db_table': 'crm_enrichment_settings',
            },
        ),
        migrations.CreateModel(
            name='CRMEnrichmentRule',
            fields=[
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=140, unique=True)),
                ('rule_type', models.CharField(choices=[('Industry', 'Industry'), ('Social', 'Social')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('target_value', models.CharField(blank=True, max_length=140)),
                ('weight', models.FloatField(default=1)),
                ('match_scope', models.CharField(choices=[('Headline', 'Headline'), ('Full Text', 'Full Text'), ('HTML', 'HTML'), ('Headers', 'Headers'), ('URL', 'URL')], default='Full Text', max_length=10)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmindustry')),
            ],
            options={
                'verbose_name': 'CRM Enrichment Rule',
                'db_table': 'crm_enrichment_rule',
            },
        ),
        migrations.CreateModel(
            name='CRMEnrichmentRulePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('pattern', models.CharField(max_length=255)),
                ('is_regex', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='crm.crmenrichmentrule')),
            ],
            options={
                'verbose_name': 'CRM Enrichment Rule Pattern',
                'db_table': 'crm_enrichment_rule_pattern',
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='CRMEnrichmentLinkPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('keyword', models.CharField(max_length=140)),
                ('weight', models.FloatField(default=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_priority_order', to='crm.crmenrichmentsettings')),
            ],
            options={
                'verbose_name': 'CRM Enrichment Link Priority',
                'db_table': 'crm_enrichment_link_priority',
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='CRMEnrichmentDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('allowed', 'allowed'), ('blocked', 'blocked')], max_length=10)),
                ('idx', models.PositiveIntegerField(default=0)),
                ('domain', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='crm.crmenrichmentsettings')),
            ],
            options={
                'verbose_name': 'CRM Enrichment Domain',
                'db_table': 'crm_enrichment_domain',
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='CRMEnrichmentSkipPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField(default=0)),
                ('pattern', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_patterns', to='crm.crmenrichmentsettings')),
            ],
            options={
                'verbose_name': 'CRM Enrichment Skip Pattern',
                'db_table': 'crm_enrichment_skip_pattern',
                'ordering': ['idx'],
            },
        ),
    ]
