# Generated by Django 5.0.14 on 2026-09-27 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_seed_enrichment_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMFormScript',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('dt', models.CharField(max_length=140)),
                ('view', models.CharField(choices=[('Form', 'Form'), ('List', 'List')], default='Form', max_length=10)),
                ('enabled', models.BooleanField(default=False)),
                ('is_standard', models.BooleanField(default=False)),
                ('script', models.TextField(blank=True, default='function setupForm({ doc }) {\n    return {\n        actions: [],\n    }\n}')),
            ],
            options={
                'verbose_name': 'CRM Form Script',
                'db_table': 'crm_form_script',
            },
        ),
        migrations.CreateModel(
            name='CRMGlobalSettings',
            fields=[
                ('name', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('dt', models.CharField(max_length=140)),
                ('type', models.CharField(choices=[('Quick Filters', 'Quick Filters'), ('Sidebar Items', 'Sidebar Items')], max_length=20)),
                ('json', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CRM Global Settings',
                'db_table': 'crm_global_settings',
            },
        ),
        migrations.CreateModel(
            name='CRMViewSettings',
            fields=[
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=140)),
                ('icon', models.CharField(blank=True, max_length=140)),
                ('is_standard', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('list', 'list'), ('group_by', 'group_by'), ('kanban', 'kanban')], default='list', max_length=10)),
                ('dt', models.CharField(max_length=140)),
                ('route_name', models.CharField(blank=True, max_length=140)),
                ('pinned', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('filters', models.TextField(blank=True)),
                ('order_by', models.CharField(blank=True, max_length=255)),
                ('load_default_columns', models.BooleanField(default=False)),
                ('columns', models.TextField(blank=True)),
                ('rows', models.TextField(blank=True)),
                ('group_by_field', models.CharField(blank=True, max_length=140)),
                ('column_field', models.CharField(blank=True, max_length=140)),
                ('title_field', models.CharField(blank=True, max_length=140)),
                ('kanban_columns', models.TextField(blank=True)),
                ('kanban_fields', models.TextField(blank=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM View Settings',
                'db_table': 'crm_view_settings',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='QuickFilterOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype_label', models.CharField(max_length=140)),
                ('fieldname', models.CharField(max_length=140)),
                ('in_standard_filter', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quick Filter Override',
                'db_table': 'crm_quick_filter_override',
                'unique_together': {('doctype_label', 'fieldname')},
            },
        ),
    ]
