# Generated by Django 5.0.14 on 2026-09-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_seed_quick_filter_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcrmsettings',
            name='brand_logo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fcrmsettings',
            name='brand_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='fcrmsettings',
            name='favicon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
