# Generated by Django 5.0.14 on 2026-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_fcrmsettings_brand_logo_fcrmsettings_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMFieldsLayout',
            fields=[
                ('name', models.CharField(editable=False, max_length=140, primary_key=True, serialize=False)),
                ('dt', models.CharField(max_length=140)),
                ('type', models.CharField(choices=[('Quick Entry', 'Quick Entry'), ('Side Panel', 'Side Panel'), ('Data Fields', 'Data Fields'), ('Grid Row', 'Grid Row'), ('Required Fields', 'Required Fields')], max_length=20)),
                ('layout', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CRM Fields Layout',
                'db_table': 'crm_fields_layout',
                'unique_together': {('dt', 'type')},
            },
        ),
    ]
