# Generated by Django 5.0.14 on 2026-09-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment'),
        ('crm', '0013_seed_form_scripts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mention', 'Mention'), ('Task', 'Task'), ('Assignment', 'Assignment'), ('WhatsApp', 'WhatsApp'), ('Automation', 'Automation')], default='Mention', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('reference_doctype', models.CharField(blank=True, max_length=140)),
                ('reference_name', models.CharField(blank=True, max_length=140)),
                ('notification_type_doctype', models.CharField(blank=True, max_length=140)),
                ('notification_type_doc', models.CharField(blank=True, max_length=140)),
                ('notification_text', models.TextField(blank=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.comment')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Notification',
                'db_table': 'crm_notification',
                'ordering': ['-creation'],
            },
        ),
    ]
