# Generated by Django 5.0.14 on 2026-09-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # See core/0005's comment -- RunSQL UPDATE then AlterField on the same
    # table needs separate transactions on Postgres.
    atomic = False

    dependencies = [
        ('core', '0005_address_gender_salutation_alter_user_options_and_more'),
        ('crm', '0018_seed_salutation_gender_address'),
    ]

    operations = [
        # Same '' -> NULL cleanup as core/0005, for the CharField-to-Link
        # columns on CRM Deal/CRM Organization.
        migrations.RunSQL(
            "ALTER TABLE crm_deal ALTER COLUMN gender DROP NOT NULL; "
            "ALTER TABLE crm_deal ALTER COLUMN salutation DROP NOT NULL; "
            "ALTER TABLE crm_organization ALTER COLUMN address DROP NOT NULL; "
            "UPDATE crm_deal SET gender = NULL WHERE gender = ''; "
            "UPDATE crm_deal SET salutation = NULL WHERE salutation = ''; "
            "UPDATE crm_organization SET address = NULL WHERE address = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.gender'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salutation'),
        ),
        migrations.AlterField(
            model_name='crmorganization',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.address'),
        ),
    ]
