# Generated by Django 5.0.14 on 2026-09-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # See core/0005's comment -- RunSQL UPDATE then AlterField on the same
    # table needs separate transactions on Postgres.
    atomic = False

    dependencies = [
        ('core', '0005_address_gender_salutation_alter_user_options_and_more'),
        ('crm', '0019_alter_crmdeal_gender_alter_crmdeal_salutation_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE crm_lead ALTER COLUMN gender DROP NOT NULL; "
            "ALTER TABLE crm_lead ALTER COLUMN salutation DROP NOT NULL; "
            "UPDATE crm_lead SET gender = NULL WHERE gender = ''; "
            "UPDATE crm_lead SET salutation = NULL WHERE salutation = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.gender'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salutation'),
        ),
    ]
