# Generated by Django 5.0.14 on 2026-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_seed_address_quick_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcrmsettings',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        # Reset the one already-seeded row's wrongly-auto-defaulted "USD"
        # back to unset, matching the real doctype's blank-by-default field --
        # otherwise the Dashboard settings' currency picker would stay
        # permanently locked to read-only text for every existing install.
        migrations.RunSQL(
            "UPDATE fcrm_settings SET currency = '' WHERE id = 1 AND currency = 'USD';",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
