# Generated by Django 5.0.14 on 2026-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_crmdropdownitem_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmservicelevelagreement',
            name='condition_json',
            field=models.TextField(blank=True),
        ),
    ]
