# Generated by Django 5.0.14 on 2026-10-04 16:27

import django.db.models.deletion
from apps.core.migration_utils import tolerant_extra_columns
from django.db import migrations, models

@tolerant_extra_columns
def copy_lookups(apps, schema_editor):
    from apps.core.crm_custom_fields import CRM_CUSTOM_FIELDS

    CustomField = apps.get_model("erpnext", "CustomField")
    for field in CRM_CUSTOM_FIELDS["Opportunity Lost Reason"]:
        name = f"Opportunity Lost Reason-{field['fieldname']}"
        if not CustomField.objects.filter(pk=name).exists():
            CustomField.objects.create(
                name=name, dt="Opportunity Lost Reason", fieldname=field["fieldname"], fieldtype=field["fieldtype"],
                label=field["label"], insert_after=field.get("insert_after"), is_system_generated=1,
                owner="Administrator", modified_by="Administrator",
            )

    User = apps.get_model("core", "User")
    emails = dict(User.objects.values_list("pk", "email"))

    Industry = apps.get_model("erpnext", "IndustryType")
    for row in apps.get_model("crm", "CRMIndustry").objects.all():
        Industry.objects.get_or_create(
            pk=row.name, defaults={"industry": row.name, "owner": "Administrator", "modified_by": "Administrator"}
        )

    Source = apps.get_model("erpnext", "UtmSource")
    for row in apps.get_model("crm", "CRMLeadSource").objects.all():
        Source.objects.get_or_create(
            pk=row.name,
            defaults={"description": row.details, "slug": row.name, "owner": "Administrator", "modified_by": "Administrator"},
        )

    Reason = apps.get_model("erpnext", "OpportunityLostReason")
    for row in apps.get_model("crm", "CRMLostReason").objects.all():
        Reason.objects.get_or_create(
            pk=row.name,
            defaults={"lost_reason": row.name, "owner": "Administrator", "modified_by": "Administrator"},
        )

    Territory = apps.get_model("erpnext", "Territory")
    root = Territory.objects.filter(pk="All Territories").first()
    for row in apps.get_model("crm", "CRMTerritory").objects.all().order_by("lft"):
        if Territory.objects.filter(pk=row.name).exists():
            continue
        Territory.objects.create(
            pk=row.name,
            territory_name=row.name,
            is_group=1 if row.is_group else 0,
            parent_territory=row.parent_crm_territory_id or (root.pk if root else ""),
            territory_manager=emails.get(row.territory_manager_id) or "",
            owner="Administrator",
            modified_by="Administrator",
        )
    from apps.frappe.utils.nestedset import rebuild_tree

    rebuild_tree("Territory")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_unify_contact'),
        ('erpnext', '0030_unify_lookups'),
    ]

    operations = [
        migrations.RunPython(copy_lookups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='crmlead',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.industrytype'),
        ),
        migrations.AlterField(
            model_name='crmorganization',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.industrytype'),
        ),
        migrations.AlterField(
            model_name='crmenrichmentrule',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.industrytype'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.industrytype'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.utmsource'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.utmsource'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.opportunitylostreason'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.opportunitylostreason'),
        ),
        migrations.RemoveField(
            model_name='crmterritory',
            name='old_parent',
        ),
        migrations.RemoveField(
            model_name='crmterritory',
            name='parent_crm_territory',
        ),
        migrations.RemoveField(
            model_name='crmterritory',
            name='territory_manager',
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.territory'),
        ),
        migrations.AlterField(
            model_name='crmorganization',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.territory'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.territory'),
        ),
        migrations.DeleteModel(
            name='CRMIndustry',
        ),
        migrations.DeleteModel(
            name='CRMLeadSource',
        ),
        migrations.DeleteModel(
            name='CRMLostReason',
        ),
        migrations.DeleteModel(
            name='CRMTerritory',
        ),
    ]
