# Generated by Django 5.0.14 on 2026-10-04 22:06

import django.db.models.deletion
from apps.core.migration_utils import tolerant_extra_columns
from django.db import migrations, models

@tolerant_extra_columns
def copy_lookups(apps, schema_editor):
    Gender = apps.get_model("erpnext", "Gender")
    Salutation = apps.get_model("erpnext", "Salutation")
    for row in apps.get_model("core", "Gender").objects.all():
        Gender.objects.get_or_create(
            pk=row.name, defaults={"gender": row.name, "owner": "Administrator", "modified_by": "Administrator"}
        )
    for row in apps.get_model("core", "Salutation").objects.all():
        Salutation.objects.get_or_create(
            pk=row.name, defaults={"salutation": row.name, "owner": "Administrator", "modified_by": "Administrator"}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_unify_lookups'),
        ('erpnext', '0033_gender_salutation'),
    ]

    operations = [
        migrations.RunPython(copy_lookups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='crmdeal',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.gender'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.salutation'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.gender'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erpnext.salutation'),
        ),
    ]
