from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class PurchaseReceiptItemGenerated(FrappeChildModel):
    doctype = 'Purchase Receipt Item'
    barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_part_no = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    received_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rejected_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    uom = models.CharField(max_length=140, blank=True, null=True, default='')
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_factor = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    retain_sample = models.SmallIntegerField(default=0)
    sample_quantity = models.IntegerField(null=True, blank=True)
    price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    pricing_rules = models.TextField(blank=True, null=True, default='')
    is_free_item = models.SmallIntegerField(default=0)
    net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_per_unit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    quality_inspection = models.CharField(max_length=140, blank=True, null=True, default='')
    is_fixed_asset = models.SmallIntegerField(default=0)
    purchase_order = models.CharField(max_length=140, blank=True, null=True, default='')
    schedule_date = models.DateField(null=True, blank=True)
    stock_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    item_tax_template = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default=':Company')
    purchase_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    allow_zero_valuation_rate = models.SmallIntegerField(default=0)
    billed_amt = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    closed = models.SmallIntegerField(default=0)
    landed_cost_voucher_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    brand = models.CharField(max_length=140, blank=True, null=True, default='')
    item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    rm_supp_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    item_tax_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    valuation_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    item_tax_rate = models.TextField(blank=True, null=True, default='')
    page_break = models.SmallIntegerField(default=0)
    material_request = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request_item = models.CharField(max_length=140, blank=True, null=True, default='')
    expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    manufacturer = models.CharField(max_length=140, blank=True, null=True, default='')
    manufacturer_part_no = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_location = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_category = models.CharField(max_length=140, blank=True, null=True, default='')
    from_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_receipt_item = models.CharField(max_length=140, blank=True, null=True, default='')
    putaway_rule = models.CharField(max_length=140, blank=True, null=True, default='')
    returned_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    received_stock_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    delivery_note_item = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_type = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_rate_or_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    purchase_invoice = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_invoice_item = models.CharField(max_length=140, blank=True, null=True, default='')
    product_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    provisional_expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    has_item_scanned = models.SmallIntegerField(default=0)
    serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    serial_no = models.TextField(blank=True, null=True, default='')
    rejected_serial_no = models.TextField(blank=True, null=True, default='')
    batch_no = models.CharField(max_length=140, blank=True, null=True, default='')
    rejected_serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    wip_composite_asset = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_order = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_order_item = models.CharField(max_length=140, blank=True, null=True, default='')
    subcontracting_receipt_item = models.CharField(max_length=140, blank=True, null=True, default='')
    use_serial_batch_fields = models.SmallIntegerField(default=0)
    return_qty_from_rejected_warehouse = models.SmallIntegerField(default=0)
    sales_incoming_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    distributed_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount_difference_with_purchase_invoice = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)

    class Meta:
        abstract = True
