from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class SupplierQuotationItemGenerated(FrappeChildModel):
    doctype = 'Supplier Quotation Item'
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_part_no = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    lead_time_days = models.IntegerField(null=True, blank=True)
    description = models.TextField(blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    uom = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_factor = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ordered_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_price_list_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    pricing_rules = models.TextField(blank=True, null=True, default='')
    net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_per_unit = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    weight_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    prevdoc_doctype = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_order = models.CharField(max_length=140, blank=True, null=True, default='')
    request_for_quotation = models.CharField(max_length=140, blank=True, null=True, default='')
    item_tax_template = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request_item = models.CharField(max_length=140, blank=True, null=True, default='')
    request_for_quotation_item = models.CharField(max_length=140, blank=True, null=True, default='')
    brand = models.CharField(max_length=140, blank=True, null=True, default='')
    item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    item_tax_rate = models.TextField(blank=True, null=True, default='')
    page_break = models.SmallIntegerField(default=0)
    manufacturer = models.CharField(max_length=140, blank=True, null=True, default='')
    manufacturer_part_no = models.CharField(max_length=140, blank=True, null=True, default='')
    is_free_item = models.SmallIntegerField(default=0)
    expected_delivery_date = models.DateField(null=True, blank=True)
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    distributed_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    margin_type = models.CharField(max_length=140, blank=True, null=True, default='')
    margin_rate_or_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rate_with_margin = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)

    class Meta:
        abstract = True
