from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class SalesOrderGenerated(FrappeModel):
    doctype = 'Sales Order'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    customer = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_name = models.CharField(max_length=140, blank=True, null=True, default='')
    order_type = models.CharField(max_length=140, blank=True, null=True, default='Sales')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    transaction_date = models.DateField(null=True, blank=True)
    delivery_date = models.DateField(null=True, blank=True)
    po_no = models.CharField(max_length=140, blank=True, null=True, default='')
    po_date = models.DateField(null=True, blank=True)
    tax_id = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_address = models.CharField(max_length=140, blank=True, null=True, default='')
    address_display = models.TextField(blank=True, null=True, default='')
    contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_display = models.TextField(blank=True, null=True, default='')
    contact_mobile = models.TextField(blank=True, null=True, default='')
    contact_email = models.CharField(max_length=140, blank=True, null=True, default='')
    company_address_display = models.TextField(blank=True, null=True, default='')
    company_address = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_address_name = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_address = models.TextField(blank=True, null=True, default='')
    shipping_contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_contact_display = models.TextField(blank=True, null=True, default='')
    shipping_contact_mobile = models.TextField(blank=True, null=True, default='')
    shipping_contact_email = models.CharField(max_length=140, blank=True, null=True, default='')
    customer_group = models.CharField(max_length=140, blank=True, null=True, default='')
    territory = models.CharField(max_length=140, blank=True, null=True, default='')
    currency = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    selling_price_list = models.CharField(max_length=140, blank=True, null=True, default='')
    price_list_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    plc_conversion_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    ignore_pricing_rule = models.SmallIntegerField(default=0)
    set_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    scan_barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    total_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    net_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_net_weight = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    tax_category = models.CharField(max_length=140, blank=True, null=True, default='')
    shipping_rule = models.CharField(max_length=140, blank=True, null=True, default='')
    taxes_and_charges = models.CharField(max_length=140, blank=True, null=True, default='')
    other_charges_calculation = models.TextField(blank=True, null=True, default='')
    base_total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_taxes_and_charges = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    loyalty_points = models.IntegerField(null=True, blank=True)
    loyalty_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    coupon_code = models.CharField(max_length=140, blank=True, null=True, default='')
    apply_discount_on = models.CharField(max_length=140, blank=True, null=True, default='Grand Total')
    base_discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_discount_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    discount_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    base_in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    grand_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounding_adjustment = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    rounded_total = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    in_words = models.CharField(max_length=240, blank=True, null=True, default='')
    advance_paid = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    payment_terms_template = models.CharField(max_length=140, blank=True, null=True, default='')
    tc_name = models.CharField(max_length=140, blank=True, null=True, default='')
    terms = models.TextField(blank=True, null=True, default='')
    inter_company_order_reference = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    party_account_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    language = models.CharField(max_length=140, blank=True, null=True, default='')
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    select_print_heading = models.CharField(max_length=140, blank=True, null=True, default='')
    group_same_items = models.SmallIntegerField(default=0)
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    delivery_status = models.CharField(max_length=140, blank=True, null=True, default='')
    per_delivered = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    per_billed = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    billing_status = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_partner = models.CharField(max_length=140, blank=True, null=True, default='')
    commission_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_commission = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)
    auto_repeat = models.CharField(max_length=140, blank=True, null=True, default='')
    contact_phone = models.CharField(max_length=140, blank=True, null=True, default='')
    is_internal_customer = models.SmallIntegerField(default=0)
    represents_company = models.CharField(max_length=140, blank=True, null=True, default='')
    disable_rounded_total = models.SmallIntegerField(default=0)
    dispatch_address_name = models.CharField(max_length=140, blank=True, null=True, default='')
    dispatch_address = models.TextField(blank=True, null=True, default='')
    amount_eligible_for_commission = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    per_picked = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    incoterm = models.CharField(max_length=140, blank=True, null=True, default='')
    named_place = models.CharField(max_length=140, blank=True, null=True, default='')
    reserve_stock = models.SmallIntegerField(default=0)
    advance_payment_status = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_medium = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_content = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_source = models.CharField(max_length=140, blank=True, null=True, default='')
    utm_campaign = models.CharField(max_length=140, blank=True, null=True, default='')
    company_contact_person = models.CharField(max_length=140, blank=True, null=True, default='')
    skip_delivery_note = models.SmallIntegerField(default=0)
    has_unit_price_items = models.SmallIntegerField(default=0)
    last_scanned_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    is_subcontracted = models.SmallIntegerField(default=0)
    transaction_time = models.TimeField(null=True, blank=True)
    ignore_default_payment_terms_template = models.SmallIntegerField(default=0)
    title = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
