from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class LeaseAgreementGenerated(FrappeModel):
    doctype = 'Lease Agreement'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='LSE-.YYYY.-.#####')
    customer = models.CharField(max_length=140, blank=True, null=True, default='')
    tenant_name = models.CharField(max_length=140, blank=True, null=True, default='')
    trading_name = models.CharField(max_length=140, blank=True, null=True, default='')
    lease_type = models.CharField(max_length=140, blank=True, null=True, default='New')
    renewal_of = models.CharField(max_length=140, blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    property = models.CharField(max_length=140, blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    lease_term_months = models.IntegerField(null=True, blank=True)
    rent_free_months = models.IntegerField(null=True, blank=True)
    rent_start_date = models.DateField(null=True, blank=True)
    notice_period_days = models.IntegerField(null=True, blank=True)
    auto_renew = models.SmallIntegerField(default=0)
    total_area = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_monthly_rent = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_monthly_service_charge = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    billing_frequency = models.CharField(max_length=140, blank=True, null=True, default='Monthly')
    billing_day = models.IntegerField(null=True, blank=True)
    payment_terms_days = models.IntegerField(null=True, blank=True)
    auto_invoice = models.SmallIntegerField(default=1)
    tax_template = models.CharField(max_length=140, blank=True, null=True, default='')
    next_billing_date = models.DateField(null=True, blank=True)
    last_billed_to = models.DateField(null=True, blank=True)
    escalation_type = models.CharField(max_length=140, blank=True, null=True, default='Percentage')
    escalation_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    escalation_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    escalation_months = models.IntegerField(null=True, blank=True)
    turnover_rent_applicable = models.SmallIntegerField(default=0)
    turnover_rent_percent = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    security_deposit_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    deposit_received = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    deposit_balance = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_billed = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_paid = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    outstanding_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    overdue_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    terms_template = models.CharField(max_length=140, blank=True, null=True, default='')
    terms = models.TextField(blank=True, null=True, default='')
    landlord_signatory = models.CharField(max_length=140, blank=True, null=True, default='')
    landlord_signature = models.TextField(blank=True, null=True, default='')
    landlord_signed_on = FrappeDateTimeField(null=True, blank=True)
    tenant_signatory_name = models.CharField(max_length=140, blank=True, null=True, default='')
    tenant_signature = models.TextField(blank=True, null=True, default='')
    tenant_signed_on = FrappeDateTimeField(null=True, blank=True)
    signed_copy = models.TextField(blank=True, null=True, default='')
    termination_date = models.DateField(null=True, blank=True)
    termination_type = models.CharField(max_length=140, blank=True, null=True, default='')
    termination_reason = models.TextField(blank=True, null=True, default='')

    class Meta:
        abstract = True
