import { get, post, type ModuleEndpoints } from '@/core/api/endpointRegistry'

export const crmEndpoints: ModuleEndpoints = {
  doctypes: {
    'CRM Lead': 'crm/leads',
    'CRM Deal': 'crm/deals',
    'CRM Task': 'crm/tasks',
    'FCRM Note': 'crm/notes',
    'CRM Call Log': 'crm/call-logs',
    'CRM Lead Status': 'crm/lead-statuses',
    'CRM Deal Status': 'crm/deal-statuses',
    'CRM Communication Status': 'crm/communication-statuses',
    Comment: 'crm/comments',
    'CRM Form Script': 'crm/form-scripts',
    Salutation: 'crm/salutations',
    Gender: 'crm/genders',
    Address: 'crm/addresses',
    Contact: 'crm/contacts',
    'CRM Organization': 'crm/organizations',
    User: 'crm/users',
    'Assignment Rule': 'crm/assignment-rules',
    'CRM Service Level Agreement': 'crm/sla-policies',
    'CRM Holiday List': 'crm/holiday-lists',
    'Automation Flow': 'crm/automation-flows',
    'Background Task': 'crm/background-tasks',
    'Data Import': 'crm/data-imports',
    'CRM Invitation': 'crm/invitations',
    'Email Account': 'crm/email-accounts',
    'CRM Sales Hierarchy': 'crm/sales-hierarchy',
    'Lead Sync Source': 'crm/lead-sync-sources',
    'Facebook Page': 'crm/facebook-pages',
    'Facebook Lead Form': 'crm/facebook-lead-forms',
    'Failed Lead Sync Log': 'crm/failed-lead-sync-logs',
    'CRM Telephony Agent': 'crm/telephony-agents',
    'Email Template': 'crm/email-templates',
  },
  methods: {
    'crm.api.form.list_forms': get('/api/crm/forms/'),
    'crm.api.form.get_form_config': get('/api/crm/forms/config/'),
    'crm.api.form.save_form': post('/api/crm/forms/save/'),
    'crm.api.form.set_published': post('/api/crm/forms/publish/'),
    'crm.api.form.delete_form': post('/api/crm/forms/delete/'),
    'crm.api.form.get_form_fields': get('/api/crm/form-fields/'),
    'crm.api.form.get_hidden_seed': get('/api/crm/form-hidden-seed/'),
    'crm.api.form.link_field_guest_access': post('/api/crm/form-link-guest-access/'),
    'crm.api.form.grant_guest_link_access': post('/api/crm/form-grant-guest-access/'),
    'crm.integrations.twilio.fetch_applications': post('/api/crm/integrations/twilio/fetch-applications/'),
    'crm.api.user.update_user_role': post('/api/crm/user-management/update-role/'),
    'crm.api.user.remove_crm_roles_from_user': post('/api/crm/user-management/remove/'),
    'crm.api.user.add_existing_users': post('/api/crm/user-management/add-existing/'),
    'crm.api.invite_by_email': post('/api/crm/user-management/invite/'),
    'frappe.core.doctype.data_import.data_import.get_preview_from_template': get('/api/crm/data-imports/preview/'),
    'frappe.core.doctype.data_import.data_import.form_start_import': post('/api/crm/data-imports/start/'),
    'frappe.core.doctype.data_import.data_import.get_import_logs': get('/api/crm/data-imports/logs/'),
    'crm.api.doc.get_data': post('/api/crm/doc/get-data/'),
    'frappe.automation_engine.api.get_automation_capabilities': get('/api/crm/automation-capabilities/'),
    'frappe.automation_engine.api.validate_action_params': post('/api/crm/automation-validate-params/'),
    'frappe.automation_engine.api.get_param_options': post('/api/crm/automation-param-options/'),
    'frappe.automation_engine.api.run_manually': post('/api/crm/automation-run-manually/'),
    'frappe.automation_engine.api.trial_run': post('/api/crm/automation-trial-run/'),
    'frappe.automation_engine.api.get_runs': get('/api/crm/automation-runs/'),
    'frappe.client.rename_doc': post('/api/crm/doc/rename/'),
    'crm.api.doc.sort_options': get('/api/crm/doc/sort-options/'),
    'crm.api.doc.get_filterable_fields': get('/api/crm/doc/filterable-fields/'),
    'crm.api.doc.get_group_by_fields': get('/api/crm/doc/group-by-fields/'),
    'crm.api.doc.get_quick_filters': get('/api/crm/doc/quick-filters/'),
    'crm.api.doc.update_quick_filters': post('/api/crm/doc/quick-filters/update/'),
    'crm.api.doc.get_assigned_users': get('/api/crm/doc/assigned-users/'),
    'crm.api.doc.add_seen': post('/api/crm/doc/add-seen/'),
    'crm.api.doc.get_fields': get('/api/crm/doc/fields/'),
    'crm.fcrm.doctype.crm_view_settings.crm_view_settings.create': post('/api/crm/views/create/'),
    'crm.fcrm.doctype.crm_view_settings.crm_view_settings.update': post('/api/crm/views/update/'),
    'crm.fcrm.doctype.crm_view_settings.crm_view_settings.delete': post('/api/crm/views/delete/'),
    'crm.fcrm.doctype.crm_view_settings.crm_view_settings.public': post('/api/crm/views/public/'),
    'crm.fcrm.doctype.crm_view_settings.crm_view_settings.pin': post('/api/crm/views/pin/'),
    'crm.fcrm.doctype.crm_view_settings.crm_view_settings.create_or_update_standard_view':
      post('/api/crm/views/standard/'),
    'crm.fcrm.doctype.crm_view_settings.crm_view_settings.set_as_default': post('/api/crm/views/set-default/'),
    'crm.fcrm.doctype.crm_view_settings.crm_view_settings.fetch_and_update_kanban_columns': post(
      '/api/crm/views/kanban-columns/',
    ),
    'frappe.desk.like.toggle_like': post('/api/crm/doc/toggle-like/'),
    'crm.api.session.get_users': get('/api/crm/session/users/'),
    'crm.api.session.get_user_info': post('/api/crm/session/user-info/'),
    'crm.api.session.get_organizations': get('/api/crm/session/organizations/'),
    'crm.www.crm.get_context_for_dev': get('/api/crm/session/boot/'),
    'crm.api.views.get_views': get('/api/crm/doc/views/'),
    'frappe.desk.search.search_link': post('/api/crm/doc/search-link/'),
    'crm.integrations.api.is_call_integration_enabled': get('/api/crm/telephony/status/'),
    'frappe.client.get_doc_permissions': get('/api/crm/doc/permissions/'),
    'frappe.client.get_value': post('/api/crm/doc/get-value/'),
    'crm.api.whatsapp.is_whatsapp_enabled': get('/api/crm/integrations/whatsapp/enabled/'),
    'crm.api.whatsapp.is_whatsapp_installed': get('/api/crm/integrations/whatsapp/installed/'),
    'crm.api.contact.search_emails': post('/api/crm/search-emails/'),
    'crm.api.contact.get_linked_deals': post('/api/crm/contact-linked-deals/'),
    'crm.api.contact.create_new': post('/api/crm/contact-create-new/'),
    'crm.api.contact.set_as_primary': post('/api/crm/contact-set-primary/'),
    'frappe.core.doctype.user.user.get_timezones': get('/api/crm/user-timezones/'),
    'crm.api.assignment_rule.get_assignment_rules_list': get('/api/crm/assignment-rules-list/'),
    'crm.api.assignment_rule.duplicate_assignment_rule': post('/api/crm/assignment-rules-duplicate/'),
    'crm.api.notifications.get_notifications': get('/api/crm/notifications/'),
    'crm.api.notifications.mark_as_read': post('/api/crm/notifications/mark-read/'),
    'crm.api.delete_attachment': post('/api/crm/doc/delete-attachment/'),
    'crm.api.get_file_uploader_defaults': get('/api/crm/doc/file-uploader-defaults/'),
    'crm.fcrm.doctype.crm_fields_layout.crm_fields_layout.get_fields_layout': get('/api/crm/fields-layout/'),
    'crm.fcrm.doctype.crm_fields_layout.crm_fields_layout.save_fields_layout': post('/api/crm/fields-layout/save/'),
    'crm.fcrm.doctype.crm_fields_layout.crm_fields_layout.get_sidepanel_sections': get(
      '/api/crm/fields-layout/sidepanel/',
    ),
    'crm.api.doc.remove_assignments': post('/api/crm/doc/assign-to/remove/'),
    'frappe.desk.form.assign_to.add': post('/api/crm/doc/assign-to/add/'),
    'frappe.desk.form.assign_to.add_multiple': post('/api/crm/doc/assign-to/add-multiple/'),
    'frappe.desk.form.assign_to.remove_multiple': post('/api/crm/doc/assign-to/remove-multiple/'),
    'frappe.desk.doctype.bulk_update.bulk_update.submit_cancel_or_update_docs': post('/api/crm/doc/bulk-update/'),
    'crm.api.doc.get_linked_docs_of_document': get('/api/crm/doc/linked-docs/'),
    'crm.api.doc.remove_linked_doc_reference': post('/api/crm/doc/remove-linked-doc-reference/'),
    'crm.api.doc.delete_bulk_docs': post('/api/crm/doc/delete-bulk/'),
    'crm.api.onboarding.get_first_lead': get('/api/crm/onboarding/first-lead/'),
    'crm.api.onboarding.get_first_deal': get('/api/crm/onboarding/first-deal/'),
    'frappe.onboarding.get_onboarding_status': get('/api/crm/onboarding/status/'),
    'frappe.onboarding.update_user_onboarding_status': post('/api/crm/onboarding/status/update/'),
    'frappe.apps.get_apps': get('/api/crm/apps/'),
    'crm.api.activities.get_activities': get('/api/crm/activities/'),
    'crm.api.comment.add_comment': post('/api/crm/add-comment/'),
    'crm.api.get_user_signature': get('/api/crm/user-signature/'),
    'crm.api.dashboard.get_chart_options': get('/api/crm/dashboard/chart-options/'),
    'crm.api.dashboard.get_dashboard': get('/api/crm/dashboard/'),
    'crm.api.dashboard.get_chart': get('/api/crm/dashboard/chart/'),
    'crm.api.dashboard.reset_to_default': post('/api/crm/dashboard/reset/'),
  },
}
