from dsl import CB, F, SB, doctype, perms

UNIT_TYPES = "Retail Shop\nAnchor Store\nKiosk\nFood Court Stall\nRestaurant\nOffice\nStorage\nPromotional Space\nATM / Advertising Space"
UNIT_TYPES = "Retail Shop\nAnchor Store\nKiosk\nFood Court Stall\nRestaurant\nOffice\nStorage\nPromotional Space\nATM / Advertising Space"
TRADE_CATEGORIES ="\nFashion\nFood and Beverage\nElectronics\nSupermarket\nServices\nEntertainment\nHealth and Beauty\nHome and Living\nBanking\nOther"


def defs():
    out = []

    out.append(
        doctype(
            "Property",
            [
                F("property_name", "Data", "Property Name", reqd=1, unique=1, in_list_view=1, in_standard_filter=1),
                F("abbr", "Data", "Abbreviation", reqd=1, length=10, in_list_view=1, set_only_once=1, description="Short code used in unit IDs, e.g. BBS"),
                F("property_type", "Select", "Property Type", options="Shopping Mall\nOffice Park\nMixed Use\nIndustrial\nResidential", default="Shopping Mall", in_list_view=1, in_standard_filter=1),
                F("status", "Select", "Status", options="Operational\nUnder Development\nClosed", default="Operational", in_standard_filter=1),
                CB(),
                F("company", "Link", "Company", options="Company", reqd=1, in_standard_filter=1),
                F("manager", "Link", "Property Manager", options="User"),
                F("contact_phone", "Data", "Contact Phone", options="Phone"),
                F("contact_email", "Data", "Contact Email", options="Email"),
                F("image", "Attach Image", "Image"),
                SB("Location"),
                F("address_line", "Small Text", "Address"),
                F("city", "Data", "City / Town"),
                F("county", "Data", "County"),
                CB(),
                F("country", "Link", "Country", options="Country", default="Kenya"),
                F("latitude", "Float", "Latitude"),
                F("longitude", "Float", "Longitude"),
                SB("Space and Occupancy", "metrics_section"),
                F("gross_leasable_area", "Float", "Gross Leasable Area (sqm)", precision="2"),
                F("total_units", "Int", "Total Units", read_only=1, no_copy=1),
                F("occupied_units", "Int", "Occupied Units", read_only=1, no_copy=1),
                CB(),
                F("vacant_units", "Int", "Vacant Units", read_only=1, no_copy=1),
                F("occupancy_rate", "Percent", "Occupancy Rate", read_only=1, no_copy=1, in_list_view=1),
                F("leased_area", "Float", "Leased Area (sqm)", read_only=1, no_copy=1, precision="2"),
                SB("Accounting", "accounting_section"),
                F("cost_center", "Link", "Cost Center", options="Cost Center"),
                F("rent_income_account", "Link", "Rent Income Account", options="Account"),
                CB(),
                F("service_charge_account", "Link", "Service Charge Income Account", options="Account"),
                F("security_deposit_account", "Link", "Security Deposit Liability Account", options="Account"),
                SB("About", "about_section", collapsible=1),
                F("description", "Text Editor", "Description"),
            ],
            autoname="field:property_name",
            title_field="property_name",
            image_field="image",
            search_fields="abbr,city,property_type",
            naming_rule="By fieldname",
            allow_rename=1,
        )
    )

    out.append(
        doctype(
            "Property Floor",
            [
                F("property", "Link", "Property", options="Property", reqd=1, in_list_view=1, in_standard_filter=1),
                F("floor_name", "Data", "Floor Name", reqd=1, in_list_view=1),
                F("level", "Int", "Level", default="0", in_list_view=1, description="0 = ground floor, negative = basement"),
                CB(),
                F("area_sqm", "Float", "Floor Area (sqm)", precision="2"),
                F("floor_plan", "Attach Image", "Floor Plan"),
                SB("Notes", "notes_section", collapsible=1),
                F("notes", "Small Text", "Notes"),
            ],
            autoname="Prompt",
            naming_rule="Set by user",
            title_field="floor_name",
            sort_field="modified",
        )
    )

    out.append(
        doctype(
            "Rentable Unit",
            [
                F("property", "Link", "Property", options="Property", reqd=1, in_list_view=1, in_standard_filter=1, set_only_once=1),
                F("floor", "Link", "Floor", options="Property Floor", in_standard_filter=1),
                F("unit_code", "Data", "Unit Code", reqd=1, in_list_view=1, set_only_once=1),
                F("unit_name", "Data", "Display Name"),
                CB(),
                F("status", "Select", "Status", options="Vacant\nReserved\nOccupied\nUnder Maintenance", default="Vacant", in_list_view=1, in_standard_filter=1),
                F("unit_type", "Select", "Unit Type", options=UNIT_TYPES, default="Retail Shop", in_list_view=1, in_standard_filter=1),
                F("category", "Select", "Trade Category", options=TRADE_CATEGORIES),
                SB("Space and Rent", "space_section"),
                F("area_sqm", "Float", "Area (sqm)", reqd=1, precision="2", in_list_view=1),
                F("rate_per_sqm", "Currency", "Rent Rate per sqm"),
                F("base_rent", "Currency", "Monthly Base Rent", in_list_view=1, description="Defaults to area x rate when a rate is set"),
                CB(),
                F("service_charge_per_sqm", "Currency", "Service Charge per sqm"),
                F("service_charge", "Currency", "Monthly Service Charge"),
                SB("Occupancy", "occupancy_section"),
                F("current_lease", "Link", "Current Lease", options="Lease Agreement", read_only=1, no_copy=1),
                F("current_tenant", "Link", "Current Tenant", options="Customer", read_only=1, no_copy=1, in_list_view=1),
                CB(),
                F("lease_expiry", "Date", "Lease Expiry", read_only=1, no_copy=1),
                F("vacant_since", "Date", "Vacant Since", read_only=1, no_copy=1),
                SB("Features", "features_section", collapsible=1),
                F("features", "Small Text", "Features"),
                F("frontage_m", "Float", "Frontage (m)", precision="2"),
                F("photo", "Attach Image", "Photo"),
                SB("Stacking Plan", "layout_section", collapsible=1),
                F("plan_x", "Float", "Plan X"),
                F("plan_y", "Float", "Plan Y"),
                CB(),
                F("plan_width", "Float", "Plan Width"),
                F("plan_height", "Float", "Plan Height"),
            ],
            autoname="Prompt",
            naming_rule="Set by user",
            title_field="unit_name",
            image_field="photo",
            search_fields="unit_code,unit_name,current_tenant,unit_type",
            sort_field="modified",
        )
    )

    out.append(
        doctype(
            "Property Settings",
            [
                F("default_company", "Link", "Default Company", options="Company"),
                F("default_property", "Link", "Default Property", options="Property"),
                SB("Billing", "billing_section"),
                F("auto_generate_invoices", "Check", "Generate Rent Invoices Automatically", default="1"),
                F("billing_lead_days", "Int", "Invoice This Many Days Before the Period Starts", default="0"),
                F("submit_invoices_automatically", "Check", "Submit Generated Invoices", default="1"),
                F("send_invoice_by_email", "Check", "Email Invoices to Tenants"),
                CB(),
                F("rent_item", "Link", "Rent Item", options="Item"),
                F("service_charge_item", "Link", "Service Charge Item", options="Item"),
                F("turnover_rent_item", "Link", "Turnover Rent Item", options="Item"),
                F("late_fee_item", "Link", "Late Fee Item", options="Item"),
                F("maintenance_charge_item", "Link", "Maintenance Recharge Item", options="Item"),
                F("tax_template", "Link", "Default Sales Tax Template", options="Sales Taxes and Charges Template"),
                SB("Late Fees", "late_fee_section"),
                F("enable_late_fees", "Check", "Charge Late Fees"),
                F("grace_period_days", "Int", "Grace Period (days)", default="5", depends_on="enable_late_fees"),
                F("late_fee_percent", "Percent", "Late Fee (% of outstanding per month)", default="5", depends_on="enable_late_fees"),
                CB(),
                F("late_fee_flat_amount", "Currency", "Flat Late Fee", depends_on="enable_late_fees"),
                F("maximum_late_fee_percent", "Percent", "Maximum Late Fee (% of invoice)", default="25", depends_on="enable_late_fees"),
                SB("Reminders", "reminders_section"),
                F("send_sms_reminders", "Check", "Send SMS Reminders", default="1"),
                F("send_email_reminders", "Check", "Send Email Reminders", default="1"),
                F("reminder_days_before_due", "Int", "Remind This Many Days Before Due", default="3"),
                F("overdue_reminder_every_days", "Int", "Repeat Overdue Reminders Every (days)", default="7"),
                CB(),
                F("lease_expiry_alert_days", "Int", "Alert Before Lease Expiry (days)", default="90"),
                F("expiry_alert_recipients", "Small Text", "Expiry Alert Recipients", description="One email address per line. Property managers are included automatically."),
                F("reminder_sms_template", "Small Text", "Due Reminder SMS", default="Dear {tenant}, rent invoice {invoice} of {amount} is due on {due_date}. Pay via M-Pesa Paybill {paybill}, account {account}."),
                F("overdue_sms_template", "Small Text", "Overdue SMS", default="Dear {tenant}, invoice {invoice} of {amount} is overdue since {due_date}. Please settle to avoid late fees."),
                SB("M-Pesa", "mpesa_section"),
                F("mpesa_environment", "Select", "Environment", options="Sandbox\nProduction", default="Sandbox"),
                F("mpesa_callback_url", "Data", "Public Site URL", description="Safaricom posts payment results here, e.g. https://erp.bbsmall.co.ke"),
                F("mpesa_paybill", "Data", "Paybill Number"),
                F("mpesa_till", "Data", "Till Number"),
                F("mpesa_shortcode", "Data", "STK Shortcode"),
                F("mpesa_consumer_key", "Data", "Consumer Key"),
                F("mpesa_consumer_secret", "Password", "Consumer Secret"),
                CB(),
                F("mpesa_passkey", "Password", "Passkey"),
                F("mpesa_callback_token", "Password", "Callback Token", description="Secret path segment protecting the callback URL"),
                F("mpesa_mode_of_payment", "Link", "Mode of Payment", options="Mode of Payment"),
                F("mpesa_clearing_account", "Link", "Receiving Account", options="Account"),
                F("account_reference_format", "Data", "Account Reference", default="{customer}", description="Placeholders: {customer}, {unit}, {lease}"),
                SB("Tenant Portal", "portal_section"),
                F("enable_tenant_portal", "Check", "Enable Tenant Portal", default="1"),
                F("allow_tenant_meter_readings", "Check", "Tenants May Submit Meter Readings", default="1"),
                F("require_reading_approval", "Check", "Readings Need Approval", default="1"),
                F("allow_tenant_sales_declarations", "Check", "Tenants May Declare Turnover", default="1"),
                CB(),
                F("maintenance_sla_hours", "Int", "Maintenance Response SLA (hours)", default="48"),
                F("portal_welcome_message", "Small Text", "Portal Welcome Message"),
                F("support_phone", "Data", "Management Office Phone"),
                F("support_email", "Data", "Management Office Email"),
            ],
            issingle=1,
            permissions=perms(),
        )
    )

    return out
