from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class AssetGenerated(FrappeModel):
    doctype = 'Asset'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_name = models.CharField(max_length=140, blank=True, null=True, default='')
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_category = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_owner = models.CharField(max_length=140, blank=True, null=True, default='Company')
    asset_owner_company = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier = models.CharField(max_length=140, blank=True, null=True, default='')
    customer = models.CharField(max_length=140, blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    location = models.CharField(max_length=140, blank=True, null=True, default='')
    custodian = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    department = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_date = models.DateField(null=True, blank=True)
    disposal_date = models.DateField(null=True, blank=True)
    journal_entry_for_scrap = models.CharField(max_length=140, blank=True, null=True, default='')
    available_for_use_date = models.DateField(null=True, blank=True)
    calculate_depreciation = models.SmallIntegerField(default=0)
    opening_accumulated_depreciation = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    depreciation_method = models.CharField(max_length=140, blank=True, null=True, default='')
    value_after_depreciation = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_number_of_depreciations = models.IntegerField(null=True, blank=True)
    frequency_of_depreciation = models.IntegerField(null=True, blank=True)
    next_depreciation_date = models.DateField(null=True, blank=True)
    policy_number = models.CharField(max_length=140, blank=True, null=True, default='')
    insurer = models.CharField(max_length=140, blank=True, null=True, default='')
    insured_value = models.CharField(max_length=140, blank=True, null=True, default='')
    insurance_start_date = models.DateField(null=True, blank=True)
    insurance_end_date = models.DateField(null=True, blank=True)
    comprehensive_insurance = models.CharField(max_length=140, blank=True, null=True, default='')
    maintenance_required = models.SmallIntegerField(default=0)
    status = models.CharField(max_length=140, blank=True, null=True, default='Draft')
    booked_fixed_asset = models.SmallIntegerField(default=0)
    purchase_receipt = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_invoice = models.CharField(max_length=140, blank=True, null=True, default='')
    default_finance_book = models.CharField(max_length=140, blank=True, null=True, default='')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    split_from = models.CharField(max_length=140, blank=True, null=True, default='')
    asset_quantity = models.IntegerField(null=True, blank=True)
    depr_entry_posting_status = models.CharField(max_length=140, blank=True, null=True, default='')
    is_fully_depreciated = models.SmallIntegerField(default=0)
    total_asset_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_asset_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    purchase_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    opening_number_of_booked_depreciations = models.IntegerField(null=True, blank=True)
    purchase_receipt_item = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_invoice_item = models.CharField(max_length=140, blank=True, null=True, default='')
    net_purchase_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    asset_type = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
