import type { NavigationItem } from '@/core/modules/types'

const hrmsNavigationItems: NavigationItem[] = [
  { id: 'HRMS Home', label: 'Home', to: { name: 'HRMS Home' }, icon: 'lucide-house', order: 10 },
  {
    id: 'HRMS Attendance',
    label: 'Attendance',
    to: { name: 'HRMS Attendance' },
    icon: 'lucide-calendar-check',
    order: 20,
  },
  { id: 'HRMS Leaves', label: 'Leaves', to: { name: 'HRMS Leaves' }, icon: 'lucide-calendar-off', order: 30 },
  {
    id: 'HRMS Expense Claims',
    label: 'Expenses',
    to: { name: 'HRMS Expense Claims' },
    icon: 'lucide-receipt',
    order: 40,
  },
  {
    id: 'HRMS Salary Slips',
    label: 'Salary',
    to: { name: 'HRMS Salary Slips' },
    icon: 'lucide-wallet-cards',
    order: 50,
  },
  { id: 'HRMS Roster', label: 'Roster', to: { name: 'HRMS Roster' }, icon: 'lucide-calendar-range', order: 60 },
  { id: 'HRMS Manager Employees', label: 'Employees', to: { name: 'Desk List', params: { doctype: 'Employee' } }, icon: 'lucide-users', order: 70, section: 'Manager' },
  { id: 'HRMS Manager Leave Applications', label: 'Leave Applications', to: { name: 'Desk List', params: { doctype: 'Leave Application' } }, icon: 'lucide-calendar-off', order: 80, section: 'Manager' },
  { id: 'HRMS Manager Attendance', label: 'Attendance Records', to: { name: 'Desk List', params: { doctype: 'Attendance' } }, icon: 'lucide-calendar-check', order: 90, section: 'Manager' },
  { id: 'HRMS Manager Expense Claims', label: 'Expense Claims', to: { name: 'Desk List', params: { doctype: 'Expense Claim' } }, icon: 'lucide-receipt', order: 100, section: 'Manager' },
  { id: 'HRMS Manager Salary Slips', label: 'Salary Slips', to: { name: 'Desk List', params: { doctype: 'Salary Slip' } }, icon: 'lucide-wallet-cards', order: 110, section: 'Manager' },
  { id: 'HRMS Manager Recruitment', label: 'Job Applicants', to: { name: 'Desk List', params: { doctype: 'Job Applicant' } }, icon: 'lucide-user-round-search', order: 120, section: 'Manager' },
  { id: 'HRMS Manager Organizational Chart', label: 'Organizational Chart', to: { name: 'HRMS Organizational Chart' }, icon: 'lucide-network', order: 125, section: 'Manager' },
  { id: 'HRMS Setup Employee Groups', label: 'Employee Groups', to: { name: 'Desk List', params: { doctype: 'Employee Group' } }, icon: 'lucide-users-round', order: 130, section: 'HR Setup' },
  { id: 'HRMS Setup Employee Grades', label: 'Employee Grades', to: { name: 'Desk List', params: { doctype: 'Employee Grade' } }, icon: 'lucide-layers-3', order: 140, section: 'HR Setup' },
  { id: 'HRMS Setup Employee Types', label: 'Employee Types', to: { name: 'Desk List', params: { doctype: 'Employee Type' } }, icon: 'lucide-badge', order: 150, section: 'HR Setup' },
  { id: 'HRMS Setup Departments', label: 'Departments', to: { name: 'Desk List', params: { doctype: 'Department' } }, icon: 'lucide-building-2', order: 160, section: 'HR Setup' },
  { id: 'HRMS Setup Designations', label: 'Designations', to: { name: 'Desk List', params: { doctype: 'Designation' } }, icon: 'lucide-id-card', order: 170, section: 'HR Setup' },
  { id: 'HRMS Setup Branches', label: 'Branches', to: { name: 'Desk List', params: { doctype: 'Branch' } }, icon: 'lucide-map-pin', order: 180, section: 'HR Setup' },
  { id: 'HRMS Setup Holiday Lists', label: 'Holiday Lists', to: { name: 'Desk List', params: { doctype: 'Holiday List' } }, icon: 'lucide-calendar-heart', order: 190, section: 'HR Setup' },
  { id: 'HRMS Setup Employee Onboarding', label: 'Employee Onboarding', to: { name: 'Desk List', params: { doctype: 'Employee Onboarding' } }, icon: 'lucide-user-round-plus', order: 192, section: 'HR Setup' },
  { id: 'HRMS Setup Employee Separation', label: 'Employee Separation', to: { name: 'Desk List', params: { doctype: 'Employee Separation' } }, icon: 'lucide-user-round-minus', order: 194, section: 'HR Setup' },
  { id: 'HRMS Setup Employee Promotion', label: 'Employee Promotions', to: { name: 'Desk List', params: { doctype: 'Employee Promotion' } }, icon: 'lucide-arrow-up-right', order: 196, section: 'HR Setup' },
  { id: 'HRMS Setup Employee Transfer', label: 'Employee Transfers', to: { name: 'Desk List', params: { doctype: 'Employee Transfer' } }, icon: 'lucide-arrow-right-left', order: 198, section: 'HR Setup' },
  { id: 'HRMS Setup Employee Referral', label: 'Employee Referrals', to: { name: 'Desk List', params: { doctype: 'Employee Referral' } }, icon: 'lucide-user-round-plus', order: 199, section: 'HR Setup' },
  { id: 'HRMS Setup Onboarding Templates', label: 'Onboarding Templates', to: { name: 'Desk List', params: { doctype: 'Employee Onboarding Template' } }, icon: 'lucide-list-checks', order: 201, section: 'HR Setup' },
  { id: 'HRMS Setup Separation Templates', label: 'Separation Templates', to: { name: 'Desk List', params: { doctype: 'Employee Separation Template' } }, icon: 'lucide-list-x', order: 202, section: 'HR Setup' },
  { id: 'HRMS Setup Appointment Letter Templates', label: 'Appointment Letter Templates', to: { name: 'Desk List', params: { doctype: 'Appointment Letter Template' } }, icon: 'lucide-file-signature', order: 203, section: 'HR Setup' },
  { id: 'HRMS Setup Identification Documents', label: 'Identification Documents', to: { name: 'Desk List', params: { doctype: 'Identification Document Type' } }, icon: 'lucide-badge-check', order: 204, section: 'HR Setup' },
  { id: 'HRMS Setup Skills', label: 'Skills', to: { name: 'Desk List', params: { doctype: 'Skill' } }, icon: 'lucide-sparkles', order: 205, section: 'HR Setup' },
  { id: 'HRMS Setup Settings', label: 'HR Settings', to: { name: 'Desk List', params: { doctype: 'HR Settings' } }, icon: 'lucide-settings-2', order: 200, section: 'HR Setup' },
  { id: 'HRMS Leaves Types', label: 'Leave Types', to: { name: 'Desk List', params: { doctype: 'Leave Type' } }, icon: 'lucide-calendar-plus', order: 210, section: 'Leaves' },
  { id: 'HRMS Leaves Policies', label: 'Leave Policies', to: { name: 'Desk List', params: { doctype: 'Leave Policy' } }, icon: 'lucide-file-check-2', order: 220, section: 'Leaves' },
  { id: 'HRMS Leaves Allocations', label: 'Leave Allocations', to: { name: 'Desk List', params: { doctype: 'Leave Allocation' } }, icon: 'lucide-calendar-range', order: 230, section: 'Leaves' },
  { id: 'HRMS Leaves Periods', label: 'Leave Periods', to: { name: 'Desk List', params: { doctype: 'Leave Period' } }, icon: 'lucide-calendar-clock', order: 232, section: 'Leaves' },
  { id: 'HRMS Leaves Policy Assignments', label: 'Leave Policy Assignments', to: { name: 'Desk List', params: { doctype: 'Leave Policy Assignment' } }, icon: 'lucide-file-check-2', order: 234, section: 'Leaves' },
  { id: 'HRMS Leaves Encashments', label: 'Leave Encashments', to: { name: 'Desk List', params: { doctype: 'Leave Encashment' } }, icon: 'lucide-coins', order: 236, section: 'Leaves' },
  { id: 'HRMS Leaves Compensatory', label: 'Compensatory Leave', to: { name: 'Desk List', params: { doctype: 'Compensatory Leave Request' } }, icon: 'lucide-calendar-plus', order: 238, section: 'Leaves' },
  { id: 'HRMS Leaves Control Panel', label: 'Leave Control Panel', to: { name: 'HRMS Leave Control Panel' }, icon: 'lucide-sliders-horizontal', order: 239, section: 'Leaves' },
  { id: 'HRMS Leaves Adjustments', label: 'Leave Adjustments', to: { name: 'Desk List', params: { doctype: 'Leave Adjustment' } }, icon: 'lucide-calendar-cog', order: 239.1, section: 'Leaves' },
  { id: 'HRMS Leaves Ledger', label: 'Leave Ledger Entries', to: { name: 'Desk List', params: { doctype: 'Leave Ledger Entry' } }, icon: 'lucide-notebook-tabs', order: 239.2, section: 'Leaves' },
  { id: 'HRMS Leaves Block List', label: 'Leave Block Lists', to: { name: 'Desk List', params: { doctype: 'Leave Block List' } }, icon: 'lucide-calendar-x-2', order: 239.3, section: 'Leaves' },
  { id: 'HRMS Attendance Requests', label: 'Attendance Requests', to: { name: 'Desk List', params: { doctype: 'Attendance Request' } }, icon: 'lucide-calendar-clock', order: 240, section: 'Shift & Attendance' },
  { id: 'HRMS Attendance Checkins', label: 'Employee Checkins', to: { name: 'Desk List', params: { doctype: 'Employee Checkin' } }, icon: 'lucide-fingerprint', order: 250, section: 'Shift & Attendance' },
  { id: 'HRMS Attendance Shifts', label: 'Shift Assignments', to: { name: 'Desk List', params: { doctype: 'Shift Assignment' } }, icon: 'lucide-clock-3', order: 260, section: 'Shift & Attendance' },
  { id: 'HRMS Attendance Shift Types', label: 'Shift Types', to: { name: 'Desk List', params: { doctype: 'Shift Type' } }, icon: 'lucide-clock-3', order: 262, section: 'Shift & Attendance' },
  { id: 'HRMS Attendance Tool', label: 'Employee Attendance Tool', to: { name: 'HRMS Employee Attendance Tool' }, icon: 'lucide-calendar-check-2', order: 264, section: 'Shift & Attendance' },
  { id: 'HRMS Attendance Shift Tool', label: 'Shift Assignment Tool', to: { name: 'HRMS Shift Assignment Tool' }, icon: 'lucide-calendar-cog', order: 266, section: 'Shift & Attendance' },
  { id: 'HRMS Attendance Shift Requests', label: 'Shift Requests', to: { name: 'Desk List', params: { doctype: 'Shift Request' } }, icon: 'lucide-calendar-clock', order: 267, section: 'Shift & Attendance' },
  { id: 'HRMS Attendance Shift Schedules', label: 'Shift Schedules', to: { name: 'Desk List', params: { doctype: 'Shift Schedule' } }, icon: 'lucide-calendar-range', order: 268, section: 'Shift & Attendance' },
  { id: 'HRMS Attendance Shift Locations', label: 'Shift Locations', to: { name: 'Desk List', params: { doctype: 'Shift Location' } }, icon: 'lucide-map-pin', order: 269, section: 'Shift & Attendance' },
  { id: 'HRMS Expenses Advances', label: 'Employee Advances', to: { name: 'Desk List', params: { doctype: 'Employee Advance' } }, icon: 'lucide-hand-coins', order: 270, section: 'Expenses' },
  { id: 'HRMS Expenses Types', label: 'Expense Claim Types', to: { name: 'Desk List', params: { doctype: 'Expense Claim Type' } }, icon: 'lucide-receipt-text', order: 272, section: 'Expenses' },
  { id: 'HRMS Expenses Travel', label: 'Travel Requests', to: { name: 'Desk List', params: { doctype: 'Travel Request' } }, icon: 'lucide-plane', order: 274, section: 'Expenses' },
  { id: 'HRMS Expenses Vehicle', label: 'Vehicle Logs', to: { name: 'Desk List', params: { doctype: 'Vehicle Log' } }, icon: 'lucide-car-front', order: 276, section: 'Expenses' },
  { id: 'HRMS Expenses Travel Itineraries', label: 'Travel Itineraries', to: { name: 'Desk List', params: { doctype: 'Travel Itinerary' } }, icon: 'lucide-route', order: 277, section: 'Expenses' },
  { id: 'HRMS Expenses Vehicle Services', label: 'Vehicle Service Items', to: { name: 'Desk List', params: { doctype: 'Vehicle Service Item' } }, icon: 'lucide-wrench', order: 278, section: 'Expenses' },
  { id: 'HRMS Payroll Entries', label: 'Payroll Entries', to: { name: 'Desk List', params: { doctype: 'Payroll Entry' } }, icon: 'lucide-calculator', order: 280, section: 'Payroll' },
  { id: 'HRMS Payroll Components', label: 'Salary Components', to: { name: 'Desk List', params: { doctype: 'Salary Component' } }, icon: 'lucide-coins', order: 290, section: 'Payroll' },
  { id: 'HRMS Payroll Structures', label: 'Salary Structures', to: { name: 'Desk List', params: { doctype: 'Salary Structure' } }, icon: 'lucide-table-properties', order: 300, section: 'Payroll' },
  { id: 'HRMS Payroll Assignments', label: 'Salary Assignments', to: { name: 'Desk List', params: { doctype: 'Salary Structure Assignment' } }, icon: 'lucide-user-check', order: 310, section: 'Payroll' },
  { id: 'HRMS Payroll Periods', label: 'Payroll Periods', to: { name: 'Desk List', params: { doctype: 'Payroll Period' } }, icon: 'lucide-calendar-range', order: 320, section: 'Payroll' },
  { id: 'HRMS Payroll Additional Salary', label: 'Additional Salaries', to: { name: 'Desk List', params: { doctype: 'Additional Salary' } }, icon: 'lucide-circle-dollar-sign', order: 322, section: 'Payroll' },
  { id: 'HRMS Payroll Benefits', label: 'Benefit Applications', to: { name: 'Desk List', params: { doctype: 'Employee Benefit Application' } }, icon: 'lucide-badge-dollar-sign', order: 324, section: 'Payroll' },
  { id: 'HRMS Payroll Benefit Claims', label: 'Benefit Claims', to: { name: 'Desk List', params: { doctype: 'Employee Benefit Claim' } }, icon: 'lucide-badge-dollar-sign', order: 325, section: 'Payroll' },
  { id: 'HRMS Payroll Incentives', label: 'Employee Incentives', to: { name: 'Desk List', params: { doctype: 'Employee Incentive' } }, icon: 'lucide-award', order: 326, section: 'Payroll' },
  { id: 'HRMS Payroll Withholding', label: 'Salary Withholding', to: { name: 'Desk List', params: { doctype: 'Salary Withholding' } }, icon: 'lucide-wallet-cards', order: 328, section: 'Payroll' },
  { id: 'HRMS Payroll Gratuity', label: 'Gratuity', to: { name: 'Desk List', params: { doctype: 'Gratuity' } }, icon: 'lucide-hand-coins', order: 329, section: 'Payroll' },
  { id: 'HRMS Payroll Retention Bonus', label: 'Retention Bonuses', to: { name: 'Desk List', params: { doctype: 'Retention Bonus' } }, icon: 'lucide-badge-dollar-sign', order: 329.1, section: 'Payroll' },
  { id: 'HRMS Payroll Arrears', label: 'Arrears', to: { name: 'Desk List', params: { doctype: 'Arrear' } }, icon: 'lucide-circle-dollar-sign', order: 329.2, section: 'Payroll' },
  { id: 'HRMS Payroll Tax Declarations', label: 'Tax Exemption Declarations', to: { name: 'Desk List', params: { doctype: 'Employee Tax Exemption Declaration' } }, icon: 'lucide-file-check-2', order: 329.3, section: 'Payroll' },
  { id: 'HRMS Payroll Tax Proofs', label: 'Tax Exemption Proofs', to: { name: 'Desk List', params: { doctype: 'Employee Tax Exemption Proof Submission' } }, icon: 'lucide-file-check-2', order: 329.4, section: 'Payroll' },
  { id: 'HRMS Payroll Full And Final', label: 'Full and Final Statements', to: { name: 'Desk List', params: { doctype: 'Full and Final Statement' } }, icon: 'lucide-file-output', order: 329.5, section: 'Payroll' },
  { id: 'HRMS Payroll Overtime', label: 'Overtime Slips', to: { name: 'Desk List', params: { doctype: 'Overtime Slip' } }, icon: 'lucide-clock-3', order: 329.8, section: 'Payroll' },
  { id: 'HRMS Payroll Corrections', label: 'Payroll Corrections', to: { name: 'Desk List', params: { doctype: 'Payroll Correction' } }, icon: 'lucide-file-cog', order: 329.9, section: 'Payroll' },
  { id: 'HRMS Recruitment Requisitions', label: 'Job Requisitions', to: { name: 'Desk List', params: { doctype: 'Job Requisition' } }, icon: 'lucide-file-user', order: 330, section: 'Recruitment' },
  { id: 'HRMS Recruitment Openings', label: 'Job Openings', to: { name: 'Desk List', params: { doctype: 'Job Opening' } }, icon: 'lucide-briefcase-business', order: 340, section: 'Recruitment' },
  { id: 'HRMS Recruitment Interviews', label: 'Interviews', to: { name: 'Desk List', params: { doctype: 'Interview' } }, icon: 'lucide-messages-square', order: 350, section: 'Recruitment' },
  { id: 'HRMS Recruitment Offers', label: 'Job Offers', to: { name: 'Desk List', params: { doctype: 'Job Offer' } }, icon: 'lucide-file-signature', order: 360, section: 'Recruitment' },
  { id: 'HRMS Recruitment Sources', label: 'Applicant Sources', to: { name: 'Desk List', params: { doctype: 'Job Applicant Source' } }, icon: 'lucide-share-2', order: 362, section: 'Recruitment' },
  { id: 'HRMS Recruitment Interview Types', label: 'Interview Types', to: { name: 'Desk List', params: { doctype: 'Interview Type' } }, icon: 'lucide-messages-square', order: 364, section: 'Recruitment' },
  { id: 'HRMS Recruitment Staffing Plans', label: 'Staffing Plans', to: { name: 'Desk List', params: { doctype: 'Staffing Plan' } }, icon: 'lucide-users-round', order: 366, section: 'Recruitment' },
  { id: 'HRMS Recruitment Appointment Letters', label: 'Appointment Letters', to: { name: 'Desk List', params: { doctype: 'Appointment Letter' } }, icon: 'lucide-file-signature', order: 368, section: 'Recruitment' },
  { id: 'HRMS Recruitment Offer Templates', label: 'Job Offer Templates', to: { name: 'Desk List', params: { doctype: 'Job Opening Template' } }, icon: 'lucide-file-text', order: 369, section: 'Recruitment' },
  { id: 'HRMS Performance Cycles', label: 'Appraisal Cycles', to: { name: 'Desk List', params: { doctype: 'Appraisal Cycle' } }, icon: 'lucide-refresh-cw', order: 370, section: 'Performance' },
  { id: 'HRMS Performance Appraisals', label: 'Appraisals', to: { name: 'Desk List', params: { doctype: 'Appraisal' } }, icon: 'lucide-chart-no-axes-combined', order: 380, section: 'Performance' },
  { id: 'HRMS Performance Goals', label: 'Goals', to: { name: 'Desk List', params: { doctype: 'Goal' } }, icon: 'lucide-target', order: 390, section: 'Performance' },
  { id: 'HRMS Performance Feedback', label: 'Employee Feedback', to: { name: 'Desk List', params: { doctype: 'Employee Performance Feedback' } }, icon: 'lucide-message-square-heart', order: 400, section: 'Performance' },
  { id: 'HRMS Performance Training', label: 'Training Programs', to: { name: 'Desk List', params: { doctype: 'Training Program' } }, icon: 'lucide-graduation-cap', order: 410, section: 'Performance' },
  { id: 'HRMS Performance Events', label: 'Training Events', to: { name: 'Desk List', params: { doctype: 'Training Event' } }, icon: 'lucide-calendar-plus', order: 412, section: 'Performance' },
  { id: 'HRMS Performance Results', label: 'Training Results', to: { name: 'Desk List', params: { doctype: 'Training Result' } }, icon: 'lucide-clipboard-check', order: 414, section: 'Performance' },
  { id: 'HRMS Performance Training Feedback', label: 'Training Feedback', to: { name: 'Desk List', params: { doctype: 'Training Feedback' } }, icon: 'lucide-message-square-heart', order: 416, section: 'Performance' },
  { id: 'HRMS Performance Templates', label: 'Appraisal Templates', to: { name: 'Desk List', params: { doctype: 'Appraisal Template' } }, icon: 'lucide-file-check-2', order: 417, section: 'Performance' },
  { id: 'HRMS Performance KRAs', label: 'Key Result Areas', to: { name: 'Desk List', params: { doctype: 'KRA' } }, icon: 'lucide-target', order: 418, section: 'Performance' },
  { id: 'HRMS Performance Skills', label: 'Employee Skill Maps', to: { name: 'Desk List', params: { doctype: 'Employee Skill Map' } }, icon: 'lucide-sparkles', order: 419, section: 'Performance' },
  { id: 'HRMS Report Leave Balance', label: 'Employee Leave Balance', to: { name: 'Desk Report', params: { report: 'Employee Leave Balance' } }, icon: 'lucide-chart-no-axes-combined', order: 420, section: 'Reports' },
  { id: 'HRMS Report Attendance', label: 'Monthly Attendance Sheet', to: { name: 'Desk Report', params: { report: 'Monthly Attendance Sheet' } }, icon: 'lucide-chart-no-axes-combined', order: 430, section: 'Reports' },
  { id: 'HRMS Report Salary Register', label: 'Salary Register', to: { name: 'Desk Report', params: { report: 'Salary Register' } }, icon: 'lucide-chart-no-axes-combined', order: 440, section: 'Reports' },
  { id: 'HRMS Report Employee CTC', label: 'Employee CTC Breakup', to: { name: 'Desk Report', params: { report: 'Employee CTC Breakup' } }, icon: 'lucide-chart-no-axes-combined', order: 450, section: 'Reports' },
  { id: 'HRMS Report Leave Ledger', label: 'Leave Ledger', to: { name: 'Desk Report', params: { report: 'Leave Ledger' } }, icon: 'lucide-notebook-tabs', order: 452, section: 'Reports' },
  { id: 'HRMS Report Employee Analytics', label: 'Employee Analytics', to: { name: 'Desk Report', params: { report: 'Employee Analytics' } }, icon: 'lucide-chart-no-axes-combined', order: 454, section: 'Reports' },
  { id: 'HRMS Report Employee Information', label: 'Employee Information', to: { name: 'Desk Report', params: { report: 'Employee Information' } }, icon: 'lucide-file-user', order: 456, section: 'Reports' },
  { id: 'HRMS Report Employee Birthday', label: 'Employee Birthday', to: { name: 'Desk Report', params: { report: 'Employee Birthday' } }, icon: 'lucide-cake', order: 458, section: 'Reports' },
  { id: 'HRMS Report Employee Exits', label: 'Employee Exits', to: { name: 'Desk Report', params: { report: 'Employee Exits' } }, icon: 'lucide-user-round-minus', order: 460, section: 'Reports' },
  { id: 'HRMS Report Employee Advance Summary', label: 'Employee Advance Summary', to: { name: 'Desk Report', params: { report: 'Employee Advance Summary' } }, icon: 'lucide-hand-coins', order: 462, section: 'Reports' },
  { id: 'HRMS Report Shift Attendance', label: 'Shift Attendance', to: { name: 'Desk Report', params: { report: 'Shift Attendance' } }, icon: 'lucide-clock-3', order: 464, section: 'Reports' },
  { id: 'HRMS Report Unpaid Expense Claim', label: 'Unpaid Expense Claim', to: { name: 'Desk Report', params: { report: 'Unpaid Expense Claim' } }, icon: 'lucide-receipt', order: 466, section: 'Reports' },
  { id: 'HRMS Report Salary Payments', label: 'Salary Payments by Mode', to: { name: 'Desk Report', params: { report: 'Salary Payments Based On Payment Mode' } }, icon: 'lucide-wallet-cards', order: 468, section: 'Reports' },
  { id: 'HRMS Report Bank Remittance', label: 'Bank Remittance', to: { name: 'Desk Report', params: { report: 'Bank Remittance' } }, icon: 'lucide-landmark', order: 470, section: 'Reports' },
  { id: 'HRMS Report Income Tax', label: 'Income Tax Computation', to: { name: 'Desk Report', params: { report: 'Income Tax Computation' } }, icon: 'lucide-receipt-text', order: 472, section: 'Reports' },
  { id: 'HRMS Report Accrued Earnings', label: 'Accrued Earnings', to: { name: 'Desk Report', params: { report: 'Accrued Earnings' } }, icon: 'lucide-circle-dollar-sign', order: 474, section: 'Reports' },
  { id: 'HRMS Report Appraisal Overview', label: 'Appraisal Overview', to: { name: 'Desk Report', params: { report: 'Appraisal Overview' } }, icon: 'lucide-chart-no-axes-combined', order: 476, section: 'Reports' },
  { id: 'HRMS Report Recruitment Analytics', label: 'Recruitment Analytics', to: { name: 'Desk Report', params: { report: 'Recruitment Analytics' } }, icon: 'lucide-user-round-search', order: 478, section: 'Reports' },
  { id: 'HRMS Report Vehicle Expenses', label: 'Vehicle Expenses', to: { name: 'Desk Report', params: { report: 'Vehicle Expenses' } }, icon: 'lucide-car-front', order: 480, section: 'Reports' },
  { id: 'HRMS Report Leave Balance Summary', label: 'Employee Leave Balance Summary', to: { name: 'Desk Report', params: { report: 'Employee Leave Balance Summary' } }, icon: 'lucide-chart-no-axes-combined', order: 482, section: 'Reports' },
  { id: 'HRMS Report Employee Hours', label: 'Employee Hours Utilization', to: { name: 'Desk Report', params: { report: 'Employee Hours Utilization Based On Timesheet' } }, icon: 'lucide-clock-3', order: 484, section: 'Reports' },
  { id: 'HRMS Report Holiday Work', label: 'Employees Working on a Holiday', to: { name: 'Desk Report', params: { report: 'Employees Working on a Holiday' } }, icon: 'lucide-calendar-heart', order: 486, section: 'Reports' },
  { id: 'HRMS Report Income Tax Deductions', label: 'Income Tax Deductions', to: { name: 'Desk Report', params: { report: 'Income Tax Deductions' } }, icon: 'lucide-receipt-text', order: 488, section: 'Reports' },
  { id: 'HRMS Report ECS Payments', label: 'Salary Payments via ECS', to: { name: 'Desk Report', params: { report: 'Salary Payments Via ECS' } }, icon: 'lucide-landmark', order: 490, section: 'Reports' },
  { id: 'HRMS Report Project Profitability', label: 'Project Profitability', to: { name: 'Desk Report', params: { report: 'Project Profitability' } }, icon: 'lucide-chart-no-axes-combined', order: 492, section: 'Reports' },
]

const hrmsSectionOrder = ['Self Service', 'Manager', 'Shift & Attendance', 'Leaves', 'Expenses', 'Payroll', 'Recruitment', 'Performance', 'HR Setup', 'Reports']

export const hrmsNavigation: NavigationItem[] = hrmsNavigationItems.map((item) => {
  const section = item.section ?? 'Self Service'
  const position = hrmsSectionOrder.indexOf(section)
  return { ...item, section, sectionOrder: position === -1 ? hrmsSectionOrder.length : position }
})
