from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class EmployeeGenerated(FrappeTreeModel):
    doctype = 'Employee'
    employee = models.CharField(max_length=140, blank=True, null=True, default='')
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    salutation = models.CharField(max_length=140, blank=True, null=True, default='')
    first_name = models.CharField(max_length=140, blank=True, null=True, default='')
    middle_name = models.CharField(max_length=140, blank=True, null=True, default='')
    last_name = models.CharField(max_length=140, blank=True, null=True, default='')
    employee_name = models.CharField(max_length=140, blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    status = models.CharField(max_length=140, blank=True, null=True, default='Active')
    employee_number = models.CharField(max_length=140, blank=True, null=True, default='')
    gender = models.CharField(max_length=140, blank=True, null=True, default='')
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_joining = models.DateField(null=True, blank=True)
    emergency_phone_number = models.CharField(max_length=140, blank=True, null=True, default='')
    person_to_be_contacted = models.CharField(max_length=140, blank=True, null=True, default='')
    relation = models.CharField(max_length=140, blank=True, null=True, default='')
    user_id = models.CharField(max_length=140, blank=True, null=True, default='')
    create_user_permission = models.SmallIntegerField(default=1)
    create_user_automatically = models.SmallIntegerField(default=0)
    scheduled_confirmation_date = models.DateField(null=True, blank=True)
    final_confirmation_date = models.DateField(null=True, blank=True)
    contract_end_date = models.DateField(null=True, blank=True)
    notice_number_of_days = models.IntegerField(null=True, blank=True)
    date_of_retirement = models.DateField(null=True, blank=True)
    department = models.CharField(max_length=140, blank=True, null=True, default='')
    designation = models.CharField(max_length=140, blank=True, null=True, default='')
    reports_to = models.CharField(max_length=140, blank=True, null=True, default='')
    branch = models.CharField(max_length=140, blank=True, null=True, default='')
    holiday_list = models.CharField(max_length=140, blank=True, null=True, default='')
    salary_mode = models.CharField(max_length=140, blank=True, null=True, default='')
    bank_name = models.CharField(max_length=140, blank=True, null=True, default='')
    bank_ac_no = models.CharField(max_length=140, blank=True, null=True, default='')
    cell_number = models.CharField(max_length=140, blank=True, null=True, default='')
    prefered_contact_email = models.CharField(max_length=140, blank=True, null=True, default='')
    prefered_email = models.CharField(max_length=140, blank=True, null=True, default='')
    company_email = models.CharField(max_length=140, blank=True, null=True, default='')
    personal_email = models.CharField(max_length=140, blank=True, null=True, default='')
    unsubscribed = models.SmallIntegerField(default=0)
    permanent_accommodation_type = models.CharField(max_length=140, blank=True, null=True, default='')
    permanent_address = models.TextField(blank=True, null=True, default='')
    current_accommodation_type = models.CharField(max_length=140, blank=True, null=True, default='')
    current_address = models.TextField(blank=True, null=True, default='')
    bio = models.TextField(blank=True, null=True, default='')
    passport_number = models.CharField(max_length=140, blank=True, null=True, default='')
    date_of_issue = models.DateField(null=True, blank=True)
    valid_upto = models.DateField(null=True, blank=True)
    place_of_issue = models.CharField(max_length=140, blank=True, null=True, default='')
    marital_status = models.CharField(max_length=140, blank=True, null=True, default='')
    blood_group = models.CharField(max_length=140, blank=True, null=True, default='')
    family_background = models.TextField(blank=True, null=True, default='')
    health_details = models.TextField(blank=True, null=True, default='')
    resignation_letter_date = models.DateField(null=True, blank=True)
    relieving_date = models.DateField(null=True, blank=True)
    reason_for_leaving = models.TextField(blank=True, null=True, default='')
    leave_encashed = models.CharField(max_length=140, blank=True, null=True, default='')
    encashment_date = models.DateField(null=True, blank=True)
    held_on = models.DateField(null=True, blank=True)
    new_workplace = models.CharField(max_length=140, blank=True, null=True, default='')
    feedback = models.TextField(blank=True, null=True, default='')
    lft = models.IntegerField(null=True, blank=True)
    rgt = models.IntegerField(null=True, blank=True)
    old_parent = models.CharField(max_length=140, blank=True, null=True, default='')
    attendance_device_id = models.CharField(max_length=140, blank=True, null=True, default='')
    salary_currency = models.CharField(max_length=140, blank=True, null=True, default='')
    ctc = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    iban = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
