from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeDateTimeField, FrappeModel, FrappeTimeField, FrappeTreeModel


class StockEntryDetailGenerated(FrappeChildModel):
    doctype = 'Stock Entry Detail'
    barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    s_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    t_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    item_code = models.CharField(max_length=140, blank=True, null=True, default='')
    item_name = models.CharField(max_length=140, blank=True, null=True, default='')
    description = models.TextField(blank=True, null=True, default='')
    image = models.TextField(blank=True, null=True, default='')
    qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    basic_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    basic_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    additional_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    valuation_rate = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    uom = models.CharField(max_length=140, blank=True, null=True, default='')
    conversion_factor = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    stock_uom = models.CharField(max_length=140, blank=True, null=True, default='')
    transfer_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    retain_sample = models.SmallIntegerField(default=0)
    sample_quantity = models.IntegerField(null=True, blank=True)
    serial_no = models.TextField(blank=True, null=True, default='')
    batch_no = models.CharField(max_length=140, blank=True, null=True, default='')
    quality_inspection = models.CharField(max_length=140, blank=True, null=True, default='')
    expense_account = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')
    allow_zero_valuation_rate = models.SmallIntegerField(default=0)
    actual_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    bom_no = models.CharField(max_length=140, blank=True, null=True, default='')
    allow_alternative_item = models.SmallIntegerField(default=0)
    material_request = models.CharField(max_length=140, blank=True, null=True, default='')
    material_request_item = models.CharField(max_length=140, blank=True, null=True, default='')
    pick_list_item = models.CharField(max_length=140, blank=True, null=True, default='')
    original_item = models.CharField(max_length=140, blank=True, null=True, default='')
    subcontracted_item = models.CharField(max_length=140, blank=True, null=True, default='')
    against_stock_entry = models.CharField(max_length=140, blank=True, null=True, default='')
    ste_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    transferred_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    item_group = models.CharField(max_length=140, blank=True, null=True, default='')
    reference_purchase_receipt = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    po_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    sco_rm_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    set_basic_rate_manually = models.SmallIntegerField(default=0)
    putaway_rule = models.CharField(max_length=140, blank=True, null=True, default='')
    is_finished_item = models.SmallIntegerField(default=0)
    job_card_item = models.CharField(max_length=140, blank=True, null=True, default='')
    has_item_scanned = models.SmallIntegerField(default=0)
    serial_and_batch_bundle = models.CharField(max_length=140, blank=True, null=True, default='')
    use_serial_batch_fields = models.SmallIntegerField(default=0)
    landed_cost_voucher_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    customer_provided_item_cost = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    scio_detail = models.CharField(max_length=140, blank=True, null=True, default='')
    against_fg = models.CharField(max_length=140, blank=True, null=True, default='')
    secondary_item_type = models.CharField(max_length=140, blank=True, null=True, default='')
    bom_secondary_item = models.CharField(max_length=140, blank=True, null=True, default='')
    valuation_type = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
