from django.db import models


class DocTypeColumns(models.Model):
    track_seen = models.SmallIntegerField(default=0)
    track_views = models.SmallIntegerField(default=0)
    beta = models.SmallIntegerField(default=0)
    deprecated = models.SmallIntegerField(default=0)
    image_field = models.CharField(max_length=140, blank=True, null=True, default='')
    timeline_field = models.CharField(max_length=140, blank=True, null=True, default='')
    max_attachments = models.IntegerField(null=True, blank=True)
    hide_toolbar = models.SmallIntegerField(default=0)
    allow_copy = models.SmallIntegerField(default=0)
    allow_events_in_timeline = models.SmallIntegerField(default=0)
    allow_auto_repeat = models.SmallIntegerField(default=0)
    search_fields = models.CharField(max_length=140, blank=True, null=True, default='')
    default_print_format = models.CharField(max_length=140, blank=True, null=True, default='')
    icon = models.CharField(max_length=140, blank=True, null=True, default='')
    color = models.CharField(max_length=140, blank=True, null=True, default='')
    show_preview_popup = models.SmallIntegerField(default=0)
    show_name_in_global_search = models.SmallIntegerField(default=0)
    restrict_to_domain = models.CharField(max_length=140, blank=True, null=True, default='')
    read_only = models.SmallIntegerField(default=0)
    in_create = models.SmallIntegerField(default=0)
    has_web_view = models.SmallIntegerField(default=0)
    allow_guest_to_view = models.SmallIntegerField(default=0)
    route = models.CharField(max_length=140, blank=True, null=True, default='')
    is_published_field = models.CharField(max_length=140, blank=True, null=True, default='')
    documentation = models.CharField(max_length=140, blank=True, null=True, default='')
    subject_field = models.CharField(max_length=140, blank=True, null=True, default='')
    sender_field = models.CharField(max_length=140, blank=True, null=True, default='')
    email_append_to = models.SmallIntegerField(default=0)
    default_email_template = models.CharField(max_length=140, blank=True, null=True, default='')
    migration_hash = models.CharField(max_length=140, blank=True, null=True, default='')
    show_title_field_in_link = models.SmallIntegerField(default=0)
    translated_doctype = models.SmallIntegerField(default=0)
    make_attachments_public = models.SmallIntegerField(default=0)
    queue_in_background = models.SmallIntegerField(default=0)
    default_view = models.CharField(max_length=140, blank=True, null=True, default='')
    force_re_route_to_default_view = models.SmallIntegerField(default=0)
    is_calendar_and_gantt = models.SmallIntegerField(default=0)
    sender_name_field = models.CharField(max_length=140, blank=True, null=True, default='')
    row_format = models.CharField(max_length=140, blank=True, null=True, default='Dynamic')
    grid_page_length = models.IntegerField(null=True, blank=True)
    protect_attached_files = models.SmallIntegerField(default=0)
    rows_threshold_for_grid_search = models.IntegerField(null=True, blank=True)
    recipient_account_field = models.CharField(max_length=140, blank=True, null=True, default='')
    allow_bulk_edit = models.SmallIntegerField(default=1)

    class Meta:
        abstract = True


class DocFieldColumns(models.Model):
    allow_in_quick_entry = models.SmallIntegerField(default=0)
    allow_bulk_edit = models.SmallIntegerField(default=0)
    remember_last_selected_value = models.SmallIntegerField(default=0)
    ignore_xss_filter = models.SmallIntegerField(default=0)
    in_filter = models.SmallIntegerField(default=0)
    ignore_versioning = models.SmallIntegerField(default=0)
    print_hide_if_no_value = models.SmallIntegerField(default=0)
    oldfieldname = models.CharField(max_length=140, blank=True, null=True, default='')
    oldfieldtype = models.CharField(max_length=140, blank=True, null=True, default='')
    alignment = models.CharField(max_length=140, blank=True, null=True, default='')
    hide_days = models.SmallIntegerField(default=0)
    hide_seconds = models.SmallIntegerField(default=0)
    hide_border = models.SmallIntegerField(default=0)
    min_value = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    max_value = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    max_height = models.CharField(max_length=10, blank=True, null=True, default='')
    show_dashboard = models.SmallIntegerField(default=0)
    documentation_url = models.CharField(max_length=140, blank=True, null=True, default='')
    sort_options = models.SmallIntegerField(default=0)
    not_nullable = models.SmallIntegerField(default=0)
    show_on_timeline = models.SmallIntegerField(default=0)
    placeholder = models.CharField(max_length=140, blank=True, null=True, default='')
    make_attachment_public = models.SmallIntegerField(default=0)
    sticky = models.SmallIntegerField(default=0)
    mask = models.SmallIntegerField(default=0)
    button_color = models.CharField(max_length=140, blank=True, null=True, default='')
    show_description_on_click = models.SmallIntegerField(default=0)
    in_import_template = models.SmallIntegerField(default=0)

    class Meta:
        abstract = True
