from django.db import models

from apps.frappe.model.base import FrappeChildModel, FrappeModel, FrappeTreeModel


class StockEntryGenerated(FrappeModel):
    doctype = 'Stock Entry'
    naming_series = models.CharField(max_length=140, blank=True, null=True, default='')
    stock_entry_type = models.CharField(max_length=140, blank=True, null=True, default='')
    weight_per_piece = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    outgoing_stock_entry = models.CharField(max_length=140, blank=True, null=True, default='')
    source_stock_entry = models.CharField(max_length=140, blank=True, null=True, default='')
    purpose = models.CharField(max_length=140, blank=True, null=True, default='')
    company = models.CharField(max_length=140, blank=True, null=True, default='')
    work_order = models.CharField(max_length=140, blank=True, null=True, default='')
    is_fg_conversion = models.SmallIntegerField(default=0)
    purchase_order = models.CharField(max_length=140, blank=True, null=True, default='')
    subcontracting_order = models.CharField(max_length=140, blank=True, null=True, default='')
    delivery_note_no = models.CharField(max_length=140, blank=True, null=True, default='')
    sales_invoice_no = models.CharField(max_length=140, blank=True, null=True, default='')
    purchase_receipt_no = models.CharField(max_length=140, blank=True, null=True, default='')
    posting_date = models.DateField(null=True, blank=True)
    posting_time = models.TimeField(null=True, blank=True)
    set_posting_time = models.SmallIntegerField(default=0)
    inspection_required = models.SmallIntegerField(default=0)
    from_bom = models.SmallIntegerField(default=0)
    bom_no = models.CharField(max_length=140, blank=True, null=True, default='')
    fg_completed_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    use_multi_level_bom = models.SmallIntegerField(default=1)
    from_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    source_warehouse_address = models.CharField(max_length=140, blank=True, null=True, default='')
    source_address_display = models.TextField(blank=True, null=True, default='')
    to_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    target_warehouse_address = models.CharField(max_length=140, blank=True, null=True, default='')
    target_address_display = models.TextField(blank=True, null=True, default='')
    scan_barcode = models.CharField(max_length=140, blank=True, null=True, default='')
    total_incoming_value = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_outgoing_value = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    value_difference = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_additional_costs = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    supplier = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_name = models.CharField(max_length=140, blank=True, null=True, default='')
    supplier_address = models.CharField(max_length=140, blank=True, null=True, default='')
    address_display = models.TextField(blank=True, null=True, default='')
    select_print_heading = models.CharField(max_length=140, blank=True, null=True, default='')
    letter_head = models.CharField(max_length=140, blank=True, null=True, default='')
    is_opening = models.CharField(max_length=140, blank=True, null=True, default='')
    project = models.CharField(max_length=140, blank=True, null=True, default='')
    remarks = models.TextField(blank=True, null=True, default='')
    per_transferred = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    total_amount = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    job_card = models.CharField(max_length=140, blank=True, null=True, default='')
    amended_from = models.CharField(max_length=140, blank=True, null=True, default='')
    credit_note = models.CharField(max_length=140, blank=True, null=True, default='')
    pick_list = models.CharField(max_length=140, blank=True, null=True, default='')
    add_to_transit = models.SmallIntegerField(default=0)
    apply_putaway_rule = models.SmallIntegerField(default=0)
    is_return = models.SmallIntegerField(default=0)
    process_loss_qty = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    process_loss_percentage = models.DecimalField(max_digits=21, decimal_places=9, null=True, blank=True)
    asset_repair = models.CharField(max_length=140, blank=True, null=True, default='')
    last_scanned_warehouse = models.CharField(max_length=140, blank=True, null=True, default='')
    is_additional_transfer_entry = models.SmallIntegerField(default=0)
    subcontracting_inward_order = models.CharField(max_length=140, blank=True, null=True, default='')
    cost_center = models.CharField(max_length=140, blank=True, null=True, default='')

    class Meta:
        abstract = True
